BD-1005: Add X-Braze-Bulk header to /users/track endpoint
braze-inc/braze-docs pull request #2449
Opened 2021-07-26 22:46 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

**Description of Change:**
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-1005**

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [ ] No

> If yes, please note the date of the feature release.

---
---

<details>
<summary>PR Checklist</summary>

- [ ] Check that all links work!
- [ ] Ensure you have completed [our CLA](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is _done and ready to be reviewed for merge_.
- [ ] Tag others as Reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `config/nginx.conf.erb`.

</details>

<details>
<summary>Writing & Style Quick Tips</summary>

- Use the formatting shown on the [Styling Test Page](https://github.com/Appboy/braze-docs/blob/develop/_docs/_home/styling_test_page.md) to create unique templates and vehicles for your information.
- Use Action verbs!
- Capitalize proper nouns, unique Braze tools and features, custom Braze channels, and all Header titles.
- Redirect when necessary!
- Always speak to the Braze customer - refer to them as “you”, whether they are an Engineer/Developer, a Marketer, or an Admin.
- On Voice: You should aim to be a Friendly Professor. Imagine, if you will, the smartest, but also kindest professor you had. You know, the one who showed you your potential and tested you, but also went slowly in class so you could take great notes and learn some things? Don't be too peppy, but don't be formal. You’re not selling anything - you’re instructing and informing and enabling.

_Consult the [Docs Text Formatting Guide](https://github.com/Appboy/braze-docs/wiki/Special-Formatting) and the [Docs Writing Style Guide & Best Practices](https://github.com/Appboy/braze-docs/wiki/Writing-Style-Guide-&-Best-Practices) for more details._

</details>

<details>
<summary>ATTENTION: For PR Reviewers</summary>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then "Docs". A `502` error just means you should refresh until you see the Docs Home page.
</details>

---
---

2021-07-27 16:33 UTC, KellieHawks requested changes

2021-07-27 16:33 UTC, KellieHawks commented on _docs/_api/endpoints/user_data/post_user_track.md
> +curl --location --request POST 'https://anna.braze.com/users/track' \
Hey @bre-fitzgerald can we update this to include the standard example endpoint instead of the "anna.braze.com" one: https://rest.iad-01.braze.com/users/track

2021-07-27 17:00 UTC, bre-fitzgerald commented on _docs/_api/endpoints/user_data/post_user_track.md
> +curl --location --request POST 'https://anna.braze.com/users/track' \
Good catch! Updated :)

2021-07-27 17:16 UTC, KellieHawks approved these changes
lgtm!

2021-07-27 17:16 UTC, merged

2023-11-15 16:00 UTC, Tenzer commented
Hi! The documentation doesn't really mention if there's any benefit or difference for the end-user by setting the `X-Braze-Bulk` header to true. Will the endpoint behave any differently? Why should an end-user bother with adding this header?

2023-11-15 20:12 UTC, josh-mccrowell-braze commented
Hi @Tenzer,

Thanks for reaching out! When digging into this issue, we found that this part of the documentation was out of date. We have removed the documentation about the `x-braze-bulk` header as of 11/16/23. Thanks for bringing up this issue!

-The Documentation Team @ Braze

2023-11-15 20:14 UTC, Tenzer commented
Thank you for getting back about this so quickly and thank you for the clarification. I won't implement the header on our side then!