Update liquid_use_cases.md with 30 for 30 tips
braze-inc/braze-docs pull request #2468
Opened 2021-07-30 17:18 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

**Description of Change:**
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [ ] No

> If yes, please note the date of the feature release.

---
---

<details>
<summary>PR Checklist</summary>

- [ ] Check that all links work!
- [ ] Ensure you have completed [our CLA](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is _done and ready to be reviewed for merge_.
- [ ] Tag others as Reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `config/nginx.conf.erb`.

</details>

<details>
<summary>Writing & Style Quick Tips</summary>

- Use the formatting shown on the [Styling Test Page](https://github.com/Appboy/braze-docs/blob/develop/_docs/_home/styling_test_page.md) to create unique templates and vehicles for your information.
- Use Action verbs!
- Capitalize proper nouns, unique Braze tools and features, custom Braze channels, and all Header titles.
- Redirect when necessary!
- Always speak to the Braze customer - refer to them as “you”, whether they are an Engineer/Developer, a Marketer, or an Admin.
- On Voice: You should aim to be a Friendly Professor. Imagine, if you will, the smartest, but also kindest professor you had. You know, the one who showed you your potential and tested you, but also went slowly in class so you could take great notes and learn some things? Don't be too peppy, but don't be formal. You’re not selling anything - you’re instructing and informing and enabling.

_Consult the [Docs Text Formatting Guide](https://github.com/Appboy/braze-docs/wiki/Special-Formatting) and the [Docs Writing Style Guide & Best Practices](https://github.com/Appboy/braze-docs/wiki/Writing-Style-Guide-&-Best-Practices) for more details._

</details>

<details>
<summary>ATTENTION: For PR Reviewers</summary>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then "Docs". A `502` error just means you should refresh until you see the Docs Home page.
</details>

---
---

2021-07-30 17:35 UTC, KellieHawks requested changes
Hey! Looks great, just made a few minor suggestions. Thanks!

2021-07-30 17:35 UTC, KellieHawks commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> +{%if today == "2021-12-24" or today == "2021-12-25" or today == "2021-12-26” %}
Can you add a space between the percentage sign and the "if", "abort_message", and "endif"

2021-07-30 17:35 UTC, KellieHawks commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> +### Avoid sending messages on major holidays {#holiday-avoid}
Capitalize the use case title.

2021-07-30 17:35 UTC, KellieHawks commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> +### Avoid sending emails to customers that have blocked marketing emails {#misc-avoid-blocked-emails}
Capitalize use case title.

2021-07-30 22:45 UTC, bre-fitzgerald commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> +{%if today == "2021-12-24" or today == "2021-12-25" or today == "2021-12-26” %}
Good catch, thanks!!

2021-08-03 14:24 UTC, KellieHawks approved these changes
Looks great. Thanks for adding this in.

2021-08-03 14:25 UTC, merged