Campaign and Canvas Revamp
braze-inc/braze-docs pull request #2578
Opened 2021-08-25 18:09 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> Reorganizing and adding new content for the Campaigns and Canvas sections of the user guide.

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [x] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the chart below to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTtzHpcihaXTTYD85LoKIvYBvpCQFLr8n0BDKRDRAMEz_DnZdHJJINKL24r4JXkRUui24pl_DVxbu2T/pub)
- [Technical Documentation Style Guide](https://docs.google.com/document/d/e/2PACX-1vTtzHpcihaXTTYD85LoKIvYBvpCQFLr8n0BDKRDRAMEz_DnZdHJJINKL24r4JXkRUui24pl_DVxbu2T/pub#h.wstt3flbts5k)
- [Styling Test Page](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_home/styling_test_page.md)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then `Docs`, this can take up to 5 minutes to load. A `502` error means the deployment is still loading, refresh the page, and try again.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Application Infrastructure<br>Data Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Intelligence<br>Product Partnerships<br>SMS<br>Internal Tools</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Reporting<br>Ingestion<br>Platforms and Channels<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Messaging and Automation<br>Dashboard Infrastructure<br>Email</td>
  </tr>
</table>
</details>

2021-09-28 21:40 UTC, bre-fitzgerald commented
@cla-bot check

2021-09-28 22:18 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/campaigns/building_campaigns.md
> +nav_title: Building Campaigns
@bre-fitzgerald Minor suggestion to align the "Building X" titles so it's either 
- "Building a Campaign" and "Building a Canvas" 
- "Building Campaigns" and "Building Canvases"

2021-09-29 15:18 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/campaigns/building_campaigns.md
> +nav_title: Building Campaigns
Updated to "Building Campaigns" and "Building Canvases" to match verb form with Managing/Testing

2021-09-29 16:06 UTC, lydia-xie approved these changes
looks great to me!

2021-09-29 16:53 UTC, KellieHawks commented on _docs/_user_guide/engagement_tools/campaigns/faq.md
Hey @bre, FAQ isn't showing up as the last thing on the left hand nav
<img width="220" alt="Screen Shot 2021-09-29 at 12 53 30 PM" src="https://user-images.githubusercontent.com/47005843/135314208-a5bb7f34-cbb9-4d13-a84a-054a75872a69.png">

2021-09-29 17:02 UTC, KellieHawks commented on _docs/_user_guide/engagement_tools/canvas/get_started/the_basics.md
> +nav_title: Canvas Basics
Hey @bre, do you mind swapping out the "Find your strategy with the five W's of visualization" section here, for the one in the Campaign basics doc I made. That one has an updated list and is formatted correctly.

2021-09-29 17:05 UTC, KellieHawks commented
minor nit, can you move experiment step above FB audience step and google audience step so the same type of steps are all grouped together in the right-hand nav
<img width="177" alt="Screen Shot 2021-09-29 at 1 05 09 PM" src="https://user-images.githubusercontent.com/47005843/135315883-28bd8279-be6f-4cb0-9470-82e8df2634fc.png">

2021-09-29 17:07 UTC, KellieHawks requested changes
Looks so great! Thank you for all the hard work on this. It looks so much better!! 😭 Just a couple of minor things I caught.

2021-09-29 17:08 UTC, bre-fitzgerald commented
> minor nit, can you move experiment step above FB audience step and google audience step so the same type of steps are all grouped together in the right-hand nav

@KellieHawks 
We originally decided to group it as it is ordered in the UI. I don't mind the change, just want to double-check 
cc: @lydia-xie

2021-09-29 17:10 UTC, KellieHawks commented
Ah gotcha. Wasn't sure the reason, but that makes lots of sense. We can leave it. :)

2021-09-29 17:17 UTC, KellieHawks approved these changes
💯💯💯

2021-09-29 17:17 UTC, merged