Update collapse key docs
braze-inc/braze-docs pull request #2636
Opened 2021-09-09 16:31 UTC by Bucimis

2021-09-09 16:32 UTC, froodian submitted a review, later dismissed

2021-09-09 16:34 UTC, bryanlogan requested changes
Digging into this more, there's some confusion betwen collapse key and notification ID.   I think in these documents, it should strictly be notification ID, and collapse_key should be noted somewhere to inform the user that Braze uses one.

2021-09-09 17:33 UTC, KellieHawks commented
@cla-bot check

2021-09-09 19:39 UTC, Bucimis commented on _docs/_api/objects_filters/messaging/android_object.md
> +| `collapse_key` | FCM can simultaneously store only up to 4 collapse keys per device. If you use more than 4 collapse keys, FCM does not make any guarantees as to which ones will be kept. Braze uses
Moved the language closer to FCMs + moved collapse key docs to REST API docs exclusively, which is the only place where collapse key can be set on a Braze push.

2021-09-09 19:39 UTC, Bucimis commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/advanced_settings.md
> -## Delivery Options
Removed since 
1. The info is redundant with field descriptions
2. The only pure FCM delivery option we offer from the dashboard is TTL (notification ID is used by the SDK and unrelated to FCM specifically), and not sure making the distinction here is actually useful for users. All the fields appear undifferentiated in the dashboard + REST APIs.

2021-09-09 19:39 UTC, Bucimis commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/advanced_settings.md
> -A __"Notification ID"__ is a unique identifier for a message category of your choosing that informs the messaging service to only respect the most recent message from that ID. Setting a Notification
Last sentence was false

2021-09-09 19:39 UTC, Bucimis commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/advanced_settings.md
> +## Firebase Messaging Delivery Priority {#fcm-priority}
Updated this and "Notification Display Priority" to what they're called in the Braze dashboard (note difference with FireOS for "Notification Display Priority", not sure if we want to fix that)

2021-09-09 19:39 UTC, Bucimis commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/fireos/advanced_settings.md
> -## Delivery Options
Notification ID isn't supported on FireOS dashboard

2021-09-09 19:39 UTC, Bucimis commented on _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
> +## Notification Display Priority
Moved this section to same place it was in the Android push developer docs. @KellieHawks not sure we need the same info in two spots fwiw

2021-09-09 19:39 UTC, Bucimis commented on _docs/_user_guide/message_building_by_channel/push/android/advanced_campaign_settings.md
> +## Notification ID {#notification-id}
This is in the User Guide, updated it to match the developer docs (as it appears to be intended to do)

2021-09-09 19:40 UTC, Bucimis commented
Did a bunch of cleanup + annotated the PR with some notes to guide folks through what I did

2021-09-09 19:54 UTC, froodian approved these changes

2021-09-09 20:01 UTC, bryanlogan approved these changes

2021-09-13 14:47 UTC, chshapiro approved these changes

2021-09-14 15:55 UTC, KellieHawks commented
Addressed in this PR: https://github.com/braze-inc/braze-docs/pull/2646 due to CLA issues.

2021-09-14 15:55 UTC, closed without merging