BD-1069: Add support for array of objects data type
braze-inc/braze-docs pull request #2649
Opened 2021-09-14 21:24 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> I'm adding a new page for arrays of objects.

Closes #**BD-1069**

#### Is this change associated with a Braze feature/product release?
- [x] Yes (__Insert Feature Release Date Here__)
- [ ] No

---

2021-09-15 21:17 UTC, KellieHawks commented on _docs/_hidden/private_betas/array_of_objects.md
> +Update values for specific objects within an array using the `_merge_objects` parameter and the `$update` operator. Similar to updates to simple [nested custom attribute]({{site.baseurl}}/nested_cust
Can you define what a deep merge is here. Couldn't find the definition in the nested custom attribute doc

2021-09-15 21:18 UTC, KellieHawks commented on _docs/_hidden/private_betas/array_of_objects.md
> +The following example shows removing any object in the pets array that has an `id` with a value of `1`, an `id` with a value of `2`, and a `type` with a value of `dog`. If there are multiple objects
`pets`

2021-09-15 21:20 UTC, KellieHawks commented on _docs/_hidden/private_betas/array_of_objects.md
> +You can use this pets array to personalize a message. The Liquid templating example below shows how to reference the custom attribute object properties saved from the above API request and use them i
`pets` here too?

2021-09-15 21:23 UTC, KellieHawks commented on _docs/_hidden/private_betas/array_of_objects.md
> +For example, if you want to filter the pets array of objects based on the `type` field, enter `[].type` and choose which type of pet to filter for, such as `snake`.
`pets` here too? Not sure if it's worth formatting it this way for all the instances of "`pets` array". I'd either change the initial one, or codify the text for the rest of the instances.

2021-09-15 21:24 UTC, KellieHawks commented on _docs/_hidden/private_betas/array_of_objects.md
> +![Filter by pet type equals snake][3]
Just as a nit, can we crop the images a little more to just include the filters?

2021-09-15 21:25 UTC, KellieHawks requested changes
Hey Bre! Looks great, just a couple of minor formatting things I wanted to bring up. Let me know if you have any Qs!

2021-09-15 22:20 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/array_of_objects.md
> +Update values for specific objects within an array using the `_merge_objects` parameter and the `$update` operator. Similar to updates to simple [nested custom attribute]({{site.baseurl}}/nested_cust
Good point, added a brief sentence to the nested custom attribute doc.

2021-09-16 14:08 UTC, KellieHawks approved these changes
Looks great! Thanks for those edits!

2021-09-16 14:08 UTC, merged