BD-1140: Add documentation for purchases/product_list endpoint
braze-inc/braze-docs pull request #2870
Opened 2021-11-03 19:52 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> Add documentation for `purchases/product_list` endpoint

Closes #**BD-1140**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [ ] No

2021-11-03 20:05 UTC, bre-fitzgerald commented
Hi @johndinh—here's what I put together for the `purchases/product_list` endpoint. Right now the link to the Postman collection is a filler, I'll update it and Postman with the endpoint once this content is finalized.

Feel free to tag anyone else as needed for review :)

2021-11-05 13:23 UTC, johndinh requested changes
Reviewed and left one question.

@mkigikm could you take a look at this too before it goes out?  Thank you!

2021-11-05 13:23 UTC, johndinh commented on _docs/_api/endpoints/export/purchases/get_list_product_id.md
> +| `page`  | Required | String | The page of your product list that you would like to view. |
Not sure if page is required.  I was able to submit a request in Sweeney without it and I got a response with products.

2021-11-12 18:25 UTC, bre-fitzgerald commented on _docs/_api/endpoints/export/purchases/get_list_product_id.md
> +| `page`  | Required | String | The page of your product list that you would like to view. |
Changed to optional!

2021-11-15 16:16 UTC, mkigikm commented on _docs/_api/endpoints/export/purchases/get_list_product_id.md
> +https://rest.iad-03.braze.com/purchases/product_list?page=1
Do we want to use iad-01 for this example? It looks like that's what the others all do to me.

2021-11-15 16:29 UTC, mkigikm approved these changes

2021-11-15 16:47 UTC, johndinh approved these changes
LGTM!

2021-11-15 18:20 UTC, KellieHawks approved these changes
Looks good to me!

2021-11-15 18:39 UTC, merged