Knak Partnership Docs
braze-inc/braze-docs pull request #3140
Opened 2022-01-26 21:33 UTC by KellieHawks

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the chart below to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTtzHpcihaXTTYD85LoKIvYBvpCQFLr8n0BDKRDRAMEz_DnZdHJJINKL24r4JXkRUui24pl_DVxbu2T/pub)
- [Technical Documentation Style Guide](https://docs.google.com/document/d/e/2PACX-1vTtzHpcihaXTTYD85LoKIvYBvpCQFLr8n0BDKRDRAMEz_DnZdHJJINKL24r4JXkRUui24pl_DVxbu2T/pub#h.wstt3flbts5k)
- [Styling Test Page](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_home/styling_test_page.md)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then `Docs`, this can take up to 5 minutes to load. A `502` error means the deployment is still loading, refresh the page, and try again.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Application Infrastructure<br>Data Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Intelligence<br>Product Partnerships<br>SMS<br>Internal Tools</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Reporting<br>Ingestion<br>Platforms and Channels<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Messaging and Automation<br>Dashboard Infrastructure<br>Email</td>
  </tr>
</table>
</details>

2022-01-26 21:38 UTC, KellieHawks commented
@bradyknak When you get a chance, please sign our contributor's license agreement (CLA). This allows us to use your contributions on our site. Thanks!

https://www.braze.com/docs/cla/

2022-01-27 14:46 UTC, bradyknak commented
@KellieHawks , CLA signed! Thanks so much. No more action required on my part, is that right?

2022-01-27 14:54 UTC, KellieHawks commented
> @cla-bot check


> @KellieHawks , CLA signed! Thanks so much. No more action required on my part, is that right?

@bradyknak Correct! Your documentation is good to go, we are just waiting for the go-ahead from our partner team to publish it on our site. Thanks!

2022-02-11 16:44 UTC, lydia-xie requested changes
looks great! left a couple of minor suggestions!

2022-02-11 16:44 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/email_templates/knak.md
> +description: "This article outlines the partnership between Braze and Knak, a campaign creation platform that allows you to create fully-responsive emails in minutes or hours instead of days or weeks
```suggestion
description: "This article outlines the partnership between Braze and Knak, a campaign creation platform that allows you to create fully responsive emails in minutes or hours instead of days or weeks, and export them as ready-to-use Braze templates."
```

2022-02-11 16:44 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/email_templates/knak.md
> +| Braze REST API key | A Braze REST API key with full **Templates** permissions. <br><br>This can be created within the **Braze Dashboard -> Developer Console -> REST API Key -> Create New API Key**
```suggestion
| Braze REST API key | A Braze REST API key with full **Templates** permissions. <br><br>This can be created within the **Braze Dashboard > Developer Console > REST API Key > Create New API Key** |
```

Suggestion to update "->" to ">" for consistency with Step 1!

2022-02-11 16:44 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/email_templates/knak.md
> +- Currently use simple templates for emails, and want to up their game
```suggestion
- Currently use simple templates for emails and want to up their game
```

2022-02-11 17:03 UTC, lydia-xie approved these changes
lgtm!

2022-02-11 17:03 UTC, merged