Wyng Partnership Docs
braze-inc/braze-docs pull request #3186
Opened 2022-02-08 17:27 UTC by KellieHawks

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the chart below to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTtzHpcihaXTTYD85LoKIvYBvpCQFLr8n0BDKRDRAMEz_DnZdHJJINKL24r4JXkRUui24pl_DVxbu2T/pub)
- [Technical Documentation Style Guide](https://docs.google.com/document/d/e/2PACX-1vTtzHpcihaXTTYD85LoKIvYBvpCQFLr8n0BDKRDRAMEz_DnZdHJJINKL24r4JXkRUui24pl_DVxbu2T/pub#h.wstt3flbts5k)
- [Styling Test Page](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_home/styling_test_page.md)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then `Docs`, this can take up to 5 minutes to load. A `502` error means the deployment is still loading, refresh the page, and try again.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Application Infrastructure<br>Data Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Intelligence<br>Product Partnerships<br>SMS<br>Internal Tools</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Reporting<br>Ingestion<br>Platforms and Channels<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Messaging and Automation<br>Dashboard Infrastructure<br>Email</td>
  </tr>
</table>
</details>

2022-02-08 17:40 UTC, adam-ismael commented
This is great, thank you @KellieHawks!

Do we need to provide documents/assets for the [Technology Partners page](https://braze-docs-en-git-kh-doceditswyng-braze.vercel.app/docs/partners/home)?

2022-02-08 17:57 UTC, KellieHawks commented
> This is great, thank you @KellieHawks!
> 
> Do we need to provide additional documents/assets for the [Technology Partners page](https://braze-docs-en-git-kh-doceditswyng-braze.vercel.app/docs/partners/home)?

@adam-ismael Happy to help! Please have your partner contact reach out to Jen Mcnamee (Braze director of partnerships) and she will let you know what assets are needed for the page you attached and [this one](https://www.braze.com/partners/technology-partners) as well.

2022-02-11 17:21 UTC, bre-fitzgerald requested changes
Looks great! Few comments for your review @KellieHawks

2022-02-11 17:21 UTC, bre-fitzgerald commented on _docs/_partners/message_personalization/dynamic_content/wyng.md
> +To subscribe users to subscription groups, click **Add Subscription** and add your subscription group name and id. To add multiple group names and ids, click the **Add Subscription** button again.<br
```suggestion
To subscribe users to subscription groups, click **Add Subscription** and add your subscription group name and ID. To add multiple group names and IDs, click the **Add Subscription** button again.<br>![Add subscription group name and ID][8]{: style="max-width:80%;"}<br><br>
```

2022-02-11 17:21 UTC, bre-fitzgerald commented on _docs/_partners/message_personalization/dynamic_content/wyng.md
> +4. Lastly, you must map Wyng fields to Braze API fields based on your use case. Click **Select a field** to choose fields to map, and afterwards, **Save** your integration. Once saved, these mapped f
@KellieHawks Random little consistency thing, but here we have a right-angled bracket for separating steps (>) but in the prereqs we have an arrow (->). I'd pick one for consistency, probably > since it's more widely used 🤔

2022-02-11 18:07 UTC, bre-fitzgerald approved these changes

2022-02-11 18:07 UTC, merged