Alt and link text edits - Message Building by Channel - Pt. 2
braze-inc/braze-docs pull request #3275
Opened 2022-03-01 22:46 UTC by lydia-xie

Updating image alt text and link text for Email in Message Building by Channel section of User Guide

2022-03-02 23:38 UTC, bre-fitzgerald requested changes
Thanks for making all these edits! For the alt text, keep in mind that screen readers will prefix images with "Image of", and then read the alt text. I've added suggestions to remove the instances of "Image of" in your alt text, plus areas where we can add a bit more information on what the image is trying to convey.

Remember if the contents of the image are already covered somewhere else in the surrounding text, it's fine to use an empty alt tag! This tells screen readers to ignore the image. LMK if you have any questions on my suggestions and happy to chat :)

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/creating_an_email_campaign.md
> +![Image that shows the Test Send option and an example email preview.][15]
```suggestion
![Test Send option and example email preview when composing your email.][15]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/css_inline.md
> +| ![Image that shows checkbox to manage CSS inlining in HTML composer.][2]{: style="max-width:80%;"} | ![Image that shows toggle to manage CSS inlining in Drag & Drop Editor.][3]{: style="max-width:8
```suggestion
| ![Checkbox to manage CSS inlining in HTML composer.][2]{: style="max-width:80%;"} | ![Toggle to manage CSS inlining in Drag & Drop Editor.][3]{: style="max-width:80%;"} |
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +- Select the HTML Code Editor to use the existing editors and to see your existing email templates. <br><br>![Image that shows the option to select the Drag & Drop Editor as the email editing experie
```suggestion
- Select the HTML Code Editor to use the existing editors and to see your existing email templates. <br><br>![Option to select the Drag & Drop Editor as the email editing experience.][6]{: style="max-width:80%;"}
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +2. **Add Content:** Add desired content types to the various row components.<br><br>![GIF that shows an example of using Drag & Drop Editor to compose an email.][1]
TBH this GIF has so much content in it and it goes by so fast that it seems like it's just there to showcase the workflow. I'd vote leaving it blank or removing the GIF entirely (GIFs aren't very accessible anyways) 🤷‍♀️

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +![Image that shows the Auto width option in the Content tab of the Drag & Drop Editor.][2]
```suggestion
![Auto width option in the Content tab of the Drag & Drop Editor.][2]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +![Image that shows an example of the color layering in the Drag & Drop Editor.][3]
```suggestion
![Example of the color layering in the Drag & Drop Editor.][3]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +![Image that shows the Block Options for the Drag & Drop Editor.][4]{: style="float:right;max-width:25%;margin-left:15px;"}
```suggestion
![Block Options for the Drag & Drop Editor.][4]{: style="float:right;max-width:25%;margin-left:15px;"}
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +![Image that shows the options for adding personalization for the Drag & Drop Editor.][5]{: style="float:right;max-width:25%;margin-left:15px;"}
```suggestion
![Options for adding personalization for the Drag & Drop Editor.][5]{: style="float:right;max-width:25%;margin-left:15px;"}
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
> +![Image that shows the option to whitelabel individual email addresses on the Apple Certificate page.]({% image_buster /assets/img/email-relay-whitelabel-address.png %})
```suggestion
![Option to whitelist individual email addresses on the Apple Certificate page.]({% image_buster /assets/img/email-relay-whitelabel-address.png %})
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/email_private_relay_apple_SSO.md
> +![Image that shows the HOST Value column in Sendgrid DNS records section.]({% image_buster /assets/img/email-relay-dns-records.png %})
```suggestion
![HOST Value column in Sendgrid DNS records section.]({% image_buster /assets/img/email-relay-dns-records.png %})
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
> +![GIF that shows an example of how to build a card.][2]
This GIF plus the one immediately after it look pretty outdated. They also go by SO FAST 😵  I'd suggest either replacing them with a screenshot or removing them entirely.

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
>  After you've finished filling out the fields, you'll see a completed script at the bottom of your editor. Copy and paste it into the "`<head>` "section/element of your email's `HTML`.
```suggestion
After you've finished filling out the fields, you'll see a completed script at the bottom of your editor. Copy and paste it into the `<head>` element of your email's HTML.
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
> +![GIF that shows how to copy your script to paste into the email's HTML body.][3]
Same comment as above

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
> +![Image that shows an example of the card layout.][4]
Since the layout of the elements in this image is important, let's describe that! Something like "Example of the card layout. The logo is in the top left of the card. etc etc".

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
> +![Image that shows an overview of Inbox Vision for the HTML editor.][1]
```suggestion
![Overview of Inbox Vision for the HTML editor.][1]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/inbox_vision.md
> +![Image of an example code analysis on the Inbox Vision preview.][2]
```suggestion
![Example code analysis on the Inbox Vision preview.][2]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
> +![Image that shows Compose, Delivery, and Confirm workflow to create a Transactional Email campaign.][2]
```suggestion
![Compose, Delivery, and Confirm workflow to create a Transactional Email campaign.][2]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/transactional_message_api_campaign.md
> +![Image of the Create Campaign dropdown with the highlighted option for Transactional Email.][1]{: style="float:right;max-width:30%;margin-left:15px;"}
```suggestion
![Create Campaign dropdown with the highlighted option for Transactional Email.][1]{: style="float:right;max-width:30%;margin-left:15px;"}
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
> +![Image of the Link Templating tab with an example list of link templates.][1]
```suggestion
![Link Templating tab with an example list of link templates.][1]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
> +![Image of the Template Position, Query Parameters, and Template Preview fields for the link template insertion process after a URL.]({% image_buster /assets/img_archive/link_template_postappend.png
```suggestion
![Template Position, Query Parameters, and Template Preview fields for the link template insertion process after a URL.]({% image_buster /assets/img_archive/link_template_postappend.png %})
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
> +![Image of the Template Position, Prepend URL, and Template Preview fields for the link template insertion process before a URL.]({% image_buster /assets/img_archive/link_template_preappend.png %})
```suggestion
![Template Position, Prepend URL, and Template Preview fields for the link template insertion process before a URL.]({% image_buster /assets/img_archive/link_template_preappend.png %})
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/link_template.md
> +![Image of the Create Link Template option.][11]{: style="float:right;max-width:30%;"}
My vote is blank alt text or remove the image! 😄 
```suggestion
![][11]{: style="float:right;max-width:30%;"}
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/html_email_template.md
> +![Image of the API Identifier section of an HTML email template.][4]
```suggestion
![API Identifier section of an HTML email template.][4]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image of the fields to create a subscription group.][26]{: height="50%" width="50%"}
Could also be empty alt text here, since this information is in the preceding text
```suggestion
![Fields to create a subscription group.][26]{: height="50%" width="50%"}
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![GIF that shows how to set a subscription group name as a filter.][27]{: style="max-width:80%"}
```suggestion
![GIF of a user setting a subscription group name as a filter.][27]{: style="max-width:80%"}
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image that shows the option to export user subscription state data as a CSV file.][29]
Also could be empty alt text, since the preceding sentence covers it!
```suggestion
![Option to export user subscription state data as a CSV file.][29]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image of the Outbound Email Settings panel.][19]
```suggestion
![Outbound Email Settings panel.][19]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image that shows the enabled Custom Footer toggle.][20]
```suggestion
![Enabled Custom Footer toggle.][20]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image that shows the protocol and URL values needed for the custom footer.][24]{: style="max-width:50%;"}
```suggestion
![Protocol and URL values needed for the custom footer.][24]{: style="max-width:50%;"}
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image of an example email composed without a footer.][21]
```suggestion
![Example email composed without a footer.][21]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image of a no-footer campaign composition.][22]
```suggestion
![No-footer campaign composition.][22]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image with the Set Custom Plaintext Footer option selected.][23]{: style="max-width:70%" }
```suggestion
![Email with Set Custom Plaintext Footer option selected.][23]{: style="max-width:70%" }
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image of an example custom unsubscribe email in the Custom Unsubscribe Page panel.][11]
```suggestion
![Custom unsubscribe email in the Custom Unsubscribe Page panel.][11]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image that shows an example of a user profile's subscription status as subscribed to email and opted-in to push.][16]{: style="max-width:60%" }
```suggestion
![A user profile's subscription status as subscribed to email and opted-in to push.][16]{: style="max-width:60%" }
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image of a audience targeting example for users who are subscribed or opted in in the Advanced Options of the Target Users step.][17]
```suggestion
![Audience targeting example for users who are subscribed or opted in the Advanced Options of the Target Users step.][17]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/managing_user_subscriptions.md
> +![Image that shows the Email Subscription Status used as a segment filter.][18]
```suggestion
![Email Subscription Status used as a segment filter.][18]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
> +![Image of the Drag and Drop Editor badge in the Email Body section]({% image_buster /assets/img/dnd_badge_icon.png %})
```suggestion
![Drag and Drop Editor badge in the Email Body section]({% image_buster /assets/img/dnd_badge_icon.png %})
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
> +![Image of the Email Template Details panel in the HTML editor.]({% image_buster/assets/img/email_templates/template3.png %})
```suggestion
![Email Template Details panel in the HTML editor.]({% image_buster/assets/img/email_templates/template3.png %})
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
> +![Image of the dropdown in the Body tab that displays options for the editor types.]({% image_buster/assets/img/email_templates/template4.png %})
```suggestion
![Dropdown in the Body tab that displays options for the editor types.]({% image_buster/assets/img/email_templates/template4.png %})
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
> +![Image of an errors and warnings list from an example email.][1]{: style="float:right;max-width:40%;margin-left:15px;"}
```suggestion
![Errors and warnings list from an example email.][1]{: style="float:right;max-width:40%;margin-left:15px;"}
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
> +![Image that shows an example email preview to be sent for testing.][6]
```suggestion
![Example email preview to be sent for testing.][6]
```

2022-03-02 23:38 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/templates/email_template.md
> +![Image of an example Template API Identifier.][5]
```suggestion
![Example Template API Identifier.][5]
```

2022-03-02 23:50 UTC, lydia-xie commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +2. **Add Content:** Add desired content types to the various row components.<br><br>![GIF that shows an example of using Drag & Drop Editor to compose an email.][1]
Will incorporate this feedback into my DND revamp!

2022-03-02 23:51 UTC, lydia-xie commented on _docs/_user_guide/message_building_by_channel/email/gmail_promotions_tab.md
> +![GIF that shows an example of how to build a card.][2]
Noted!

2022-03-03 00:21 UTC, bre-fitzgerald approved these changes
🙌

2022-03-03 00:21 UTC, merged