Drag & Drop Editor - Docs Rework
braze-inc/braze-docs pull request #3298
Opened 2022-03-03 23:54 UTC by lydia-xie

Updating Drag & Drop Editor docs based on feedback from Product

2022-03-16 20:26 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks.md
> +| `Add Personalization` |  Located on the left menu. Allows you to lookup standard Liquid snippets such as default attributes, custom attributes, content blocks etc. |
```suggestion
| `Add Personalization` |  Located on the left menu. Allows you to lookup standard Liquid snippets such as default attributes, custom attributes, content blocks, etc. | 
```

2022-03-16 20:27 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md
> +description: "This article covers various FAQs related to the Drag & Drop editor."
```suggestion
description: "This article covers various FAQs related to the Drag & Drop Editor."
```

2022-03-16 20:29 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/faq.md
> +### Can I save my Drag & Drop Email as a template after I build it within my campaign or Canvas?
Hmm. Not entirely sure that Drag & Drop Email needs to be capitalized. 🤔

2022-03-16 20:31 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> -article_title: Drag & Drop Editor Overview
Hey, I think Drag & Drop Editor Overview should be kept as the article title so that users won't just see "Overview" in the search results.

2022-03-16 20:33 UTC, lydia-xie commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> -article_title: Drag & Drop Editor Overview
Whoops, good call!

2022-03-16 20:34 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> -article_title: Drag & Drop Editor Overview
Actually, after looking through the content, there's probably a better article title than what I suggested. Maybe "Create a Drag & Drop Email"?

2022-03-16 20:35 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +> With the Drag & Drop Editor, you can create completely custom and personalized email messages in either Campaigns or Canvas using the drag & drop editing experience.
I think you probably want this under the article title?

2022-03-16 20:35 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +> With the Drag & Drop Editor, you can create completely custom and personalized email messages in either Campaigns or Canvas using the drag & drop editing experience.
```suggestion
> With the Drag & Drop Editor, you can create completely custom and personalized email messages in either campaigns or Canvas using the drag & drop editing experience.
```

2022-03-16 20:39 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +[12]: {site.baseurl}/user_guide/message_building_by_channel/email/creating_an_email_campaign/#step-4-build-the-remainder-of-your-campaign-or-canvas
```suggestion
[12]: {{site.baseurl}}/user_guide/message_building_by_channel/email/creating_an_email_campaign/#step-4-build-the-remainder-of-your-campaign-or-canvas
```

2022-03-16 20:39 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +[7]: {site.baseurl}/user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks/
```suggestion
[7]: {{site.baseurl}}/user_guide/message_building_by_channel/email/drag_and_drop/dnd_editor_blocks/
```

2022-03-16 20:39 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +[13]: {site.baseurl}/user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings/
```suggestion
[13]: {{site.baseurl}}/user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings/
```

2022-03-16 20:41 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
>  ![Options for adding personalization for the Drag & Drop Editor.][5]{: style="float:right;max-width:25%;margin-left:15px;"}
Hey! Can you move this line down a couple of lines? It's bumping into the above image and is looking a little funny on my computer. Thanks!

2022-03-16 20:42 UTC, KellieHawks requested changes
Looks great! Love the edits, found a couple of things for you to take a look at. :)

2022-03-17 17:07 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/best_practices/templates_styling.md
> +
hidden: true

2022-03-17 17:08 UTC, KellieHawks requested changes
looks good! Found one last thing to look over.

2022-03-17 17:18 UTC, KellieHawks approved these changes
Looks great!

2022-03-17 17:18 UTC, merged