Removal of _ formatting, replacing with * formatting
braze-inc/braze-docs pull request #3315
Opened 2022-03-09 21:18 UTC by KellieHawks

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the chart below to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then `Docs`, this can take up to 5 minutes to load. A `502` error means the deployment is still loading, refresh the page, and try again.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Application Infrastructure<br>Data Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Intelligence<br>Product Partnerships<br>SMS<br>Internal Tools</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Reporting<br>Ingestion<br>Platforms and Channels<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Messaging and Automation<br>Dashboard Infrastructure<br>Email</td>
  </tr>
</table>
</details>

2022-03-09 21:21 UTC, KellieHawks commented on _docs/_developer_guide/platform_wide/analytics_overview.md
> +| Check if the numeric attribute **does not equal** a **numver**| **DOES NOT EQUAL** | **NUMBER** |
```suggestion
| Check if the numeric attribute **does not equal** a **number**| **DOES NOT EQUAL** | **NUMBER** |
```

2022-03-09 21:21 UTC, KellieHawks commented on _docs/_developer_guide/platform_wide/app_group_configuration.md
> +The best way to go about this if you want to separate the old vs. new app would be to create a new app within the same app group. This way, you can effectively target only users on the new version by
```suggestion
The best way to go about this if you want to separate the old vs. new app would be to create a new app within the same app group. This way, you can effectively target only users on the new version by selecting that app as you create your segments. If you did want to message users who are still on the old version, you can use [Liquid to select the old app and filter the previous app version](https://www.youtube.com/watch?v=Dv__RAUwamA).
```

2022-03-09 21:22 UTC, KellieHawks commented on _docs/_hidden/other/support_contact.md
> +                 **html: '<div class="no_results">No results were found with your current search. Try to change the search query.</div>',
```suggestion
                 __html: '<div class="no_results">No results were found with your current search. Try to change the search query.</div>',
```

2022-03-09 21:22 UTC, KellieHawks commented on _docs/_hidden/other/support_contact.md
> +                **html: resulttemplate,
```suggestion
                __html: resulttemplate,
```

2022-03-09 21:23 UTC, KellieHawks commented on _docs/_home/styling_test_page.md
> +	def **init**(self, var):
```suggestion
	def __init__(self, var):
```

2022-03-09 21:24 UTC, KellieHawks commented on _docs/_partners/data_and_infrastructure_agility/support/pypestream.md
> +PATH = os.path.dirname(**file**)
```suggestion
PATH = os.path.dirname(__file__)
```

2022-03-09 21:25 UTC, KellieHawks commented on _docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
> +![The data key-value pairs for this example are "app_group_id" set as "your-app-group-id", "campaign_id" set as "your-campaign-id", and "trigger_properties**name" set as "Post Name".][10]
```suggestion
![The data key-value pairs for this example are "app_group_id" set as "your-app-group-id", "campaign_id" set as "your-campaign-id", and "trigger_properties__name" set as "Post Name".][10]
```

2022-03-09 21:25 UTC, KellieHawks commented on _docs/_partners/data_and_infrastructure_agility/workflow_automation/zapier.md
> +- **Data** : `trigger_properties**name`, `api_key`, and `campaign_id`
```suggestion
- **Data** : `trigger_properties__name`, `api_key`, and `campaign_id`
```

2022-03-09 21:25 UTC, KellieHawks commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/talonone.md
> +You can also access the entire response from Talon.One by accessing {% raw %} `{{result}}` {% endraw %} directly, which will look similar to `{"id"=>1548040, "value"=>"44D4-U4PL", "**http_status_code
```suggestion
You can also access the entire response from Talon.One by accessing {% raw %} `{{result}}` {% endraw %} directly, which will look similar to `{"id"=>1548040, "value"=>"44D4-U4PL", "__http_status_code__"=>200}`.
```

2022-03-09 21:26 UTC, KellieHawks commented on _docs/_partners/message_personalization/location/radar.md
> +{% if nearbyplaces.**http_status_code** != 200 %}
```suggestion
{% if nearbyplaces.__http_status_code__ != 200 %}
```

2022-03-09 21:30 UTC, KellieHawks commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
> +{% if connected.**http_status_code** != 200 %}
```suggestion
{% if connected.__http_status_code__ != 200 %}
```

2022-03-09 21:31 UTC, KellieHawks commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/supported_personalization_tags.md
> +You can utilize the HTTP status from a [Connected Content][38] call by first saving it as a local variable and then using the `**http_status_code**` key. For example:
```suggestion
You can utilize the HTTP status from a [Connected Content][38] call by first saving it as a local variable and then using the `__http_status_code__` key. For example:
```

2022-03-09 21:31 UTC, KellieHawks commented on _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
> +{% if result.**http_status_code** != 200 %}
```suggestion
{% if result.__http_status_code__ != 200 %}
```

2022-03-09 21:31 UTC, KellieHawks commented on _docs/_user_guide/personalization_and_dynamic_content/connected_content/local_connected_content_variables.md
> +You can utilize the HTTP status from a Connected Content call by first saving it as a local variable and then using the `**http_status_code**` key. For example:
```suggestion
You can utilize the HTTP status from a Connected Content call by first saving it as a local variable and then using the `__http_status_code__` key. For example:
```

2022-03-09 22:54 UTC, bre-fitzgerald requested changes
Looks good! Few small things for your review :)

2022-03-09 22:54 UTC, bre-fitzgerald commented on _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
> +- (instancetype **nullable)initWithMetaData:(NSDictionary *)metaData
@KellieHawks  should this be omitted from the change?

2022-03-09 22:54 UTC, bre-fitzgerald commented on _docs/_developer_guide/platform_integration_guides/ios/content_cards/implementation_guide.md
> +#### **Implementation components**<br><br>
```suggestion
#### Implementation components<br><br>
```

2022-03-09 22:54 UTC, bre-fitzgerald commented on _docs/_developer_guide/platform_integration_guides/ios/in-app_messaging/implementation_guide.md
> +#### **Adding additional behavior to our default UI**<br><br>
```suggestion
#### Adding additional behavior to our default UI<br><br>
```

2022-03-10 16:01 UTC, bre-fitzgerald submitted a review, later dismissed

2022-03-10 16:40 UTC, bre-fitzgerald approved these changes

2022-03-10 16:44 UTC, merged