Create google_play_privacy.md
braze-inc/braze-docs pull request #3430
Opened 2022-04-12 13:07 UTC by bryanlogan

# Pull Request/Issue Resolution

#### Description of Change:
Add informtion on Google Privacy

Closes # SDK-2408

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [X] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [X] Check that all links work.
- [X] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [X] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the chart below to tag the appropriate reviewer.
- [X] Tag others as reviewers as necessary.
- [X] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Data Infrastructure<br>Platform Infrastructure<br>Quality Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Internal Tools<br>Product Partnerships<br>SDKs<br>SMS</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Channels<br>FIX<br>Intelligence<br>Reporting<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Email (Composition and Infrastructure)<br>Ingestion<br>Messaging</td>
  </tr>
</table>
</details>

2022-04-12 17:50 UTC, bryanlogan commented
https://braze-docs-en-git-sdk-2408googleplayprivacy-braze.vercel.app/docs/developer_guide/platform_integration_guides/android/google_play_privacy
Let me know what you think of the layout.  One of the goals was to have all the Google wording there for people trying to match it up.  I also wanted to give too much information instead of too little, but feel free if you think something should be removed.

2022-04-12 18:36 UTC, davidbielik requested changes

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +Google requires you to disclose your apps' privacy and security practices when submitting to the Google Play Consolse.
```suggestion
Starting April 2022, Android developers will be required to complete the [Google Play's Data safety form](https://support.google.com/googleplay/android-developer/answer/10787469) to disclose privacy and security practices.
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +This guide will give you information on how Braze handles your app data to help you answer the questions. As the app developer, you are in control of what data Braze receives. Data received by Braze
```suggestion
This guide explains how Braze handles your app data and will provide information related to this new form. 

As the app developer, you are in control of what data you send to Braze. Data received by Braze is processed according to your instructions. This is what Google classifies as a [service provider][3]. 
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +
```suggestion

{% alert important %}
**Note**:  This article provides information related to the data the Braze SDK processes as related to Google Safety Section Questionnaire. This article is not providing legal advice, so we recommend consulting with your legal team prior to submitting any information to Google.
{% endalert %}
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +|Does your app collect or share any of the required user data types?|Yes, but what data is collected is configured by the app developer|
```suggestion
|Does your app collect or share any of the required user data types?|Yes, the Braze Android SDK collects data as configured by the app developer|
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +For more information about how to handle user requests for their data and deletion, see [Braze Data Retention Information][1]
```suggestion
For more information about how to handle user requests for their data and deletion, see [Braze Data Retention Information][1].
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +For the data collected by Braze, that's going to be dependent on what data you as an app developer choose to collect.  While Braze has fields for the most common data (name, email, etc), users may al
```suggestion
The data collected by Braze is determined by your specific integration and the user data you choose to collect. To learn more about what data Braze collects by default, and how to disable certain attributes, please see our [SDK Data Collection Overview](https://www.braze.com/docs/user_guide/data_and_analytics/user_data_collection/sdk_data_collection/#minimum-integration)
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td rowspan="15">Only data that is configured by you to be sent to Braze.</td>
```suggestion
            <td rowspan="15">Not collected by default.</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td rowspan="2">Only data that is configured by you to be sent to Braze. INSERT HIPAA STUFF HERE?</td>
```suggestion
            <td rowspan="2">Not collected by default.</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td rowspan="2">Only data that is configured by you to be sent to Braze.</td>
```suggestion
            <td rowspan="2">Not collected by default.</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>If configured by you Braze may generate In-App Messages and Push notification that are sent to users, and we store read-indicators on them.</td>
```suggestion
            <td>If you send In-app messages or push notifications through Braze, we collect information on when users have opened or read these messages.</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td rowspan="8">No.</td>
```suggestion
            <td rowspan="8">Not collected</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>Only data that is configured by you to be sent to Braze.</td>
```suggestion
            <td>Braze collects session activity data by default. All other interactions and activity is determined by your app's custom integration.</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>No.</td>
```suggestion
            <td>Not collected.</td>            
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>No.</td>
```suggestion
            <td>Not collected.</td>            
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td rowspan="2">Only data that is configured by you to be sent to Braze.</td>
```suggestion
            <td rowspan="2">Not collected by default.</td>            
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>No.</td>
```suggestion
            <td>Not collected.</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>Yes, Braze does collect crash logs for errors that occur within the SDK. This contains the user's phone model and OS level, along with a Braze specific user ID.</td>
```suggestion
            <td>Braze collects crash logs for errors that occur within the SDK. This contains the user's phone model and OS level, along with a Braze specific user ID.</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>No.</td>
```suggestion
            <td>Not collected.</td>            
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>No.</td>
```suggestion
            <td>Not collected.</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>Yes, Braze generates a random ID for your device.</td>
```suggestion
            <td>Braze generates a random ID for each user's device.</td>
```

2022-04-12 18:36 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +You can also see the other device data that Braze collects, along with how to disable them, that falls oustide of Google Play's Data Safety guidelines [here][2]
```suggestion
To learn more about other device data that Braze collects which may fall outside the scope of Google Play's Data Safety guidelines, see our [Android Storage Overview][2] and our [SDK Data Collection Options](https://www.braze.com/docs/user_guide/data_and_analytics/user_data_collection/sdk_data_collection/).
```

2022-04-12 19:14 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +Starting April 2022, Android developers will be required to complete the [Google Play's Data safety form](https://support.google.com/googleplay/android-developer/answer/10787469) to disclose privacy
```suggestion
Starting April 2022, Android developers will be required to complete [Google Play's Data safety form](https://support.google.com/googleplay/android-developer/answer/10787469) to disclose privacy and security practices.
```

2022-04-12 19:14 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +{% endalert %}
```suggestion
{% endalert %}


```

2022-04-12 19:14 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +The data collected by Braze is determined by your specific integration and the user data you choose to collect. To learn more about what data Braze collects by default, and how to disable certain att
```suggestion
The data collected by Braze is determined by your specific integration and the user data you choose to collect. To learn more about what data Braze collects by default, and how to disable certain attributes, please see our [SDK Data Collection Overview](https://www.braze.com/docs/user_guide/data_and_analytics/user_data_collection/sdk_data_collection/#minimum-integration).
```

2022-04-12 19:16 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +nav_title: Answers for Google Play Store Privacy Questions
```suggestion
nav_title: Google Play Privacy Questionnaire
```

2022-04-13 17:21 UTC, Bucimis approved these changes

2022-04-13 17:21 UTC, Bucimis commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>Braze generates a random ID for each user's device.</td>
Maybe refer to the "Device ID" row in https://www.braze.com/docs/user_guide/data_and_analytics/user_data_collection/sdk_data_collection#minimum-integration

2022-04-13 17:21 UTC, Bucimis commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +Starting April 2022, Android developers will be required to complete [Google Play's Data safety form](https://support.google.com/googleplay/android-developer/answer/10787469) to disclose privacy and
```suggestion
As of April 2022, Android developers are required to complete [Google Play's Data safety form](https://support.google.com/googleplay/android-developer/answer/10787469) to disclose privacy and security practices.
```

This may help with staleness

2022-04-13 17:33 UTC, radixdev approved these changes
lgtm after the links are addressed

2022-04-13 17:33 UTC, radixdev commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +Starting April 2022, Android developers will be required to complete [Google Play's Data safety form](https://support.google.com/googleplay/android-developer/answer/10787469) to disclose privacy and
All links (e.g. `[Google Play's Data safety form](https://support.google.com/googleplay/android-developer/answer/10787469)`) should be in the `[link text](link identifier)` format like on line 22. I.e. put this link at the bottom.

2022-04-13 17:33 UTC, radixdev commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +This guide explains how Braze handles your app data and will provide information related to this new form.
```suggestion
This guide provides instructions on how to fill out this new form with information on how Braze handles your app data.
```

2022-04-13 17:33 UTC, radixdev commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +The data collected by Braze is determined by your specific integration and the user data you choose to collect. To learn more about what data Braze collects by default, and how to disable certain att
Use a shortlink here as well.

2022-04-13 17:33 UTC, radixdev commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +To learn more about other device data that Braze collects which may fall outside the scope of Google Play's Data Safety guidelines, see our [Android Storage Overview][2] and our [SDK Data Collection
use a shortlink here as well.

2022-04-13 17:57 UTC, bryanlogan commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>Braze generates a random ID for each user's device.</td>
You mean just copy and paste that text here?  Or try to also link to that row?

2022-04-13 19:38 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +            <td>Braze generates a deviced ID to differentiate users’ devices, and ensure messages are sent to the correct intended device.</td>
```suggestion
            <td>Braze generates a device ID to differentiate users’ devices, and ensure messages are sent to the intended device.</td>
```

2022-04-13 19:38 UTC, davidbielik commented on _docs/_developer_guide/platform_integration_guides/android/google_play_privacy.md
> +The data collected by Braze is determined by your specific integration and the user data you choose to collect. To learn more about what data Braze collects by default, and how to disable certain att
```suggestion
The data collected by Braze is determined by your specific integration and the user data you choose to collect. To learn more about what data Braze collects by default, and how to disable certain attributes, please see our [SDK Data Collection Options][5].
```

2022-04-13 19:38 UTC, davidbielik submitted a review, later dismissed

2022-04-18 16:54 UTC, davidbielik submitted a review, later dismissed

2022-04-18 17:48 UTC, KellieHawks approved these changes
Looks great!

2022-04-18 17:50 UTC, KellieHawks commented
@cla-bot check

2022-04-18 17:50 UTC, merged