Reorganize best practices for Email
braze-inc/braze-docs pull request #3441
Opened 2022-04-13 21:10 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2022-05-16 21:54 UTC, bre-fitzgerald requested changes
Looks good!! Left some suggestions for your review, LMK if you have any questions on the feedback 😎

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +There are also different approaches to creating a good subject line, ranging from asking a question to pique the reader’s interest or being more direct, to personalizing it as to engage your clientel
> Don't just stick with one subject line, try new ones out and gauge their effectiveness.

Might be a good place to link to docs on A/B testing 🤔

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +The "From" field should clearly show who the sender is. Try not to use a person’s name or an uncommon abbreviation. Instead, use a recognizable name like the company name. If using a person’s name su
Definitely suggest "your" over "the", however not 100% sure which is better between company or brand. I know marketing generally refers to their identities as brands, however.

```suggestion
The "From" field should clearly show who the sender is. Try not to use a person’s name or an uncommon abbreviation. Instead, use a recognizable name like your brand name. If using a person’s name suits your brand's methods of personalizing email, stay consistent to develop a relationship with the recipient. The “From” name should be no more than 25 characters to display appropriately on mobile.
```

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +Many users use **Email Previewing** in Gmail or Outlook. These preview areas generally allow for around 300 pixels or 85 characters of content to be shown. It is recommended that the email communicat
I'd lead with character count since that's likely to be a more recognizable measurement. Also, included a suggestion for eliminating passive voice.

```suggestion
Many users use **Email Previewing** in Gmail or Outlook. These preview areas generally allow for around 85 characters or 300 pixels of content to be shown. Try to communicate the main point of the message efficiently within that space, engaging the reader’s interest to encourage opens.
```

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +Getting out of office replies can actually provide valuable information, increasing open rates and decreasing spam reports (by removing those who don’t want to be emailed). On a personal level, a no-
```suggestion
Getting out-of-office replies can actually provide valuable information, increasing open rates and decreasing spam reports (by removing those who don’t want to be emailed). On a personal level, a no-reply can appear impersonal to recipients and may turn them away from receiving further emails from your company.
```

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +No-reply email addresses are generally not recommended for multiple reasons as they disengage your readers. Many recipients reply to the email to unsubscribe, so if they are not allowed to do that, t
> No-reply email addresses are generally not recommended for multiple reasons as they disengage your readers. Many recipients reply to the email to unsubscribe, so if they are not allowed to do that, the next course of action is more often than not marking the email as spam.

> Getting out of office replies can actually provide valuable information, increasing open rates and decreasing spam reports (by removing those who don’t want to be emailed). On a personal level, a no-reply can appear impersonal to recipients, and may turn them away from receiving further email from your company.

These two paragraphs might make more sense as a subheading under "Address styling", such as "No-reply addresses". If you do so, I'd recommend also renaming the heading "Body styling" to something like "Preheader text", since that's all this section would then refer to.

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +## Preheader character limits
```suggestion
### Preheader character limits
```

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +Here are some best practices to keep in mind when writing your preheaders:
If renaming the prior section to "Preheader text", we should move this remaining content (not the character limit tables), to that section.

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +If you are receiving this error in the editor, you likely have `base64` encoded images that have been embedded in the email itself. However, this is not the most effective way to send emails with ima
> If you are receiving this error in the editor...

What error? 🤔

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +Refer to the following table for recommended text lengths:
```suggestion
Refer to the following table for recommended text lengths.
```

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +Refer to the following table for recommended image sizes. Smaller, high quality images will load faster, so it’s recommended to use the smallest asset possible to achieve your desired output.
```suggestion
Refer to the following table for recommended image sizes. Smaller, high-quality images will load faster, so use the smallest asset possible to achieve your desired output.
```

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/email_styling.md
> +Email, on the other hand, gives no way of knowing whether recipients have the app installed. As such, providing a deep link to the app could link to an error message for these recipients who do not h
This ends somewhat ambiguously. It's heavily implied, but I'd suggest adding a definitive recommendation _not_ to use deep links in email (if that is indeed what we're recommending here).

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/use_cases.md
> +# Email Use Cases
```suggestion
# Email use cases
```

2022-05-16 21:54 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/email/best_practices/use_cases.md
> +For recommending certain products, try to present them as curated, personal suggestions that the user may like. If you're promoting a limited time offer, be sure to let users know! Ideeli does a grea
```suggestion
For recommending certain products, try to present them as curated, personal suggestions that the user may like. If you're promoting a limited-time offer, be sure to let users know! Ideeli does a great job at conveying urgency in this email:
```

2022-05-16 23:07 UTC, bre-fitzgerald submitted a review, later dismissed

2022-05-17 14:57 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/best_practices/templates_styling.md
> -page_type: reference
Add to broken link page

2022-05-17 16:20 UTC, KellieHawks approved these changes
Looks great!

2022-05-17 16:20 UTC, merged