Remove directional language: right
braze-inc/braze-docs pull request #3456
Opened 2022-04-18 20:30 UTC by KellieHawks

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the interal reviewing chart to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Data Infrastructure<br>Platform Infrastructure<br>Quality Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Internal Tools<br>Product Partnerships<br>SDKs<br>SMS</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Channels<br>FIX<br>Intelligence<br>Reporting<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Email (Composition and Infrastructure)<br>Ingestion<br>Messaging</td>
  </tr>
</table>
</details>

2022-04-18 20:30 UTC, KellieHawks commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
> +To create a new account, in the log-in dialog, click **立即注册** (new account) directly above the large blue 登录 (log in) button.
```suggestion
To create a new account, in the log-in dialog, click **立即注册** (new account) directly below the large blue 登录 (log in) button.
```

2022-04-18 21:43 UTC, bre-fitzgerald requested changes
Looks good! Left a few suggestions for your review :)

2022-04-18 21:43 UTC, bre-fitzgerald commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
> +To create a new account, in the log-in dialog, click **立即注册** (new account) directly above the large blue 登录 (log in) button.
Since we have a screenshot here to show people specifically where on the UI this is (if they're very lost), I'd recommend simplifying it to just:

```suggestion
To create a new account, in the log-in dialog, click **立即注册** (new account).
```

2022-04-18 21:43 UTC, bre-fitzgerald commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
>  ## Step 2: Register as a Baidu developer
@KellieHawks I wonder if this doc might just need a quick refresh, I poked into the Baidu developer portal linked here and it looks like they redesigned the site so these instructions are no longer accurate 🤔  For example, "register" is no longer in a dropdown:
![2022-04-18_14-19-44](https://user-images.githubusercontent.com/82903296/163879922-fcf73cdb-c9cf-4781-84ec-9e95effe4951.png)

2022-04-18 21:43 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/your_analytics_dashboards/understanding_your_app_usage_data.md
> +> You can click **Show Breakdown** located next to all of the rows of the dashboard statistics to view each statistic's value per day for the time period specified under the **Display Data For** sect
```suggestion
> You can click **Show Breakdown** for each row of the dashboard statistics to view each statistic's value per day for the time period specified under the **Display Data For** section.
```

2022-04-18 21:43 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/segments/creating_a_segment.md
> +You can unarchive the segment by navigating to it within Segments, then selecting Unarchive at the top of its page.
```suggestion
You can unarchive the segment by navigating to it within Segments, then selecting **Unarchive**.
```

2022-04-19 14:36 UTC, KellieHawks commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/integration/baidu_integration.md
>  ## Step 2: Register as a Baidu developer
Great call out, will do!

2022-04-19 14:58 UTC, bre-fitzgerald approved these changes

2022-04-19 14:58 UTC, merged