Rehaul HTML Preview
braze-inc/braze-docs pull request #3457
Opened 2022-04-18 23:23 UTC by bre-fitzgerald

2022-04-27 19:48 UTC, davidbielik commented
hey @bre-fitzgerald can i suggest we merge this page into https://www.braze.com/docs/user_guide/message_building_by_channel/in-app_messages/customize/

2022-04-27 19:50 UTC, davidbielik commented on _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
> +After your assets are added, they will appear in the **Assets for this campaign** section. Hover over an asset from the list and select <i class="fas fa-copy"></i> **Copy** to copy the file's URL to
@ekim-braze @bre-fitzgerald shouldn't this section mention the local asset replacement?

2022-04-27 21:16 UTC, bre-fitzgerald commented
> hey @bre-fitzgerald can i suggest we merge this page into [braze.com/docs/user_guide/message_building_by_channel/in-app_messages/customize](https://www.braze.com/docs/user_guide/message_building_by_channel/in-app_messages/customize/)

@davidbielik good idea! I can update the PR this week to move this content over.

2022-04-27 21:26 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
> +After your assets are added, they will appear in the **Assets for this campaign** section. Hover over an asset from the list and select <i class="fas fa-copy"></i> **Copy** to copy the file's URL to
@davidbielik can you clarify what that means? Is this referring to the behavior when you delete an asset?
![2022-04-27_14-25-29](https://user-images.githubusercontent.com/82903296/165633764-3812e26a-bd21-42f7-bded-4da8b581e9e6.png)

2022-04-27 21:28 UTC, davidbielik commented on _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
> +After your assets are added, they will appear in the **Assets for this campaign** section. Hover over an asset from the list and select <i class="fas fa-copy"></i> **Copy** to copy the file's URL to
No, we recently added functionality that removes the need to find/copy/replace asset URLs as noted here. 

@ekim-braze do you know if this was ever added to docs?

2022-05-02 21:19 UTC, davidbielik commented on _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
> +After your assets are added, they will appear in the **Assets for this campaign** section. Hover over an asset from the list and select <i class="fas fa-copy"></i> **Copy** to copy the file's URL to
@bre-fitzgerald this means that you can remove assets from the message's list of assets, but it'll remain in the account's media library.

2022-05-03 20:39 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
> +After your assets are added, they will appear in the **Assets for this campaign** section. Hover over an asset from the list and select <i class="fas fa-copy"></i> **Copy** to copy the file's URL to
Right. Is this the behavior that you want to mention? If not I'm a little confused 😅

2022-05-03 20:51 UTC, davidbielik commented on _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
> +After your assets are added, they will appear in the **Assets for this campaign** section. Hover over an asset from the list and select <i class="fas fa-copy"></i> **Copy** to copy the file's URL to
there were improvements made to the editor where you no longer have to copy/paste asset URLs (especially if you were to follow a similar flow as the old zip-upload HTML type).

I don't think anything more needs to be added re: that removal screenshot though.

2022-05-03 20:53 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/in-app_messages/preview.md
> +After your assets are added, they will appear in the **Assets for this campaign** section. Hover over an asset from the list and select <i class="fas fa-copy"></i> **Copy** to copy the file's URL to
Ahh, got it. Thanks for clarifying!!

2022-05-03 22:01 UTC, davidbielik submitted a review, later dismissed
left a few proposed changes, but otherewise looks great!

2022-05-03 22:01 UTC, davidbielik commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
> +Alternatively, you can use the asset file names directly in the HTML message.
```suggestion
```

2022-05-03 22:01 UTC, davidbielik commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
> +Changes you make in the HTML automatically render in the preview panel as you type. Any `appboyBridge` JavaScript methods you use in your HTML won’t update user profiles while previewing in the dashb
```suggestion
Changes you make in the HTML automatically render in the preview panel as you type. Any [`appboyBridge` JavaScript](#bridge) methods you use in your HTML won’t update user profiles while previewing in the dashboard.
```

2022-05-03 22:01 UTC, davidbielik commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/html_in-app_messages.md
> +| Body click | `appboyBridge.logClick()`    |
```suggestion
| Body click | `appboyBridge.logClick()`    |
|Custom Button Tracking|`appboyBridge.logClick("your custom name here")`|
```

2022-05-04 16:36 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md
> +description: ""
Please add description

2022-05-04 16:38 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/video.md
> +description: ""
add description please

2022-05-04 16:45 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md
> +Email capture messages allow you to easily prompt users of your site to submit their email address, after which it will be available within on their user profile for use in all your messaging campaig
```suggestion
Email capture messages allow you to easily prompt users of your site to submit their email address, after which it will be available within their user profile for use in all your messaging campaigns.
```

2022-05-04 16:45 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md
> +## Step 1: Create in-app message campaign
```suggestion
## Step 1: Create an in-app message campaign
```

2022-05-04 16:46 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md
> +- Different colors for the header and body text, buttons and background
```suggestion
- Different colors for the header and body text, buttons, and background
```

2022-05-04 16:47 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/color_profiles_and_css.md
> +You can customize the color scheme of your message template by either entering HEX color code or by clicking the colored box and selecting a color with the color picker.
```suggestion
You can customize the color scheme of your message template by either entering a HEX color code or by clicking the colored box and selecting a color with the color picker.
```

2022-05-04 16:48 UTC, KellieHawks requested changes
Hey Bre! Looks great, so happy to have this in docs! Caught a couple of minor edits. Thank you for all you do!

2022-05-04 18:10 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/in-app_messages/customize/email_capture_form.md
> +description: ""
Whoops, thanks for catching!! 😅

2022-05-04 18:33 UTC, merged