Extole Partnership Docs - MERGE 5/9
braze-inc/braze-docs pull request #3510
Opened 2022-04-28 20:53 UTC by KellieHawks

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the interal reviewing chart to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Data Infrastructure<br>Platform Infrastructure<br>Quality Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Internal Tools<br>Product Partnerships<br>SDKs<br>SMS</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Channels<br>FIX<br>Intelligence<br>Reporting<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Email (Composition and Infrastructure)<br>Ingestion<br>Messaging</td>
  </tr>
</table>
</details>

2022-05-04 18:18 UTC, bre-fitzgerald requested changes
Looks great! Left a few small suggestions for you :)

2022-05-04 18:18 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +| Braze REST test API key (optional) | A test API key that can be used for testing purposes if you’d like these requests sent to a separate staging Braze instance. |
I'm not sure putting "test" between "REST" and "API" is grammatically correct 🤔  
```suggestion
| Braze test REST API key (optional) | A test API key that can be used for testing purposes if you’d like these requests sent to a separate staging Braze instance. |
```

2022-05-04 18:18 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +If you only provide one Braze REST API key to Extole, only production events will be sent to Braze. If you also want to send staging/testing events, create another Braze REST API key and configure an
```suggestion
If you only provide one Braze REST API key to Extole, only production events will be sent to Braze. If you also want to send staging or testing events, create another Braze REST API key and configure an additional webhook integration in the Extole dashboard.
```

2022-05-05 14:49 UTC, ekthayer commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +| Braze REST test API key (optional) | A test API key that can be used for testing purposes if you’d like these requests sent to a separate staging Braze instance. |
Definitely a typo, thank you for pointing this out!!!

2022-05-05 14:50 UTC, ekthayer commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +If you only provide one Braze REST API key to Extole, only production events will be sent to Braze. If you also want to send staging/testing events, create another Braze REST API key and configure an
Looks good to me!

2022-05-05 14:52 UTC, ekthayer submitted a review, later dismissed

2022-05-09 15:04 UTC, bre-fitzgerald approved these changes

2022-05-09 15:08 UTC, merged