Shopify updates
braze-inc/braze-docs pull request #3582
Opened 2022-05-24 23:38 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [x] Yes (**5/30**)
- [ ] No

2022-05-25 20:40 UTC, bre-fitzgerald commented
@lydia-xie this is ready to be merged on **Friday, 5/27**. After merging, please create an ad hoc deploy and tag me for review, and I'll get it merged on Monday. Thanks!!

2022-05-25 21:06 UTC, lydia-xie requested changes
looks great! left two small comments :)

2022-05-25 21:06 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
> +By default, Braze will automatically set the delay to trigger the `shopify_abandoned_checkout` event to 1 hour of inactivity. You can set the **Abandoned Checkout Delay** from 5 minutes up to 24 hour
```suggestion
By default, Braze will automatically set the delay to trigger the `shopify_abandoned_checkout` event to one hour of inactivity. You can set the **Abandoned Checkout Delay** from 5 minutes up to 24 hours by selecting the dropdown and then selecting **Set Delay** on the Shopify partner page.
```
Minor suggestion for number formatting if we're referring to the abandonment default value but not the actual option like this sentence from earlier in the doc:

> The abandonment default is set to **1 hour** but is configurable within the **Advanced Settings** section on the Shopify partner page.

2022-05-25 21:06 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/ecommerce/shopify/shopify.md
> +| `shopify_abandoned_checkout` | [Custom Event]({{site.baseurl}}/user_guide/data_and_analytics/custom_data/custom_events/) | Shopify checkout updates webhook's trigger when a customer adds or removes
```suggestion
| `shopify_abandoned_checkout` | [Custom Event]({{site.baseurl}}/user_guide/data_and_analytics/custom_data/custom_events/) | Shopify checkout updates a webhook's trigger when a customer adds or removes items from their cart AND proceeds further into the checkout process, including adding their personal information.<br><br>Braze will listen to the inbound Shopify checkout update webhooks and trigger the `shopify_abandoned_checkout` custom event when that checkout is considered abandoned. The abandonment default is set to **1 hour** but is configurable within the **Advanced Settings** section on the Shopify partner page. |
```
Missing an article here, I think?

2022-05-25 21:16 UTC, lydia-xie approved these changes
lgtm!

2022-05-27 20:37 UTC, PAMILER commented
Hi there did you want to add new section and images to your store I'll design a brand image's for store and section
  I can build a theme from scratch

2022-05-27 22:58 UTC, merged