Postman/API updates
braze-inc/braze-docs pull request #3653
Opened 2022-06-13 20:21 UTC by KellieHawks

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the interal reviewing chart to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Data Infrastructure<br>Platform Infrastructure<br>Quality Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Internal Tools<br>Product Partnerships<br>SDKs<br>SMS</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Channels<br>FIX<br>Intelligence<br>Reporting<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Email (Composition and Infrastructure)<br>Ingestion<br>Messaging</td>
  </tr>
</table>
</details>

2022-06-13 20:22 UTC, KellieHawks commented on _docs/_api/objects_filters.md
> +# Objects and filters specifications
```suggestion
# Object and filter specifications
```

2022-06-13 20:37 UTC, bre-fitzgerald commented on _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
> +{% include rate_limits.md endpoint='default' %}
@KellieHawks I think this might not be correct 🤔 I'm not sure why this wasn't included in the original edits when I made them, but from what I can tell _I think_ these two endpoints (`external_ids/remove` and `external_ids/rename`) each have a rate limit of 1k requests per minute (not the default 250k per hour)

cc: @johndinh

2022-06-13 20:38 UTC, bre-fitzgerald commented on _docs/_api/objects_filters.md
>  nav_title: Objects & Filters
Love making this its own page!

2022-06-13 20:48 UTC, bre-fitzgerald commented on _docs/_api/endpoints/user_data/external_id_migration/post_external_ids_remove.md
> +{% include rate_limits.md endpoint='default' %}
Yeah looks like it's 1k/min
![2022-06-13_13-48-15](https://user-images.githubusercontent.com/82903296/173442690-31ad1818-3386-4b74-9137-7a7fff367c5a.png)

2022-06-13 20:49 UTC, bre-fitzgerald requested changes
Thanks for making these edits! See my comment on the rate limit addition 👇

2022-06-14 15:17 UTC, bre-fitzgerald approved these changes
lgtm! thanks for making these edits!!

2022-06-14 15:17 UTC, merged