Personalized variants EA
braze-inc/braze-docs pull request #3991
Opened 2022-08-29 22:47 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [x] Yes (**Insert Feature Release Date Here**)
- [ ] No

-

2022-08-30 20:53 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing.md
> +This page explains what multivariate and A/B testing are and their benefits. For steps on how to create a multivariate or A/B test, refer to [Creating multivariate and A/B tests with Braze]({{site.ba
```suggestion
> This page explains what multivariate and A/B testing are and their benefits. For steps on how to create a multivariate or A/B test, refer to [Creating multivariate and A/B tests with Braze]({{site.baseurl}}/user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign/). 

Multivariate and A/B testing can be quickly utilized using [Intelligent Selection]({{site.baseurl}}/user_guide/intelligence/intelligent_selection/).
```

2022-08-31 19:03 UTC, borisrev commented
Bre FTW

2022-09-01 15:18 UTC, borisrev commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +## How variants are tested
This section "How variants are tested" only actually applies to "Winning Variant." It might make sense to bump that up into that section (and clarify it only applies in the Winning Variant case).

2022-09-01 16:27 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +If you selected **Winning Variant** for your optimization when setting up your campaign, you have access to an additional tab of your campaign analytics called **A/B Test Result**. You can access thi
@borisrev I want to confirm if this is correct (for both winning + personalized variant):
> You can access this tab after the winning variant is sent to the remaining users in your test.

2022-09-01 21:28 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +## How variants are tested
Moved that section up and added a similar heading to the technical details you added earlier 👍

2022-09-06 15:59 UTC, bre-fitzgerald commented
@lydia-xie @KellieHawks please review when you have a moment, but don't merge yet! Waiting for final confirmation 🙇‍♀️

2022-09-06 15:59 UTC, borisrev commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +If you selected **Winning Variant** for your optimization when setting up your campaign, you have access to an additional tab of your campaign analytics called **A/B Test Result**. You can access thi
correct yes

2022-09-06 16:04 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +If you selected **Winning Variant** for your optimization when setting up your campaign, you have access to an additional tab of your campaign analytics called **A/B Test Result**. You can access thi
```suggestion
If you selected **Winning Variant** for your optimization when setting up your campaign, you have access to an additional tab of your campaign analytics called **A/B Test Result**. After the winning variant is sent to the remaining users in your test, this tab shows the results of that send.
```

2022-09-06 16:04 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +If you selected **Personalized Variant** for your optimization when setting up your campaign, you have access to an additional tab of your campaign analytics called **A/B Test Result**. This tab is a
```suggestion
If you selected **Personalized Variant** for your optimization when setting up your campaign, you have access to an additional tab of your campaign analytics called **A/B Test Result**. After personalized variants are sent to the remaining users in your test, this tab shows the results of that send.
```

2022-09-06 17:47 UTC, lydia-xie requested changes
looks great! 👍 left some suggestions and comments for your review!

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
> +You can create a [Multivariate or A/B test]({{site.baseurl}}/user_guide/engagement_tools/testing/multivariant_testing/) for any campaign that targets a single channel.
```suggestion
You can create a [multivariate or A/B test]({{site.baseurl}}/user_guide/engagement_tools/testing/multivariant_testing/) for any campaign that targets a single channel.
```

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
> +You can create up to 8 variants of your message, differentiating between titles, content, images, and more. The number of differences between the messages determines whether this is a multivariate or
```suggestion
You can create up to 8 variants of your message, differentiating between titles, content, images, and more. The number of differences between the messages determines whether this is a multivariate or A/B test. An A/B test examines the effect of changing one variable, whereas a multivariate test examines two or more.
```

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
> +For push, email, and webhook campaigns scheduled to send once, you can also use an [optimization](#optimizations). This will reserve a portion of your target audience from the A/B test and hold them
```suggestion
For push, email, and webhook campaigns scheduled to send once, you can also use an [optimization](#optimizations). This will reserve a portion of your target audience from the A/B test and hold them for a second optimized send based on the results from the first test.
```

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
> +For email, push, and webhook campaigns scheduled to send once, you can select an optimization. There are two optimization options: **Winning Variant** and **Personalized Variant** (early access).
```suggestion
For email, push, and webhook campaigns scheduled to send once, you can select an optimization. There are two optimization options: **Winning Variant** and **Personalized Variant**.
```
Since we have the alert below, I think we can remove the (early access) here

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
> +| Initial test start date | The date and time the initial test starts.
```suggestion
| Initial test start date | The date and time the initial test starts. |
```
I think you're missing a `|` here, but on the deploy the table shows up fine 🤔

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
> +{% tab Personalized Variant (early access) %}
```suggestion
{% tab Personalized Variant %}
```
Suggesting to remove the (early access) here since we have an alert for that

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
> +| Initial test start date | The date and time the initial test starts.
```suggestion
| Initial test start date | The date and time the initial test starts. |
```

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +To do this, create another test with the same messaging channel and variants, but choose a different segment of users.  For instance, if one type of messaging was extremely effective for engaged user
```suggestion
To do this, create another test with the same messaging channel and variants, but choose a different segment of users. For instance, if one type of messaging was extremely effective for engaged users, it may be useful to investigate its effect on lapsed users. It’s possible that the lapsed users will respond similarly, or they may prefer another one of the other variants. This test will help you learn more about your different segments and how they respond to different types of messages. Why make assumptions about your segments when you can base your strategy on data?
```

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +If you find that a particular strategy is very effective in one channel, you may want to test that strategy in other channels.  If one type of message is effective in one channel but not effective in
```suggestion
If you find that a particular strategy is very effective in one channel, you may want to test that strategy in other channels. If one type of message is effective in one channel but not effective in another, you may be able to conclude that certain channels are more conducive to certain types of messages. Or, perhaps there is a difference between users who are more likely to enable push notifications and those who are more likely to pay attention to in-app messages. Ultimately, running this sort of test will help you learn about how your audience interacts with your different communication channels.
```

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +Was your sample size too small? Were the differences between your variants too subtle? Each test provides an opportunity to learn how to improve future tests. If your confidence is low, your sample s
```suggestion
Was your sample size too small? Were the differences between your variants too subtle? Each test provides an opportunity to learn how to improve future tests. If your confidence is low, your sample size is too small and should be enlarged for future tests. If you find no clear difference between how your variants performed, it’s possible that the differences were too subtle to have a discernible effect on users' responses.
```

2022-09-06 17:47 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/multivariate_analytics.md
> +- While testing is useful for discovering which type of messaging generates the most response from your audience, it’s also important to understand which alterations in messaging have only a negligib
```suggestion
- While testing is useful for discovering which type of messaging generates the most response from your audience, it’s also important to understand which alterations in messaging have only a negligible effect. This allows you to either continue testing for another more effective alternative, or save the time that may have been spent deciding between two alternate messages.
```

2022-09-06 17:49 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
> +For email, push, and webhook campaigns scheduled to send once, you can select an optimization. There are two optimization options: **Winning Variant** and **Personalized Variant** (early access).
I think I'd prefer to keep it, just because some people tend to gloss over it. So the more areas we mention it in, the better the safety net that people will notice it.

2022-09-06 17:51 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign.md
> +{% tab Personalized Variant (early access) %}
Same comment as above, I just want to make it abundantly clear at the outset that it's in early access, instead of hiding it within the tab. I could this being a point of frustration. 🤔

2022-09-06 17:57 UTC, KellieHawks approved these changes
Looks great!

2022-09-06 18:01 UTC, lydia-xie approved these changes

2022-09-06 18:01 UTC, merged