BD-1567: Updates to Drag & Drop Editor docs
braze-inc/braze-docs pull request #4034
Opened 2022-09-07 18:08 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> New type of DND Content Block **Video**, supported background image for row configurations, fallback fonts, dynamic image URL.

Closes #**BD-1567**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

2022-09-07 18:26 UTC, willng-braze commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +For further personalization, you can add Liquid to your image URLs. For example, instead of a static image, you can insert {% raw %} `https://example.com/images/?imageBanner={{first_name}}` {% endraw
I think users expect that this is the default functionality.  Beefree editor forces us to use "dynamic" images if we want to add liquid.  So maybe it's worth calling out that the user has to choose "dynamic images" if they want liquid rather than having the option of using liquid.

Though softer language is probably better for the customer.

2022-09-07 18:26 UTC, willng-braze submitted a review, later dismissed

2022-09-08 00:59 UTC, colleenwoodford requested changes

2022-09-08 00:59 UTC, colleenwoodford commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_email_style_settings.md
>  Fallback fonts are currently in early access. Contact your Braze account manager if you're interested in participating in the early access.
Fallback fonts have been globally released as of Sept 1 - so we can remove this message!

2022-09-08 00:59 UTC, colleenwoodford commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/overview.md
> +For further personalization, you can add Liquid to your image URLs. For example, instead of a static image, you can insert {% raw %} `https://example.com/images/?imageBanner={{first_name}}` {% endraw
Chiming in that I'm in alignment here as well

2022-09-08 16:02 UTC, KellieHawks approved these changes
Looks great!

2022-09-08 16:02 UTC, merged