BD-1600: Content Blocks for Drag & Drop Editor GA
braze-inc/braze-docs pull request #4080
Opened 2022-09-16 23:06 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2022-09-19 18:30 UTC, colleenwoodford commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
> +First, go to the the **Rows** tab the editor and select **Content Blocks**. Locate your Content Block, and drag and drop the Content Block into the email editor.
Do you think it complicates things to say something like - "Once added into the email editor, you can make changes to the content block that will not affect the parent content block you created in the Templates & Media section." ?

I'm thinking about making the behavior difference between adding via dragging (can edit, can preview, as soon as dragged into the email no longer connected to the template/media parent block) versus Liquid (can't edit or preview, always tied to the parent block in templates/media) as clear as possible

2022-09-20 22:23 UTC, lydia-xie commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
> +First, go to the the **Rows** tab the editor and select **Content Blocks**. Locate your Content Block, and drag and drop the Content Block into the email editor.
Added 2 callouts to clarify!

2022-09-21 16:10 UTC, colleenwoodford approved these changes

2022-09-26 18:48 UTC, KellieHawks commented on _docs/_user_guide/message_building_by_channel/email/drag_and_drop/dnd_content_blocks.md
> +First, go to the the **Rows** tab the editor and select **Content Blocks**. Locate your Content Block, and drag and drop the Content Block into the email editor. \
```suggestion
First, go to the the **Rows** tab the editor and select **Content Blocks**. Locate your Content Block, and drag and drop the Content Block into the email editor.
```

2022-09-26 18:49 UTC, KellieHawks requested changes
Looks great! One quick edit needed

2022-09-26 18:56 UTC, KellieHawks approved these changes

2022-09-26 18:56 UTC, merged