Updates to docs from CSM solutions repository
braze-inc/braze-docs pull request #4201
Opened 2022-10-07 20:07 UTC by KellieHawks

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Data Infrastructure<br>Platform Infrastructure<br>Quality Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Internal Tools<br>Product Partnerships<br>SDKs<br>SMS</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Channels<br>FIX<br>Intelligence<br>Reporting<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Email (Composition and Infrastructure)<br>Ingestion<br>Messaging</td>
  </tr>
</table>
</details>

2022-10-19 21:06 UTC, KellieHawks commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> +### Track how many times a custom event occured over the past month {#track}
```suggestion
### Track how many times a custom event occurred over the past month {#track}
```

2022-10-20 21:11 UTC, bre-fitzgerald requested changes
Looks really good! Left a few minor comments for some grammar fixes and clarifications.

2022-10-20 21:11 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/braze_currents.md
> +guide_top_text: "Understanding the impact of your engagement strategy is critical in informing your iteration and optimization of your communications with your users. To ensure that this valuable eng
```suggestion
guide_top_text: "Understanding the impact of your engagement strategy is critical in informing your iteration and optimization of your communications with your users. To ensure that this valuable engagement data is tightly integrated with the rest of your operations and help amplify your investment in data science, the Braze platform tracks a wide array of event data from your integration for analysis, retargeting, and other use cases elsewhere within your own systems. <br> <br>The Currents tool is a real-time data stream of your engagement events that is the most robust, yet granular export out of the Braze platform. It provides you data in an Avro file type to one of our many <a href='https://www.braze.com/docs/user_guide/data_and_analytics/braze_currents/available_partners/'>data partners</a>, empowering you to use the unique and valuable data Braze creates to power your BI and analytics efforts in other best-in-class platforms."
```

2022-10-20 21:11 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
> +- Trigger a campaign or Canvas using [action-based delivery]({{site.baseurl}}/user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/) based on a custom event.
```suggestion
- Trigger a campaign or Canvas based on a custom event using [action-based delivery]({{site.baseurl}}/user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/).
```

2022-10-20 21:11 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
> +- Find additional analytics using [funnel]({{site.baseurl}}/user_guide/data_and_analytics/your_reports/funnel_reports/#step-2-select-events-for-funnel-steps) and [retention]({{site.baseurl}}/user_gui
Minor callout, if one of your bullets has a period, they should all have a period

```suggestion
- Find additional analytics using [funnel]({{site.baseurl}}/user_guide/data_and_analytics/your_reports/funnel_reports/#step-2-select-events-for-funnel-steps) and [retention]({{site.baseurl}}/user_guide/data_and_analytics/your_reports/retention_reports/) reports.
```

2022-10-20 21:11 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
> +- Generate more sophisticated analytics with [Currents]({{site.baseurl}}/user_guide/data_and_analytics/braze_currents)
```suggestion
- Generate more sophisticated analytics with [Currents]({{site.baseurl}}/user_guide/data_and_analytics/braze_currents).
```

2022-10-20 21:11 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/custom_data/custom_events.md
> +- Set up Canvas [exception events]({{site.baseurl}}/user_guide/engagement_tools/canvas/create_a_canvas/exception_events#canvas-exception-events) to define when users should not advance to the next st
```suggestion
- Set up Canvas [exception events]({{site.baseurl}}/user_guide/engagement_tools/canvas/create_a_canvas/exception_events#canvas-exception-events) to define when users should not advance to the next step of your Canvas.
```

2022-10-20 21:11 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
> +- **Client checks internally (recommended)**<br>If you have an external record or database containing the provided user information that exists outside of Braze, reference this at the time of email s
"Client checks internally" is this calling the user a client? Or is this referring to client-side data? If it's the former, I'd suggest rewording these two bullets to something along the lines of

- Check internal database
- Use /users/export/id endpoint

If it's the latter, might want to clarify the first bullet point 🤔

2022-10-20 21:11 UTC, bre-fitzgerald commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> +Spanich image URL
```suggestion
Spanish image URL
```

2022-10-20 21:11 UTC, bre-fitzgerald commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> +Russian iamge URL
```suggestion
Russian image URL
```

2022-10-20 21:11 UTC, bre-fitzgerald commented on _docs/_user_guide/personalization_and_dynamic_content/liquid/liquid_use_cases.md
> +This use case will display an image based on a user's language. Note that this use case has only been tested with images uploaded to Braze.
Might be good to add more detail here, but feel free to discard 🤔 
```suggestion
This use case will display an image based on a user's language. Note that this use case has only been tested with images uploaded to the Braze Media Library.
```

2022-10-20 21:26 UTC, lydia-xie requested changes
looks great! left two small suggestions

2022-10-20 21:26 UTC, lydia-xie commented on _docs/_user_guide/data_and_analytics/braze_currents.md
> +A Currents connector is already included in many of our pro and enterprise-level packages. If you’re interested using Currents, reach out to your account manager. Your account manager and our data sp
```suggestion
A Currents connector is already included in many of our pro and enterprise-level packages. If you’re interested using Currents, reach out to your account manager. Your account manager and our data specialists can assist in your [Currents setup and integration]({{site.baseurl}}/user_guide/data_and_analytics/braze_currents/setting_up_currents/).
```

2022-10-20 21:26 UTC, lydia-xie commented on _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
> +If you would like to remove custom attributes from user profiles, set the value to "null" in your API request to the [/users/track]({{site.baseurl}}/api/endpoints/user_data/post_user_track#user-track
```suggestion
If you would like to remove custom attributes from user profiles, set the value to "null" in your API request to the [`/users/track`]({{site.baseurl}}/api/endpoints/user_data/post_user_track#user-track) endpoint.
```

2022-10-21 14:37 UTC, KellieHawks commented on _docs/_user_guide/data_and_analytics/user_data_collection/best_practices.md
> +- **Client checks internally (recommended)**<br>If you have an external record or database containing the provided user information that exists outside of Braze, reference this at the time of email s
```suggestion
- **Checks internal database (recommended)**<br>If you have an external record or database containing the provided user information that exists outside of Braze, reference this at the time of email submission or account creation to ensure the information has not already been captured.<br><br>
```

2022-10-21 14:56 UTC, lydia-xie approved these changes

2022-10-21 15:08 UTC, bre-fitzgerald approved these changes

2022-10-21 15:08 UTC, merged