ff
braze-inc/braze-docs pull request #4319
Opened 2022-10-27 20:22 UTC by davidbielik

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +Feature flags allow you to remotely enable or disable functionality for a specific section of your user base. Importantly, they let you turn a feature on and off in production without additional code
```suggestion
Feature flags allow you to remotely enable or disable functionality for a specific or random selection of users. Importantly, they let you turn a feature on and off in production without additional code deployment or app store updates. This allows you to safely roll out new features with confidence. 
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +Manage, create, and delete feature flags by navigating to **Feature Flags** in the left sidebar of the Braze dashboard. This page displays a list of existing feature flags for this app group.
```suggestion
Create, edit, and archive feature flags by navigating to **Feature Flags** in the left sidebar of the Braze dashboard. This page displays a list of existing feature flags for this app group.
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +A feature flag `ID` is unique. The same `ID` is used across app groups so that different platforms (i.e., iOS/Android/Web) can share references to the same feature. Once set, the feature flag `ID` sh
```suggestion
Feature flags are shared across apps within an app group so that different platforms (i.e., iOS/Android/Web) can share references to the same feature.
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +To target a particular [segment]({{site.baseurl}}/user_guide/engagement_tools/segments/) of users for your feature rollout, use the **Add Segment** dropdown menu.
```suggestion
To being the rollout of a feature flag, you must choose a particular [segment]({{site.baseurl}}/user_guide/engagement_tools/segments/) of users.
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +If no segment is selected, the percentage of targeted users (see [Rollout Traffic](#rollout-traffic), below) will come from your entire user base. You can add multiple segments to target.
```suggestion
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +To filter users out of your target audience, use the **Add Filter** dropdown menu. You can add multiple filters to narrow your audience.
Not sure if this is needed since the segment/filter component is the same one used elsewhere in the product.

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +Feature flags always start as disabled to allow you to separate the timing of the feature's release and activation in your users' experience. When you are ready to rollout your new feature, use the *
```suggestion
Feature flags always start as disabled to allow you to separate the timing of the feature's release and activation in your users' experience. 

When you are ready to rollout your new feature, specify an audience and then use the **Rollout Traffic** slider to define the random percentage of your targeted user base to receive the new feature. Set the **Rollout Traffic** slider to set a percentage between 0% (no users) and 100% (the entire target audience). 
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +Do not set your rollout traffic above 0% until you are ready for your new feature to go live. When you initially define your feature flag in the dashboard, leave this setting at 0%.
good callout!

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +Let's say you were to rolling out a new type of user profile for your app. You might set the `ID` as `expanded_user_profile`. Then, you would have your app check to see if it should display this new
maybe we can change `expanded_user_profile` to the `show_out_of_stock_banner`?

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +The Braze SDK uses getter methods to pull your feature flag's properties into your app. It refreshes these properties during app start so that it displays the most up-to-date version of your feature
```suggestion
The Braze SDK provides getter methods to pull your feature flag's enabled/disabled status and its properties into your app. Feature flags are refreshed automatically at session start so that you can display the most up-to-date version of your feature upon launch. The SDK caches these values so they can be used while offline. 
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +Refreshing happens automatically upon session start, and may be throttled by Braze. Please ensure you refresh only prior to important user actions or pages, such as before loading a checkout page, or
```suggestion
Refreshing happens automatically upon session start. Manually refreshing may be throttled by Braze. Please ensure you refresh only prior to important user actions or pages, such as before loading a checkout page, or if you know a feature flag will be consumed.
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +You can configure the SDK to listen and update your app if a refresh changes a feature flag's value.
```suggestion
You can configure the Braze SDK to listen and update your app when feature flags have been refreshed.
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +This is useful if you want to update your app behind the scenes if feature flags are refreshed mid-session. For example, setting some state in your app based on whether or not a feature is enabled, o
```suggestion
This is useful if you want to update your app if a user is no longer eligible for a feature. For example, setting some state in your app based on whether or not a feature is enabled, or one of its property values.
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +Use feature flags to coordinate feature rollout and messaging simultaneously. This will allow you to use Braze as the source of truth for both your user experience and its relevant messaging. To achi
```suggestion
(Coming Soon in Canvas)

Use feature flags to coordinate feature rollout and messaging simultaneously. This will allow you to use Braze as the source of truth for both your user experience and its relevant messaging. To achieve this, target the new feature to a particular segment or filtered portion of your audience. Then, create a Campaign or Canvas that only targets that segment. 
```

2022-11-16 15:42 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags.md
> +### Feature experimentation
```suggestion
### Feature experimentation
(Coming Soon in Canvas)

```

2022-12-16 21:15 UTC, josh-mccrowell-braze commented
@bre-fitzgerald : Leaving this piece of coal for your stocking for after your holiday. We're still waiting on some last-touch items (so still not ready to merge), but thought I could incorporate your peer review into the content while we were waiting.

Particularly interested in your perspective on how the screenshots are sitting on the page.

Thanks!

2022-12-16 22:24 UTC, davidbielik commented on _docs/_hidden/private_betas/feature_flags.md
> +![A list of previously created feature flags on the Braze dashboard][1]
todo (for me) to add a screenshot with better fake data

2022-12-27 19:57 UTC, bre-fitzgerald requested changes
Looks great! Left some suggestions for your review @josh-mccrowell-braze 🙏

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +![A list of previously created feature flags on the Braze dashboard][1]
Might want to crop the bottom half of this image off since it makes it pretty tall (and doesn't add new info)

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +![A blank feature flag form][2]
I'd suggest chunking this screenshot and just including an image of the details in the details section, image of properties in the properties section, etc.

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +Create, edit, and archive feature flags by navigating to **Feature Flags** in the left sidebar of the Braze dashboard. This page displays a list of existing feature flags for this app group.
When possible, we generally avoid using directional language to refer to where something is on the page. If we localize to a right-to-left language, that might change, and it also just makes it easier to keep up with updates if things move around on the UI. Adding a suggested rewrite but feel free to adjust!

```suggestion
Create, edit, and archive feature flags from the **Feature Flags** page, located under **Engagement**. This page displays a list of existing feature flags for this app group.
```

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +Create, edit, and archive feature flags by navigating to **Feature Flags** in the left sidebar of the Braze dashboard. This page displays a list of existing feature flags for this app group.
When possible, we generally avoid using directional language to refer to where something is on the page. If we localize to a right-to-left language, that might change, and it also just makes it easier to keep up with updates if things move around on the UI. Adding a suggested rewrite but feel free to adjust!

```suggestion
Create, edit, and archive feature flags from the **Feature Flags** page, located under **Engagement**. This page displays a list of existing feature flags for this app group.
```

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +To create a new feature flag, click the **Create Feature Flag** button. Then, define your feature flag's [details](#details), [properties](#properties), user [targeting](#targeting), and [rollout tra
Just the button name is fine! Generally, avoid calling out what a specific UI element is unless it's needed for clarity.

```suggestion
To create a new feature flag, click **Create Feature Flag**. Then, define your feature flag's [details](#details), [properties](#properties), user [targeting](#targeting), and [rollout traffic](#rollout-traffic).
```

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +* The **ID** field will be referenced in your code to determine whether the feature is enabled for a particular user.
Might be good to just pop this inline here as well.

```suggestion
* The **ID** field will be referenced in your code to determine whether the feature is enabled for a particular user. This must be unique and cannot be modified once created.
```

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +##### Example
Minor suggestion, feel free to reject. It took me a second to realize this was nested 😆 

```suggestion
##### Example properties
```

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +|:Property Name|Type|Value|
```suggestion
|Property Name|Type|Value|
```

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +To being the rollout of a feature flag, you must choose a particular [segment]({{site.baseurl}}/user_guide/engagement_tools/segments/) of users.
Typo?
```suggestion
To begin the rollout of a feature flag, you must choose a particular [segment]({{site.baseurl}}/user_guide/engagement_tools/segments/) of users.
```

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +Feature flags always start as disabled to allow you to separate the timing of the feature's release and activation in your users' experience.
```suggestion
Feature flags always start as turned off to allow you to separate the timing of the feature's release and activation in your users' experience. 
```

2022-12-27 19:57 UTC, bre-fitzgerald commented on _docs/_hidden/private_betas/feature_flags.md
> +The Braze SDK provides getter methods to pull your feature flag's enabled/disabled status and its properties into your app. Feature flags are refreshed automatically at session start so that you can
1. Using slashes to combine words isn't recommended
2. I think we can just omit that entirely in this case, since status covers the "enabled/disabled" portion.

```suggestion
The Braze SDK provides getter methods to pull your feature flag's status and its properties into your app. Feature flags are refreshed automatically at session start so that you can display the most up-to-date version of your feature upon launch. The SDK caches these values so they can be used while offline. 
```

2023-01-05 15:34 UTC, davidbielik commented on _docs/_hidden/private_betas/feature_flags.md
> +
TODO: add FAQ section stating that liquid is supported, but Connected Content is not.

2023-01-05 19:13 UTC, josh-mccrowell-braze commented
@davidbielik , @bre-fitzgerald 
On a suggestion from my team, I've split the feature flag articles into two. "About feature flags" is aimed more at a marketing user to help them understand what feature flags are and why they would use them. "Creating feature flags" is aimed at developers who execute the implementation.

It might be worth a re-review of the content in this format. As always, eager for any notes or feedback.

2023-01-06 15:07 UTC, davidbielik commented on _docs/_hidden/private_betas/about_feature_flags.md
> +permalink: "/about_feature_flags/"
@josh-mccrowell-braze what's the full URL for this? I think it might make sense to instead make it `/feature_flags/overview` and `/feature_flags/integration` or something like that nested inside a `feature_flags` directory?

2023-01-06 15:08 UTC, davidbielik commented on _docs/_hidden/private_betas/about_feature_flags.md
> +Create a new feature flag within the Braze dashboard by providing a name and an `ID`, a target audience, and a percentage of users for whom to enable to this feature. Then, using that same `ID` in yo
This paragraph seems more fitting in the creation article

2023-01-06 15:09 UTC, davidbielik commented on _docs/_hidden/private_betas/about_feature_flags.md
> +This functionality is not supported in beta.
```suggestion
This functionality is not yet supported in beta.
```

2023-01-06 15:12 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +  console.log(`Failed to refresh feature flags.);
```suggestion
  console.log(`Failed to refresh feature flags.`);
```

2023-01-06 15:21 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +
### Accessing Properties

To access the properties of a feature flag you can use one of the following methods depending on the type you defined in the dashboard.

{% tabs %}
{% tab Javascript %}
```javascript
```
{% endtab %}
{% tab Swift %}
```swift
```
{% endtab %}
{% tab Java %}
```java
```
{% endtab %}
{% tab Kotlin %}
```kotlin
```
{% endtab %}
{% endtabs %}

2023-01-06 15:21 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +
```suggestion

### Accessing Properties

To access the properties of a feature flag you can use one of the following methods depending on the type you defined in the dashboard.

{% tabs %}
{% tab Javascript %}
```javascript
```
{% endtab %}
{% tab Swift %}
```swift
```
{% endtab %}
{% tab Java %}
```java
```
{% endtab %}
{% tab Kotlin %}
```kotlin
```
{% endtab %}
{% endtabs %}
```

2023-01-06 15:33 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +```java
@bryanlogan can you add code samples for java and kotlin matching the javascript above?

2023-01-06 15:35 UTC, bryanlogan commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +```java
I'm on it

2023-01-06 15:40 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +![Two dropdown menus. The first reads Target Users by Segment. The second reads Additional Filters.][3]
@josh-mccrowell-braze this is the wrong image

2023-01-06 15:41 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +![A slider labeled Rollout Traffic, spanning between 0 and 100.][4]
@josh-mccrowell-braze this is the wrong image

2023-01-06 15:42 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +[3]: {% image_buster /assets/img_archive/Feature-Flag-2.png %}
```suggestion
[3]: {% image_buster /assets/img_archive/Feature-Flag-3.png %}
```

2023-01-06 15:42 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +[4]: {% image_buster /assets/img_archive/Feature-Flag-2.png %}
```suggestion
[4]: {% image_buster /assets/img_archive/Feature-Flag-4.png %}
```

2023-01-06 15:48 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +### Accessing Properties
```suggestion
### Accessing Properties {#properties}
```

2023-01-06 15:48 UTC, davidbielik commented on _docs/_hidden/private_betas/creating_feature_flags.md
> +### Listen for changes
```suggestion
### Listen for changes {#updates}
```

2023-01-06 21:24 UTC, josh-mccrowell-braze commented on _docs/_hidden/private_betas/about_feature_flags.md
> +permalink: "/about_feature_flags/"
Happy to have suggestions about where to put it. Right *now*, I think the URL will need to remain as-is because the docs are hidden from the sidebar and will only be findable through direct links. 

In the future, we could nest them under a collapsible section. But I think one of the goals was to separate the marketer content from the developer content, in which case "About feature flags" might be in the User Guide whereas "Creating feature flags" might be in the Developer Guide. 

Do you have a strong preference towards keeping them together in a nested section or splitting them up?

2023-01-06 21:39 UTC, josh-mccrowell-braze commented on _docs/_hidden/private_betas/about_feature_flags.md
> +Create a new feature flag within the Braze dashboard by providing a name and an `ID`, a target audience, and a percentage of users for whom to enable to this feature. Then, using that same `ID` in yo
Fixed in latest push

2023-01-06 21:39 UTC, josh-mccrowell-braze commented on _docs/_hidden/private_betas/about_feature_flags.md
> +### Gradual rollouts
Image added!

2023-01-06 22:16 UTC, davidbielik commented on _docs/_hidden/private_betas/about_feature_flags.md
> +permalink: "/about_feature_flags/"
I see... i'd prefer to have the docs in the ultimate place they'll be located to avoid having to redirect and nesting within a `feature_flags` folder would look similar to what we do with other products/hierarchies.

2023-01-07 00:42 UTC, davidbielik commented
@josh-mccrowell-braze do you know why the preview link 404 errors?

2023-01-09 21:03 UTC, josh-mccrowell-braze commented on _docs/_hidden/private_betas/about_feature_flags.md
> +permalink: "/about_feature_flags/"
Happy to nest in a sidebar on the Developer Guide. 

I think the Docs team procedure is to have beta docs sit in the hidden folder until such time as they are GA. Let me know if you want to talk about that for this instance.

2023-01-13 15:38 UTC, davidbielik commented on _docs/_hidden/private_betas/about_feature_flags.md
> +permalink: "/about_feature_flags/"
Thanks @josh-mccrowell-braze yes i'd prefer to have this sit in its final location to limit changes/redirects needed in the future and to match the url structure elsewhere

2023-01-18 17:58 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags/about_feature_flags.md
> +{% sdk_min_versions android:9999 web:4.4.0 swift:9999 %}
```suggestion
{% sdk_min_versions android:9999 web:4.6.0 swift:9999 %}
```

2023-01-18 17:59 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags/creating_feature_flags.md
> +{% sdk_min_versions android:9999 web:4.4.0 swift:9999 %}
```suggestion
{% sdk_min_versions android:9999 web:4.6.0 swift:9999 %}
```

2023-01-25 21:48 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +Refreshing happens automatically upon session start. We encourage sensible limits when making refresh calls to prevent undue resource consumption. Please ensure you refresh only prior to important us
i'd prefer to either tell them we may rate limit refreshes, or just remove the second sentence

2023-01-25 21:56 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +  Log.i(TAG, "expanded_user_profile is enabled. ${featureFlag.properties}")
```suggestion
  Log.i(TAG, "expanded_user_profile is enabled.")
```

2023-01-25 21:57 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +  Log.i(TAG, "expanded_user_profile is enabled", featureFlag.getProperties());
```suggestion
  Log.i(TAG, "expanded_user_profile is enabled");
```

2023-01-25 21:57 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +    Log.i(TAG, "Feature: ", feature.getId(), feature.getEnabled(), feature.getProperties());
```suggestion
    Log.i(TAG, "Feature: ", feature.getId(), feature.getEnabled());
```

2023-01-25 22:03 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +Refreshing happens automatically upon session start. We encourage sensible limits when making refresh calls to prevent undue resource consumption. Please ensure you refresh only prior to important us
Done!

2023-01-25 22:17 UTC, bre-fitzgerald requested changes
Looks great! Only have one minor comment 🙌

2023-01-25 22:17 UTC, bre-fitzgerald commented on _docs/_developer_guide/platform_wide/feature_flags/about.md
> +> To learn how you would implement these example use cases, see the [feature flag use cases][2] article.
> To learn how you would implement these example use cases...

@josh-mccrowell-braze I'd suggest moving this line up to the top "Use cases" header instead of having a block quote down here. 

> ## Use cases
> Feature flags have a few different strategic uses, outlined below. To learn how you would implement these example use cases, see the [feature flag use cases][2] article.

2023-01-25 22:28 UTC, jocelynzz commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let featureFlag = braze.featureFlags.featureFlag(id: "expanded_user_profile")
I think it would more clear if we add the type explicitly:
ie `let featureFlag: FeatureFlag`

2023-01-25 22:29 UTC, jocelynzz commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let numberProperty = featureFlag.numberProperty(key: "height")
`let numberProperty: NSNumber?`

2023-01-25 22:32 UTC, jocelynzz commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let booleanProperty = featureFlag.boolProperty(key: "expanded")
`let booleanProperty: Bool? = eatureFlag.boolProperty(key: "expanded")?.boolValue`

2023-01-25 22:33 UTC, jocelynzz commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let stringProperty = featureFlag.stringProperty(key: "color")
`let stringProperty: String?`

2023-01-25 22:33 UTC, jocelynzz commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let featureFlag = braze.featureFlags.featureFlag(id: "expanded_user_profile")
cc @lowip for sanity

2023-01-26 15:43 UTC, lowip commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let numberProperty = featureFlag.numberProperty(key: "height")
`featureFlag.numberProperty(key: "height")` returns an `NSNumber` only in ObjC as we can't return an optional `Double` in that language.
In Swift, it returns an optional `Double`

2023-01-26 15:43 UTC, lowip commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let booleanProperty = featureFlag.boolProperty(key: "expanded")
```suggestion
let booleanProperty: Bool? = featureFlag.boolProperty(key: "expanded")
```
Just kept the type information to clearly show that it's an optional.

`eatureFlag.boolProperty(key: "expanded")` returns a `Bool?` directly in Swift. It returns a nullable `NSNumber` in ObjC

2023-01-26 15:43 UTC, lowip commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let stringProperty = featureFlag.stringProperty(key: "color")
```suggestion
let stringProperty: String? = featureFlag.stringProperty(key: "color")
```

2023-01-26 15:43 UTC, lowip commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let featureFlag = braze.featureFlags.featureFlag(id: "expanded_user_profile")
```suggestion
let featureFlag: FeatureFlag = braze.featureFlags.featureFlag(id: "expanded_user_profile")
```
I think it's good to have the type here just to show that it's not an optional value.

2023-01-26 16:43 UTC, lowip commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let numberProperty = featureFlag.numberProperty(key: "height")
```suggestion
let numberProperty: Double? = featureFlag.numberProperty(key: "height")
```

2023-01-26 16:53 UTC, davidbielik commented
@josh-mccrowell-braze ready for your review/merge :)

2023-01-26 17:09 UTC, jocelynzz commented on _docs/_developer_guide/platform_wide/feature_flags/create.md
> +let numberProperty = featureFlag.numberProperty(key: "height")
yeah, good catch. I was looking at the FF+ObjectiveC file for some reason..

2023-01-26 17:58 UTC, bre-fitzgerald approved these changes

2023-01-26 17:58 UTC, merged