Style Guide fixes, typos, and fixed links
braze-inc/braze-docs pull request #4437
Opened 2022-11-18 19:32 UTC by josh-mccrowell-braze

2022-11-18 19:33 UTC, josh-mccrowell-braze commented
@davidbielik : Would you check out this PR from a technical point of view. I think SDK Authentication is probably the only edited article that needs your consideration. 

@lydia-xie : Would you please review for style purposes? 

Thank you both!

2022-11-18 19:33 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
>  import * as braze from"@braze/web-sdk";
```suggestion
import * as braze from "@braze/web-sdk";
```

2022-11-18 19:34 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
> +braze.subscribeToSdkAuthenticationFailures((someErrorEvent) => {
```suggestion
braze.subscribeToSdkAuthenticationFailures((errorEvent) => {
```

2022-11-18 19:34 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
> +  const updated_jwt = await getNewTokenSomehow(someErrorEvent);
```suggestion
  const updated_jwt = await getNewTokenSomehow(errorEvent);
```

2022-11-18 19:35 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
> +  // TODO: Check if the someErrorEvent user matches the currently logged-in user
```suggestion
  // TODO: Check if the user_id within the `errorEvent` matches the currently logged-in user
```

2022-11-18 19:35 UTC, davidbielik commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
> +braze.subscribeToSdkAuthenticationFailures((someErrorEvent) => {
these 3 suggestions should be applied to other code samples below.

2022-11-18 19:36 UTC, davidbielik submitted a review, later dismissed
left a few comments in SDK Auth

2022-11-18 22:55 UTC, lydia-xie requested changes
Looks great! Left a few suggestions for your review!

2022-11-18 22:55 UTC, lydia-xie commented on _docs/_developer_guide/platform_wide/analytics_overview.md
> +Numeric attributes have a wide variety of use cases. Incrementing number custom attributes are useful for storing the number of times a given action or event has occurred. Standard numbers have all s
```suggestion
Numeric attributes have a wide variety of use cases. Incrementing number custom attributes are useful for storing the number of times a given action or event has occurred. Standard numbers have all sorts of usages, such as recording shoe size, waist size, or the number of times a user has viewed a certain product feature or category.
```

2022-11-18 22:55 UTC, lydia-xie commented on _docs/_developer_guide/platform_wide/analytics_overview.md
> +Boolean attributes are useful for storing subscription statuses and other simple binary data about your users. The input options that we provide allow you to find users that have explicitly had a var
```suggestion
Boolean attributes are useful for storing subscription statuses and other simple binary data about your users. The input options that we provide allow you to find users that have explicitly had a variable set to a boolean in addition to those that don't have any record of that attribute recorded yet.
```

2022-11-18 22:55 UTC, lydia-xie commented on _docs/_developer_guide/platform_wide/analytics_overview.md
> +For this example case, let's consider a taxi/ride-sharing app (such as Hailo or Lyft) that wants to decide what user data to collect. The following questions and brainstorming process are a great mod
```suggestion
For this example, let's consider a ride-sharing app that wants to decide what user data to collect. The following questions and brainstorming process are a great model for marketing and development teams to follow. By the end of this exercise, both teams should have a solid understanding of what custom events and attributes make sense to collect in order to help meet their goal.
```

2022-11-18 22:55 UTC, lydia-xie commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
>  | `exp` | **Yes**  | The "expiration" of when you want this token to expire.                                |
```suggestion
| `sub` | Yes  | The "subject" should equal the User ID you supply Braze SDK when calling `changeUser`  |
| `exp` | Yes | The "expiration" of when you want this token to expire.                                |
```

2022-11-18 22:55 UTC, lydia-xie commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
> +Failed requests will periodically be retried until your app supplies a new valid JWT. If _that user_ is still logged in, you can use this callback as an opportunity to request a new JWT from your ser
```suggestion
Failed requests will periodically be retried until your app supplies a new valid JWT. If that user is still logged in, you can use this callback as an opportunity to request a new JWT from your server and supply Braze's SDK with this new valid token.
```

2022-11-18 22:55 UTC, lydia-xie commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
> +In the **Manage Settings** page of the dashboard, add your public key to a specific app in the Braze dashboard. Each app supports up to three public keys. Note that the same public/private keys may b
```suggestion
In the **Manage Settings** page of the dashboard, add your public key to a specific app in the Braze dashboard. Each app supports up to three public keys. Note that the same public and private keys may be used across apps.
```

2022-11-18 22:55 UTC, lydia-xie commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
> +Keep in mind, SDK requests will continue to flow as usual - without authentication - _unless_ the app's SDK Authentication setting is set to **Required** in the Braze dashboard.
```suggestion
Keep in mind that SDK requests will continue to flow as usual without authentication unless the app's SDK Authentication setting is set to **Required** in the Braze dashboard.
```

2022-11-18 22:55 UTC, lydia-xie commented on _docs/_developer_guide/platform_wide/sdk_authentication.md
> +Should anything go wrong with your integration (i.e., your app is incorrectly passing tokens to the SDK, or your server is generating invalid tokens), simply disable this feature in the Braze dashboa
```suggestion
Should anything go wrong with your integration (i.e., your app is incorrectly passing tokens to the SDK, or your server is generating invalid tokens), disable this feature in the Braze dashboard, and data will resume to flow as usual without verification.
```

2022-11-18 22:55 UTC, lydia-xie commented on _docs/_developer_guide/platform_wide/tv_and_ott.md
> +For platforms that support in-app messages or Content Cards via headless UI, Braze will deliver a data model (i.e., JSON) that your app can read and use within a UI your app controls. These platforms
```suggestion
For platforms that support in-app messages or Content Cards via headless UI, Braze will deliver a data model (i.e., JSON) that your app can read and use within a UI your app controls. These platforms don't include any out-of-the-box UI or views.
```
Not sure if "Views" should be capitalized here, but also I'm not sure what this is referring to... 🤔

2022-11-21 18:23 UTC, lydia-xie approved these changes
lgtm!

2022-11-21 18:23 UTC, merged