Edited Push Token Migration
braze-inc/braze-docs pull request #4469
Opened 2022-11-30 19:04 UTC by josh-mccrowell-braze

- Edited for tone and clarity
- Fixed broken links
- Reordered information for a better flow
- Changed "warnings" to "important" alerts for tonal considerations

2022-12-04 15:08 UTC, niccrowley submitted a review, later dismissed

2022-12-05 22:23 UTC, lydia-xie requested changes
looks great! added 1 minor suggestion for how we add "Last updated on XYZ" for the last line of help articles

2022-12-05 22:23 UTC, lydia-xie commented on _docs/_help/help_articles/push/push_token_migration.md
> +{% endalert %}
```suggestion
{% endalert %}

_Last updated on December 5, 2022_
```

2022-12-05 22:46 UTC, lydia-xie approved these changes

2022-12-05 22:46 UTC, merged