Building accessible messages
braze-inc/braze-docs pull request #4648
Opened 2023-01-13 22:01 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> Adds general article for accessibility guidelines for marketers

2023-01-13 22:05 UTC, bre-fitzgerald commented
@KellieHawks / @lydia-xie / @josh-mccrowell-braze looking for a general content review as well as wondering if this is the best place for this content. I was considering perhaps adding this to the "Message Building by Channel" content as it's own article, but I think that would require renaming the section to just "Message Building" 🤔 

For context, this article is intended to provide general guidelines, and then channel-specific guidelines will follow (still a WIP on my end).

2023-01-17 18:49 UTC, lydia-xie requested changes
looks great! left a few suggestions for your consideration 👍

2023-01-17 18:49 UTC, lydia-xie commented on _docs/_help/accessibility.md
> +- Keep your content on brand, but use plain language. Write to a United States 7th grade reading level. You can use resources such as [Hemingway App](https://hemingwayapp.com/) to check your text’s r
```suggestion
- Keep your content on brand, but use plain language. Write to a United States seventh-grade reading level. You can use resources such as [Hemingway App](https://hemingwayapp.com/) to check your text’s reading level.
```

2023-01-17 18:49 UTC, lydia-xie commented on _docs/_help/accessibility.md
> +Physical disabilities include weakness and limitations of muscle control or sensation, joint disorders, pain that impedes movement, and missing limbs.
```suggestion
Physical disabilities can include weakness and limitations of muscle control or sensation, joint disorders, pain that impedes movement, and missing limbs.
```

2023-01-17 18:51 UTC, bre-fitzgerald commented on _docs/_help/accessibility.md
> +- Keep your content on brand, but use plain language. Write to a United States 7th grade reading level. You can use resources such as [Hemingway App](https://hemingwayapp.com/) to check your text’s r
Hm good callout. This is a niche use since we don't really refer to grades, so it's not in the style guide, but I defaulted to [APA style](https://blog.apastyle.org/apastyle/2018/03/how-to-write-grade-numbers-in-apa-style.html) 🤔

2023-01-17 18:53 UTC, bre-fitzgerald commented on _docs/_help/accessibility.md
> +Similar to link text, write button text that clearly describes the action that will happen when a user presses it (e.g., “Read the full story” rather than “Read more”). Test to ensure your button tex
oop thanks, good catch!

2023-01-17 18:55 UTC, lydia-xie commented on _docs/_help/accessibility.md
> +- Keep your content on brand, but use plain language. Write to a United States 7th grade reading level. You can use resources such as [Hemingway App](https://hemingwayapp.com/) to check your text’s r
Yep, I also used the same reference 🤔

> When writing a grade in its ordinal form, use words for Grades 1–9 and numerals for Grades 10, 11, and 12.

2023-01-17 19:00 UTC, KellieHawks commented on _docs/_help/accessibility.md
> +- Mechanisms to skip over blocks of content, like page headers or navigation bars
```suggestion
- Mechanisms to skip over blocks of content, like page headers, or navigation bars
```

2023-01-17 19:07 UTC, KellieHawks commented on _docs/_help/accessibility.md
> +**Write clear error messages** <br>A good error message is made up of three parts: what’s happened, what went wrong, and how can they fix it. Error messaging should be clear and easy to understand. T
```suggestion
**Write clear error messages** <br>A good error message is made up of three parts: what’s happened, what went wrong, and how they can fix it. Error messaging should be clear and easy to understand. Try to speak in simple language. There’s no need for fancy jargon.
```

2023-01-17 19:15 UTC, KellieHawks submitted a review, later dismissed
Looks good, left a comment and slacked you some additional resources to look through

2023-01-17 19:30 UTC, bre-fitzgerald commented on _docs/_help/accessibility.md
> +{% endraw %}
@KellieHawks

2023-01-17 19:30 UTC, bre-fitzgerald commented on _docs/_help/accessibility.md
> +- Keep your content on brand, but use plain language. Write to a United States 7th grade reading level. You can use resources such as [Hemingway App](https://hemingwayapp.com/) to check your text’s r
That's for when "Grade" comes first though

2023-01-17 19:32 UTC, KellieHawks commented on _docs/_help/accessibility.md
> +{% endraw %}
Love it! Thanks for adding this!

2023-01-17 19:33 UTC, bre-fitzgerald commented on _docs/_help/accessibility.md
> +- Set the language attribute within your HTML to identify the language that your content is in. Screen readers use different sound libraries for each language based on the pronunciation and character
```suggestion
- Set the language attribute within your HTML to identify the language that your content is in. Screen readers use different sound libraries for each language based on the pronunciation and characteristics of that language. If the language is specified, screen readers can automatically switch between language libraries as needed. For example:
```

2023-01-17 19:39 UTC, lydia-xie submitted a review, later dismissed

2023-01-17 21:17 UTC, josh-mccrowell-braze approved these changes
Sorry, I had previously Approved this with these suggestions, but a push between the time I started and the time I finished invalidated my review!

2023-01-17 21:18 UTC, bre-fitzgerald commented on _docs/_help/accessibility.md
> +- **Minimize legal risk:** Many countries have laws requiring digital accessibility, and the issue is of increased legal concern.
Removing 👍

2023-01-17 21:20 UTC, bre-fitzgerald commented on _docs/_help/accessibility.md
> +**Chunk longer forms into smaller sections** <br>To reduce cognitive load, break long forms into smaller sections. This is known as chunking, a progressive disclosure pattern used to make the informa
Good point! I'll follow up with a revision and see if I can use that format in other sections.

2023-01-17 21:35 UTC, KellieHawks approved these changes

2023-01-17 21:36 UTC, merged