BD-1887: Deliverability for Chinese Android devices
braze-inc/braze-docs pull request #4762
Opened 2023-02-01 23:38 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> New push best practices article for deliverability nuances when targeting Android devices manufactured by Chinese OEMs.

Closes #**BD-1887**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [X] No

2023-02-03 23:06 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/push/best_practices/chinese_push_deliverability..md
> +Some Android devices manufactured by Chinese Original Equipment Manufacturers (OEMs), such as Xiaomi, OPPO, and Vivo, optimize for longer battery lives. This optimization may have the unintended cons
```suggestion
Some Android devices manufactured by Chinese Original Equipment Manufacturers (OEMs), such as Xiaomi, OPPO, and Vivo, optimize for longer battery lives. This optimization may have the unintended consequence of shutting down background app processing, which can reduce deliverability of your push notifications. To make sure that your app's messaging performance works as expected on these devices, your marketing and engineering teams should collaborate and follow the steps outlined in this article.
```

2023-02-03 23:06 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/push/best_practices/chinese_push_deliverability..md
> +To solve for this, integrate a library like [AutoStarter](https://github.com/judemanutd/AutoStarter) into your application. AutoStarter supports multiple manufacturers, giving you an easy way to call
```suggestion
To solve for this, integrate a library like [AutoStarter](https://github.com/judemanutd/AutoStarter) into your application. AutoStarter supports multiple manufacturers, giving you an easy way to call the startup permission manager on a wide array of devices. After you have integrated AutoStarter, call `AutoStartPermissionHelper.getInstance().getAutoStartPermission(context)` to bring up the startup permission manager on your end user's device. Couple this action with a prompt encouraging the end user to enable "auto-start" for your app. Your Marketing team will craft this message—see the next section!
```

2023-02-06 16:37 UTC, lydia-xie requested changes
lgtm! caught 1 small thing

2023-02-06 16:37 UTC, lydia-xie commented on _docs/_user_guide/message_building_by_channel/push/best_practices/chinese_push_deliverability..md
> +To solve for this, integrate a library like [AutoStarter](https://github.com/judemanutd/AutoStarter) into your application. AutoStarter supports multiple manufacturers, giving you an easy way to call
```suggestion
To solve for this, integrate a library like [AutoStarter](https://github.com/judemanutd/AutoStarter) into your application. AutoStarter supports multiple manufacturers, giving you an easy way to call the startup permission manager on a wide array of devices. After you have integrated AutoStarter, call `AutoStartPermissionHelper.getInstance().getAutoStartPermission(context)` to bring up the startup permission manager on your end user's device. Couple this action with a prompt encouraging the end user to enable "auto-start" for your app. Your marketing team will craft this message—see the next section!
```

2023-02-06 18:09 UTC, radixdev commented on _docs/_user_guide/message_building_by_channel/push/best_practices/chinese_push_deliverability..md
> +Some Android devices manufactured by Chinese Original Equipment Manufacturers (OEMs), such as Xiaomi, OPPO, and Vivo, optimize for longer battery lives. This optimization may have the unintended cons
```suggestion
Some Android devices manufactured by Chinese Original Equipment Manufacturers (OEMs), such as Xiaomi, OPPO, and Vivo, optimize for longer battery lives through aggressive app lifecycle management. This optimization may have the unintended consequence of shutting down background app processing, which can reduce the deliverability of your push notifications. To make sure that your app's messaging performance works as expected on these devices, your marketing and engineering teams should collaborate and follow the steps outlined in this article.
```

2023-02-06 18:11 UTC, radixdev commented on _docs/_user_guide/message_building_by_channel/push/best_practices/chinese_push_deliverability..md
> +This can be achieved by having your app automatically start on your end user's device, which gives your app permission to run in the background and listen for messages from Braze. Unfortunately, sinc
```suggestion
This can be achieved by having your app automatically start on your end user's device, which gives your app permission to run in the background and listen for messages from Braze. Unfortunately, since this is an OEM-specific problem and not an Android problem, there are no documented APIs for bringing up the auto-start permission prompt for each OEM.
```

2023-02-06 18:20 UTC, radixdev commented on _docs/_user_guide/message_building_by_channel/push/best_practices/chinese_push_deliverability..md
> +The way that OEMs optimize for battery life is by adding "unrecognized apps" to a blocklist that prevents them from running in the background. As a developer, you'll need to configure your app so tha
```suggestion
These OEMs perform their optimizations through aggressive killing of background applications and blocking them from self starting to run background tasks. As a developer, you'll need to configure your app to ask the user to ease these restrictions whenever possible.
```

2023-02-06 18:22 UTC, radixdev commented on _docs/_user_guide/message_building_by_channel/push/best_practices/chinese_push_deliverability..md
> +To further amplify your message, add other channels to resurface information from unopened push notifications. For example, out-of-app channels like SMS, WhatsApp, and LINE and in-app channels like i
```suggestion
To further amplify your message, add other channels to resurface information from unopened push notifications through out-of-app channels such as SMS, WhatsApp, and LINE and in-app channels like in-app messages and Content Cards. Your users will be able to see anything they might have missed the next time they open the app.
```

2023-02-06 18:33 UTC, lydia-xie approved these changes

2023-02-07 17:32 UTC, radixdev approved these changes

2023-02-07 17:32 UTC, merged