[SDK-3025] Swift Docs - In-App Messages
braze-inc/braze-docs pull request #4855
Opened 2023-02-16 19:37 UTC by jerielng

# Pull Request/Issue Resolution

#### Description of Change:
In-App Message documentation for the Swift SDK: https://jira.braze.com/browse/SDK-3025

#### Is this change associated with a Braze feature/product release?
- [X] Yes (**12/15/2022**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Currents<br>Internal Tools<br>Product Partnerships<br>SMS<br>Customer Lifecycle, Identity and Permissions</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Reporting<br>Intelligence<br>User Targeting<br>IAM<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging and Automation<br>Email (Composition and Infrastructure)</td>
  </tr>
</table>
</details>

2023-02-16 19:38 UTC, jerielng commented
> Deployment failed with the following error:
> 
> ```
> Was unable to schedule a deployment.
> ```

Not sure why the deployment failed, but the preview seems to be available [here](https://braze-docs-en-git-feature-sdk-3025-iam-swift-docs-braze.vercel.app/docs/developer_guide/platform_integration_guides/swift/in-app_messaging/overview/).

2023-02-17 21:29 UTC, lowip reviewed
LGTM overall, see comments

2023-02-17 21:29 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/setting_delegates.md
> +Not all delegate methods may not be available in Objective-C due to the incompatibility of their parameters with the language runtime.
```suggestion
Not all delegate methods are available in Objective-C due to the incompatibility of their parameters with the language runtime.
```

2023-02-17 21:29 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/handling_in_app_display.md
> +If the in-app message campaign is not displaying when the session has been started, make sure you have the necessary display logic added to your `inAppMessage(_:prepareWith:)` delegate method. This a
```suggestion
```

Not relevant anymore.

2023-02-17 21:29 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/handling_in_app_display.md
> +For `Full` and `HTML` in-app messages, the SDK will attempt to place the message over the status bar by default. However, in some cases, the status bar may still appear on top of the in-app message.
```suggestion
For `Full`, `FullImage` and `HTML` in-app messages, the SDK will hide the status bar by default. For other types of in-app messages, the status bar is left untouched. Using the `PresentationContext` object in your `inAppMessage(_:prepareWith:)` delegate method, you can configure the behavior of the status bar by setting the `statusBarHideBehavior` property. This field takes one of the following values:
```

2023-02-17 21:29 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/behavior_on_click.md
> +Each `Braze.InAppMessage` object can contain an instance of [`Context`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/inappmessageraw/context-swift.class), which defines va
I don't think we want clients replacing existing `Context`. By doing so, they will disable all SDK analytics on the in-app message.

Here, we should ask them to update the click action URL directly in the `prepareWith` delegate method:
```swift
message.clickAction.url = /* ... */
```

2023-02-17 21:29 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/behavior_on_click.md
>  To access the click action type of a button in a delegate method, you can use the following code:
I think this part about buttons can be removed. The `AppboyKit` delegate methods didn't provide the click action directly. The Swift SDK pass the correct click action as a parameter.

2023-02-17 21:29 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_app_store_review_prompt.md
> +    return .now
The indentation is off here

(Doesn't require a change:) I'm wondering why we're offering that workaround way and not ask the client to call `SKStoreReviewController.requestReview()` directly there?

2023-02-17 21:29 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
>  - The in-app message is an image-only modal in-app message but has no image.
```suggestion
```

Not relevant anymore. Those IAMs are discarded earlier in the lifecycle of the SDK

2023-02-17 21:29 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
We need to add a note here that by creating your own in-app message, you opt out of any analytics tracking.

2023-02-17 21:29 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/troubleshooting.md
>  - Failed image downloads will prevent in-app messages with images from displaying. Image downloads will always fail if the `SDWebImage` framework is not integrated properly. Check your device logs to
```suggestion
- Failed image downloads will prevent in-app messages with images from displaying. Check your device logs to ensure that image downloads are not failing.
```

2023-02-21 18:30 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_app_store_review_prompt.md
> +    return .now
The impression I got from this was if you wanted to give an example on how you might be able to use the same logic from our campaign dashboard to trigger it for any platform, whether iOS or Android.

2023-02-21 21:37 UTC, hokstuff approved these changes
Just some minor nits - LGTM!

2023-02-21 21:37 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/customizing_orientation.md
> +The `inAppMessage(_:prepareWith:)` method is not available in Objective-C.
Oh I didn't realize this - good to know!

2023-02-21 21:37 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/handling_in_app_display.md
> +Logging in-app message impressions and clicks is not automatic when you implement completely custom handling (i.e., you circumvent Braze's in-app message display by returning `.discard` in your `inAp
```suggestion
Logging in-app message impressions and clicks is not automatic when you implement completely custom handling (i.e., you circumvent Braze's in-app message display by returning `.discard` in your `inAppMessage(_:displayChoiceForMessage:)`). If you choose to implement your own UI using our in-app message models, you must log analytics with the following methods on the `Braze.InAppMessage` class:
```

This block of text is outside any Swift vs ObjC tabs, so some of the syntax (e.g. `.discard`) are only in Swift. I think this is OK since it saves from diverging everywhere

2023-02-21 21:37 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/behavior_on_click.md
> +| `.url(URL, useWebView: Bool)` | Opens the given URL. If `useWebView` is set to `true`, it will open in a web view. |
```suggestion
| `.url(URL, useWebView: Bool)` | Opens the given URL in an external browser. If `useWebView` is set to `true`, it will open in a web view. |
```

2023-02-21 21:37 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_triggering.md
> + };
```suggestion
};
```

2023-02-21 21:37 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_triggering.md
>    NSLog("A push was received");
```suggestion
  print("A push was received")
```

2023-02-21 21:37 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_app_store_review_prompt.md
> +- (enum BRZInAppMessageUIDisplayChoice)inAppMessage:(BrazeInAppMessageUI *)ui displayChoiceForMessage:(BRZInAppMessageRaw *)message {
nit: Maybe we can make this 2 lines since it is long?

2023-02-22 15:06 UTC, lowip approved these changes
LGTM

2023-02-22 15:06 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/handling_in_app_display.md
> +| `.visible`                          | Always display the status bar.                                                        |
```suggestion
| `.visible`                          | Always display the status bar.                                                        |
{: .reset-td-br-1 .reset-td-br-2}
```

@josh-mccrowell-braze, do we need to add those special directives each time we display a table? I've seen them used on other tables.

2023-02-22 18:55 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/handling_in_app_display.md
> +| `.visible`                          | Always display the status bar.                                                        |
@lowip : Yes, probably a good idea. They keep line wrapping from breaking words.

2023-02-22 22:19 UTC, cbowns approved these changes

2023-02-23 22:23 UTC, josh-mccrowell-braze reviewed
Great work here!

Haven't finished my review yet, but created a few comments as I worked today. Submitting the review so the comments aren't pending, but will come back to this in a few days as soon as I get an opportunity to finalize my review.

2023-03-01 18:36 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
> +- `Control`
> Am I right in thinking:
> Slideup = slideup (ha, duh)
> Modal and modal image = modal
> Full, HTML full, and full image = full screen

I think this is mostly correct. On the SDK side, there's little difference on how we present `HTML full` and `HTML` campaigns:

- HTML Full: html + assets are provided as a zip file, presentation animation sliding from bottom to top
- HTML: html + assets are provided as URLs, presentation animation: fade in

I'm not sure how we market differently HTML Full and HTML campaigns (apart from mentioning the live preview in the dashboard UI). Technically speaking, a client can use either HTML Full or HTML to create their own custom modals. So this type of campaign don't necessarily translate to full screen campaigns.

2023-03-01 20:17 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
> +All in-app messages are enumerated types of `Braze.InAppMessage`, which defines basic behavior and traits for all in-app messages. The in-app message class enums are as follows:
Ah, I meant this to segue into the types in each of the tabs below. I've updated this to be more descriptive of the intention.

2023-03-01 21:19 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
> +All in-app messages are enumerated types of `Braze.InAppMessage`, which defines basic behavior and traits for all in-app messages. The in-app message class enums are as follows:
Ahhh, now I get it. Thanks for clarifying!

2023-03-02 21:39 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
> +- `Control`
@josh-mccrowell-braze I've added information about `Control` in-app message types. IMO, I feel like this would be something more related to the internals of how our Swift SDK processes control group messages rather than being an in-app message type (so maybe we could remove it), but since it is a publicly documented type in our Swift class docs, I've written up a description in case customers might be curious about the usage.

Let me know what you think!

2023-03-03 15:16 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/overview.md
> +- `Control`
@jerielng Thank you! Pivoting back to this today, so will take another look at that article and then endeavor to finish out this set.

2023-03-03 22:52 UTC, josh-mccrowell-braze requested changes
Great stuff as always.

I have a few questions about bits and pieces, submitted here, but these are minor.

I also have some formatting changes I'd like to propose currently stashed on my machine, but don't want to invalidate the review questions. Once these small questions are answered, I think I'll have one last _bit_ to have you review.

Thanks for all this work!

2023-03-03 22:52 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_triggering.md
>  ## Step 1: Handle silent push and key-value pairs
@jerielng Am I right in reading these three steps not as sequential but as three separate options for creating server-side events that the SDK logs and then triggers an IAM?

2023-03-03 22:52 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/in-app_message_delivery.md
> +`Braze.InAppMessage` objects may carry key-value pairs as `extras`. These are specified on the dashboard when creating a campaign. Key-value pairs can be used to send data down with an in-app message
Would it be possible to build this out with a use case and example?

2023-03-03 22:52 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_app_store_review_prompt.md
@jerielng Am I correct in thinking that the key-value pair on line 92 should have straight quotes, not curly quotes?

2023-03-03 22:52 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_app_store_review_prompt.md
>  In your deep link handling code, add the following code to process the `{YOUR-APP-SCHEME}:appstore-review` deep link. Note that you will need to import `StoreKit` to use `SKStoreReviewController`:
Since "App Store" is two words, should this be {YOUR-APP-SCHEME}:app-store-review` (here and elsewhere), or is this hardcoded in a way I don't realize?

2023-03-03 22:52 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_app_store_review_prompt.md
Also, ditto question about the styling of "Appstore" vs "AppStore" as above.

2023-03-07 17:19 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_triggering.md
>  ## Step 1: Handle silent push and key-value pairs
Not quite - these are sequential, since the part in step 1 is watching for the extras values specified in the push campaign from step 2 to ensure that we get a matching trigger, and the IAM setup in step 3 provides the in-app trigger that's mapped to the silent push from step 2.

2023-03-07 17:21 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_app_store_review_prompt.md
Good catch - I think the idea is that they just need to make sure that there's quotes around it, but depending on the text editor, it can apply some weird formatting so that it ends up being a different ASCII value which can cause some of this code to not work depending on the context. I've updated it now!

As for the formatting of `AppStore`, it shouldn't matter as long as long as the usage is consistent throughout the code. That being said, it might make more sense to be `AppStore`, so I'll go ahead and update that.

2023-03-07 18:04 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_app_store_review_prompt.md
>  In your deep link handling code, add the following code to process the `{YOUR-APP-SCHEME}:appstore-review` deep link. Note that you will need to import `StoreKit` to use `SKStoreReviewController`:
It should just match whatever you set up in the campaign, on line 93. But I've updated it to say `app-store-review` instead since it makes more sense!

2023-03-08 15:16 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/in-app_messaging/customization/custom_triggering.md
>  ## Step 1: Handle silent push and key-value pairs
Got it. Thanks!

2023-03-08 21:56 UTC, josh-mccrowell-braze approved these changes
Great stuff!

2023-03-08 22:26 UTC, merged