[SDK-3028] Add advanced used cases for Swift
braze-inc/braze-docs pull request #5057
Opened 2023-03-17 18:55 UTC by nigelfaustino

# Pull Request/Issue Resolution

#### Description of Change:
> Advanced Use Cases updated for Swift

Closes SDK-3028

#### Is this change associated with a Braze feature/product release?
- [X ] Yes (12/15/2022)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Currents<br>Internal Tools<br>Product Partnerships<br>SMS<br>Customer Lifecycle, Identity and Permissions</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Reporting<br>Intelligence<br>User Targeting<br>IAM<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging and Automation<br>Email (Composition and Infrastructure)</td>
  </tr>
</table>
</details>

2023-03-21 20:32 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/beacon_integration.md
> +AppDelegate.braze?.logCustomEvent("Entered %@", visit.place.name)
Could we swap the order of Swift and Objective-C?

2023-03-21 20:35 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/fine_network_traffic_control.md
> +These policies can be set at app startup time from the [`startWithApiKey:inApplication:withLaunchOptions:withAppboyOptions`][3] method. In the `configuration` object, set the `Braze.Configuration.Api
Looks like this method is from AppboyKit - 
```suggestion
These policies can be set at app startup time when you initialize the Braze configuration. In the `configuration` object, set the `Braze.Configuration.Api.RequestPolicy` as shown in the following code snippet:
```

2023-03-21 20:37 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/fine_network_traffic_control.md
> +These policies can be set at app startup time from the [`startWithApiKey:inApplication:withLaunchOptions:withAppboyOptions`][3] method. In the `configuration` object, set the `Braze.Configuration.Api
We'll probably need to remove the URL. Maybe we could replace it with a link to [`RequestPolicy`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/configuration-swift.class/api-swift.class/requestpolicy-swift.enum) instead and assign it to the value mentioned above

2023-03-21 20:38 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/fine_network_traffic_control.md
> +configuration.api.requestPolicy = .automatic;
Objective-C doesn't have the `.` shorthand syntax the same way Swift does. Because of this, we have to explicitly declare the enum type like so:
```suggestion
configuration.api.requestPolicy = BRZRequestPolicyAutomatic;
```

2023-03-21 20:42 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +  apiKey: "<BRAZE_API_KEY>",
I think we want to use `{}` instead of `<>` - @josh-mccrowell-braze for sanity check?

2023-03-21 20:44 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +  apiKey: "<BRAZE_API_KEY>",
Yep, good callout! As a shorthand for "This is placeholder text to be replaced," {} is the tech writing team's shorthand for that!

2023-03-21 21:19 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  Starting with iOS 9, apps must have a whitelist of custom schemes that the app is allowed to open. Attempting to call schemes outside this list will cause the system to record an error in the device'
The Swift SDK supports iOS 11+, so we should remove any mention around previous versions (e.g. here with iOS 9) and assume all clients are on iOS 11+

2023-03-21 21:19 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
Can we update line 31 to use a capital `i` in `Info.plist`

2023-03-21 21:19 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
In line 138, I think we should word it like:
```
Refer to [Apple's documentation][11] for more information.
```

2023-03-21 21:19 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  ATS is applied by default on iOS 9+. It requires that all connections use HTTPS and are encrypted using TLS 1.2 with forward secrecy. Refer to [Requirements for Connecting Using ATS][14] for more inf
Same note around `iOS 9` in line 145

2023-03-21 21:19 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +configuration.automaticGeofencesRequest = false;
```suggestion
configuration.automaticGeofencesRequest = NO;
```

2023-03-23 18:22 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/beacon_integration.md
> +AppDelegate.braze?.logCustomEvent("Entered %@", visit.place.name)
I completed this request when I re-implemented how we surface this info!

2023-03-23 18:24 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  Starting with iOS 9, apps must have a whitelist of custom schemes that the app is allowed to open. Attempting to call schemes outside this list will cause the system to record an error in the device'
The requirement to allowlist custom schemes is still true for iOS 11+, correct?

2023-03-23 18:40 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  To use universal links, make sure you have added a registered domain to your app's capabilities and have uploaded an `apple-app-site-association` file. Then implement the method `application:continue
I was surprised by the note that universal links weren't compatible with so many Braze features. Let me ask: What is the purpose of the ## Universal links section? Is it just to address how universal links would normally be implemented if the user did not care about Braze push notifications, IAM, etc. compatibility?

2023-03-23 18:41 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  To use universal links, make sure you have added a registered domain to your app's capabilities and have uploaded an `apple-app-site-association` file. Then implement the method `application:continue
Based on your answer to the above, I might recommend moving the universal link warning to the top of this article, then calling out how the alternative implementations listed in this article allow users to accomplish deep links without universal links. 

I can help with this, just let me know!

2023-03-23 18:42 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  ATS is applied by default on iOS 9+. It requires that all connections use HTTPS and are encrypted using TLS 1.2 with forward secrecy. Refer to [Requirements for Connecting Using ATS][14] for more inf
@hokstuff For clarity, this means that the ATS workarounds described here would be necessary for all of our users? Have I understood you correctly there?

2023-03-23 19:00 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  ```
Similarly, are all of these options for partially or completely disability ATS something we still feel high confidence in endorsing/linking to?

2023-03-23 19:21 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
@nigelfaustino There's a link to ABKURLDelegate.h on line 191. Was this included in error?

2023-03-23 19:25 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  3. If you are using custom scheme-based deep links, add the following code to your `application:openURL:options:` method:
@nigelfaustino Line 299 says that universal links can be used to deep link to your app's settings, but earlier the tutorial said that universal links did not play nice with Braze features like push notifications or IAM. Is this claim on 299 accurate?

2023-03-23 19:55 UTC, josh-mccrowell-braze commented
@nigelfaustino I noticed that the Google Tag Manager article wasn't updated as part of this effort. Just doublechecking: has this been reviewed for potential changes from the Swift SDK?

2023-03-23 20:44 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
>  To control the location that the SDK reports for the purposes of receiving the most relevant geofences, starting in iOS SDK version 3.21.3, you can manually request geofences by providing the latitud
@nigelfaustino Is this reference to the iOS SDK version intentional? Could you please doublecheck the introduction to this section to make sure these recommendations are still accurate and up to date?

2023-03-23 21:01 UTC, josh-mccrowell-braze requested changes
This is great, thanks for taking this on! 

I provided some copy and style edits and pushed them up. Would you please review them to make sure I did not change any of the intended meanings? I also left a few questions. I see the rest of the team had a few questions that are still waiting to be resolved as well. 

Once those are taken care of and any other reviews are done, just re-request my review and I will handle the merge. 

Thanks again!

2023-03-24 14:53 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +nav_title: Locations and Geofences
General question: How does this section relate to turning on automatic location tracking (ala https://braze-docs-qlxwa9y1a-braze.vercel.app/docs/developer_guide/platform_integration_guides/swift/analytics/location_tracking/#enabling-automatic-location-tracking)

2023-03-24 20:22 UTC, nigelfaustino commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
>  To control the location that the SDK reports for the purposes of receiving the most relevant geofences, starting in iOS SDK version 3.21.3, you can manually request geofences by providing the latitud
I'll remove the version, that's unintentional

2023-03-24 20:27 UTC, nigelfaustino commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
Yes, removing that.

2023-03-27 22:40 UTC, lowip reviewed
First pass, still need to review the Geofence section. There are some behavior changes there which allow a wider usage

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +<<<<<<< HEAD
```suggestion
```

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +Your example allowlist might look something like:
The example below should read `<string>fb</string>` for facebook. `fb://` works but there's no `facebook://` URL scheme in the Facebook app

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +The SDK percent-encodes links to create valid `NSURL`s. All link characters that are not allowed in a properly formed URL, such as Unicode characters, will be percent escaped.
```suggestion
The SDK percent-encodes links to create valid `URL`s. All link characters that are not allowed in a properly formed URL, such as Unicode characters, will be percent escaped.
```

Using Swift types names.

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +To decode an encoded link, use the `NSString` method [`stringByRemovingPercentEncoding`][8]. You must also return `true` in the `BrazeDelegate.braze(_:shouldOpenURL:)`. A call to action is required t
```suggestion
To decode an encoded link, use the `String` property [`removingPercentEncoding`][8]. You must also return `true` in the `BrazeDelegate.braze(_:shouldOpenURL:)`. A call to action is required to trigger the handling of the URL by your app. 
```

The documentation link is unchanged

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +  NSString *urlString = url.absoluteString.stringByRemovingPercentEncoding;
```suggestion
  NSString *urlString = [url.absoluteString stringByRemovingPercentEncoding];
```

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +The open-source `Braze.WebViewController` class displays web URLs opened by the SDK, typically when "Open Web URL Inside App" is selected for a web deep link.
```suggestion
The `Braze.WebViewController` class displays web URLs opened by the SDK, typically when "Open Web URL Inside App" is selected for a web deep link.
```

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +You can declare a category for, or directly modify, the `Braze.WebViewController` class to apply customization to the web view. Check the class's [documentation][6] for details.
```suggestion
You can customize the `Braze.WebViewController` via the [`BrazeDelegate.braze(_:willPresentModalWithContext:)`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/brazedelegate/braze(_:willpresentmodalwithcontext:)-12sqy/) delegate method.
```

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +    return true
```suggestion
    return false
```
One of the breaking change of the Swift [migration](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide#:~:text=MessageUI.delegate-,Warning,should%20be%20opened%20by%20Appboy%20(false)%20or%20not%20(true).,-SDK%20initialization%20and)

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +  return false
```suggestion
  return true
```

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +    return YES;
```suggestion
    return NO;
```

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +  return NO;
```suggestion
  return YES;
```

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +<<<<<<< HEAD
```suggestion
```

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +>>>>>>> bcad141d9c2dedc70fb0c45a8d74affc1288a581
```suggestion
```

2023-03-27 22:40 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
> +    UIApplication.shared.openURL(URL(string:UIApplicationOpenSettingsURLString)!)
```suggestion
    UIApplication.shared.openURL(URL(string:UIApplication.openSettingsURLString)!)
```

2023-04-07 19:20 UTC, nigelfaustino commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  Starting with iOS 9, apps must have a whitelist of custom schemes that the app is allowed to open. Attempting to call schemes outside this list will cause the system to record an error in the device'
That's correct

2023-04-07 20:52 UTC, nigelfaustino commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
>  To use universal links, make sure you have added a registered domain to your app's capabilities and have uploaded an `apple-app-site-association` file. Then implement the method `application:continue
Yeah, these are still accurate. Multiple customers still use universal links for various reasons like other partners so this section is also mainly to call out how this interacts with our SDK.

2023-04-07 20:52 UTC, nigelfaustino commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/linking.md
It's in the old obj-c docs, I removed them here since they don't seem to match the text

2023-04-10 16:15 UTC, jocelynzz commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/google_tag_manager.md
> +To get started, create a trigger that looks for an "Event Name" that equals "played song".
is the removal of the highlight intentional?

2023-04-10 16:18 UTC, jocelynzz commented on _docs/_partners/message_personalization/location/gimbal.md
> +
extra whitespace?

2023-04-11 15:51 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +Enable geofences by setting `location.geofencesEnabled` to `true` on the `configuration` object that initializes the[`Braze`][1] instance.
There's a couple of other `location` configurations mentioned in the code snippets. Should we provide a link to https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/configuration-swift.class/location-swift.class to describe the rest of the configurations?

2023-04-11 16:03 UTC, jerielng approved these changes
Couple of small comments but LGTM

2023-04-11 16:03 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/fine_network_traffic_control.md
> +[AppDelegate.braze requestImmediateDataFlush];
Looks like this code snippet is described twice. Any way we can condense it?

2023-04-11 16:03 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/google_tag_manager.md
> +Braze's iOS SDK can be initialized and controlled by tags configured within Google Tag Manager.
Nit: We could distinguish this from the original Obj-C SDK by changing this to:
```suggestion
Braze's Swift SDK can be initialized and controlled by tags configured within Google Tag Manager.
```

2023-04-11 16:03 UTC, jerielng commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/google_tag_manager.md
> +As a prerequisite for this implementation, your iOS SDK integration must be complete.
```suggestion
As a prerequisite for this implementation, your Swift SDK integration must be complete.
```

2023-04-11 19:48 UTC, nigelfaustino commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +Enable geofences by setting `location.geofencesEnabled` to `true` on the `configuration` object that initializes the[`Braze`][1] instance.
We could; most of that should be covered in the locations article, but I can add a link

2023-04-11 20:32 UTC, hokstuff approved these changes
Looks like there are just a few minor open comments - LGTM after! 🙏

2023-04-11 20:32 UTC, hokstuff commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/fine_network_traffic_control.md
> +These policies can be set at app startup time when you initialize the Braze configuration. In the `configuration` object, set the [`Braze.Configuration.Api.RequestPolicy`][3] as shown in the followin
nit: The URL links to the subcategory `automatic` instead of the `RequestPolicy` type itself
```suggestion
These policies can be set at app startup time when you initialize the Braze configuration. In the `configuration` object, set the [`Braze.Configuration.Api.RequestPolicy`][https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/configuration-swift.class/api-swift.class/requestpolicy-swift.enum] as shown in the following code snippet:
```

2023-04-11 20:32 UTC, hokstuff commented on _docs/_partners/message_personalization/location/gimbal.md
> +## Tracking custom events
```suggestion
## Tracking custom events

```

2023-04-12 20:38 UTC, lowip approved these changes
A few last changes, after that LGTM

2023-04-12 20:38 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +## Step 5: Add NSLocationAlwaysUsageDescription to your Info.plist
```suggestion
## Step 5: Add location usage description strings to your Info.plist
```

2023-04-12 20:38 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +Add the key `NSLocationAlwaysUsageDescription` and `NSLocationAlwaysAndWhenInUseUsageDescription` or `NSLocationWhenInUseUsageDescription` to your `info.plist` with a `String` value that has a descri
```suggestion
Add the key `NSLocationAlwaysUsageDescription`, `NSLocationAlwaysAndWhenInUseUsageDescription` or `NSLocationWhenInUseUsageDescription` to your `info.plist` with a `String` value that has a description of why your application needs to track location.
```

2023-04-12 20:38 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +locationManager.requestWhenInUseAuthorization()
```suggestion
locationManager.requestWhenInUseAuthorization()
// or
```

2023-04-12 20:38 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/locations_and_geofences.md
> +[locationManager requestAlwaysAuthorization];
```suggestion
[locationManager requestWhenInUseAuthorization];
// or
[locationManager requestAlwaysAuthorization];
```

2023-04-18 17:52 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/platform_integration_guides/swift/advanced_use_cases/google_tag_manager.md
> +To get started, create a trigger that looks for an "Event Name" that equals "played song".
Reframed to conform to general code case in each instance.

2023-04-18 18:19 UTC, josh-mccrowell-braze approved these changes

2023-04-18 20:08 UTC, merged