Updated Customizing Feed
braze-inc/braze-docs pull request #5421
Opened 2023-05-12 21:51 UTC by josh-mccrowell-braze

2023-05-15 17:16 UTC, wesleyorbin approved these changes

2023-05-15 17:16 UTC, wesleyorbin commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +function refresh(){
tiny formatting nit
```suggestion
function refresh() {
```

2023-05-15 17:16 UTC, wesleyorbin commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +  })
Optional change but this version is a little more succinct
```suggestion
  braze.showContentCards(null, function(cards) {
    return cards.filter((card) => card.extras["feed_type"] === feed_type);
  });
```

2023-05-15 17:19 UTC, spvismaya approved these changes

2023-05-18 16:11 UTC, radixdev approved these changes

2023-05-18 16:11 UTC, radixdev commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +![An empty feed error message that reads "This is a custom empty state message."][1]
Looks like this on android: 
![image](https://github.com/braze-inc/braze-docs/assets/2373546/6cca1205-1713-4994-94b3-d7c23be18e94)

tbh we can probably just not have a picture here though.

2023-05-18 19:04 UTC, jerielng commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +Change the language that appears automatically in empty Content Card feeds by [redefining the localizable content card strings](https://github.com/Appboy/appboy-ios-sdk/blob/3cca65b06f66085f5bc7c8e1a
It looks like we still have the same localizable assets in the Swift SDK [here](https://github.com/braze-inc/braze-swift-sdk/tree/main/Sources/BrazeUI/Resources/Localization/en.lproj). The `Attributes` empty state message pulls from these assets, so they should be able to do the same thing in an Objective-C context:
```
public var emptyStateMessage: String = localize(
  "braze.content-cards.no-card.text",
  for: .contentCard
)
```

2023-05-19 18:28 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +Change the language that appears automatically in empty Content Card feeds by [redefining the localizable content card strings](https://github.com/Appboy/appboy-ios-sdk/blob/3cca65b06f66085f5bc7c8e1a
Thanks! Could you please re-review this section just to make sure I got it right?

2023-05-19 18:31 UTC, josh-mccrowell-braze commented
@wesleyorbin : Thanks for giving this a look! Is there any option for **customizing displayed card order** or **changing “empty feed” language** for the Web SDK?

@jerielng : Thank you as well! Can you **customize displayed card order** in the Swift SDK?

2023-05-19 19:36 UTC, wesleyorbin commented
> @wesleyorbin : Thanks for giving this a look! Is there any option for **customizing displayed card order** or **changing “empty feed” language** for the Web SDK?

For customizing display order, you can use the `filterFunction` param of `showContentCards()`:

```javascript
braze.showContentCards(null, (cards) => {
  return sortBrazeCards(cards); // where sortBrazeCards is your sorting function that returns the sorted card array
});
```

There's no way to permanently change the empty feed language. You can replace it (example below), but you'd have to do it every time the feed is shown. However, the problem with that is the feed may take some time to refresh so the empty feed text won't be there right away. Overall, I wouldn't really recommend it.

```javascript
const emptyFeedText = document.querySelector(".ab-no-cards-message");
If (emptyFeedText) {
  emptyFeedText.innerHtml = "New empty feed language";
}
```

2023-05-19 21:12 UTC, josh-mccrowell-braze commented
@wesleyorbin : I took a basic swing at pulling those answers into the Web sections of the Customizing Feed article. Would you mind taking a look at those and correcting?

2023-05-22 14:25 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +![An empty feed error message that reads "This is a custom empty state message."][1]
Thanks! I agree about the picture. 

@radixdev Quick question: I'm trying to dig into what causes the empty feed message. I understand that the empty feed error message is a toast, and the linked picture is displayed when there’s no eligible feed. Updating  `EmptyContentCardsAdapter` only affects the view when there's no eligible feed, not the error displayed, correct? (I think they're the same message for Swift, so I'm trying to nail down the behavior here.)

2023-05-22 15:16 UTC, jerielng commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +Change the language that appears automatically in empty Content Card feeds by [redefining the localizable content card strings](https://github.com/Appboy/appboy-ios-sdk/blob/3cca65b06f66085f5bc7c8e1a
Looks good! I'll take a look at the displayed order piece as well.

2023-05-22 15:24 UTC, jerielng commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +public var emptyStateMessage: String = localize(
There wouldn't be any Objective-C code here. In an Obj-C context, since they can't utilize the attributes struct, they would need to just update the value for the string in that `.strings` file for the corresponding locale.

2023-05-22 15:40 UTC, wesleyorbin commented
> @wesleyorbin : I took a basic swing at pulling those answers into the Web sections of the Customizing Feed article. Would you mind taking a look at those and correcting?

LGTM!

2023-05-22 16:19 UTC, jerielng commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +<!--- Is this possible in the iOS SDK? If so, how? --->
If they are using BrazeUI, in Swift, they can use the `.transform` method in the `Attributes` struct before presenting the BrazeUI Content Cards view controller.
```
var attributes = BrazeContentCardUI.ViewController.Attributes.defaults
attributes.transform = { cards in
    cards.sorted {
        if $0.pinned && !$1.pinned {
            return true
        } else if !$0.pinned && $1.pinned {
            return false
        } else {
            return $0.createdAt > $1.createdAt
        }
    }
}
let viewController = BrazeContentCardUI.ViewController(braze: AppDelegate.braze, attributes: attributes)
```

An Objective-C example might be a little more involved since we don't have access to the `attributes` struct. I'll circle back on that one.

2023-05-22 17:49 UTC, jerielng commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +<!--- Is this possible in the iOS SDK? If so, how? --->
As far as Objective-C goes, there isn't really a way to do this without `attributes`. If a developer would like to sort the Content Cards, for example, they can do it using Swift and [bridge it to Objective-C](https://developer.apple.com/documentation/swift/importing-swift-into-objective-c). So we could say something like this in the Objective-C tab:
```
Customization via `BrazeContentCardUI.ViewController.Attributes` is not available in Objective-C. If you wish to customize the display of your Content Cards before presentation, you can create a separate file in Swift using the corresponding example and then call your Swift class from Objective-C.

For more details on bridging to Objective-C, refer to [Importing Swift into Objective-C](https://developer.apple.com/documentation/swift/importing-swift-into-objective-c).
```

2023-05-22 18:32 UTC, jerielng commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +Change the language that appears automatically in empty Content Card feeds by [redefining the localizable content card strings](https://github.com/Appboy/appboy-ios-sdk/blob/3cca65b06f66085f5bc7c8e1a
Ah sorry I just realized the confusion here - the code snippet I attached above isn't an example of what they should do, but I was sharing it to show where that `"braze.content-cards.no-card.text"` string is being used in our SDK. I left a comment in the corresponding place, but basically, they would need to override the string for that key in their `Localizable.strings` file, rather than doing any Objective-C specific code.

2023-05-22 22:01 UTC, josh-mccrowell-braze commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +<!--- Is this possible in the iOS SDK? If so, how? --->
Thanks! This is very helpful.

We haven't, elsewhere, given workarounds like bridging from Swift to Objective-C, so I'm hesitant to do so here. If we wanted to provide this guidance elsewhere, we can do so, then link to it from our own documentation. Holding off on doing that until the need becomes apparent.

2023-05-22 22:18 UTC, josh-mccrowell-braze commented
@bre-fitzgerald : This is an article in the customization/content cards effort. It's being merged into a feature branch. Would you please give this a review for style and correctness any time before end of week? 

Let me know if you have any questions! Thank you very much!

2023-05-22 22:51 UTC, bre-fitzgerald requested changes
Content looks good to me! Just a few broken links

2023-05-22 22:51 UTC, bre-fitzgerald commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +When creating a Content Card campaign, set [key-value pair data]({{site.baseurl}}/docs/developer_guide/customization_guides/content_cards/customizing_behavior/) on each card. Our filtering logic will
```suggestion
When creating a Content Card campaign, set [key-value pair data]({{site.baseurl}}/developer_guide/customization_guides/content_cards/customizing_behavior/) on each card. Our filtering logic will use this key-value pair to categorize cards. 
```

2023-05-22 22:51 UTC, bre-fitzgerald commented on _docs/_developer_guide/customization_guides/content_cards/customizing_feed.md
> +For more information on customizing Content Card style elements, see [Customizing style]({{site.baseurl}}/docs/developer_guide/customization_guides/content_cards/customizing_styles).
```suggestion
For more information on customizing Content Card style elements, see [Customizing style]({{site.baseurl}}/developer_guide/customization_guides/content_cards/customizing_styles).
```

2023-05-22 23:06 UTC, merged