Regal Partnership Docs
braze-inc/braze-docs pull request #5426
Opened 2023-05-15 20:36 UTC by KellieHawks

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Currents<br>Internal Tools<br>Product Partnerships<br>SMS<br>Customer Lifecycle, Identity and Permissions</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Reporting<br>Intelligence<br>User Targeting<br>IAM<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging and Automation<br>Email (Composition and Infrastructure)</td>
  </tr>
</table>
</details>

2023-05-16 20:39 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/regal.md
> +### Step 1: Create new contacts in Regal
We probably want to call out that these could be a Campaign or a Canvas

2023-05-16 20:45 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/regal.md
> +2. Set the trigger node logic as "User Profile Field Updated" and select whatever field represents the user's opt-in status. If, you fire an event to Braze to represent opt-in or out, use that event
Although the triggering logic could be "User Profile Field Updated" the customer might want to use the ["Update Subscription Group Status"](https://www.braze.com/docs/user_guide/engagement_tools/campaigns/building_campaigns/delivery_types/triggered_delivery/#setting-up-a-triggered-campaign) trigger or the Subscription Status trigger for global email preference. Which is fired automatically when the subscription status is updated.

2023-05-16 20:54 UTC, alex-braze reviewed
Added two comments in:

1. All the webhooks noted in the documentation could be set up as a Canvas or a Campaign so we might want to call that out to ensure customers do not think they have to use a Canvas for each of these use cases.
2. I added a recommendation of another triggering event type the customer might want to use with the subscription preference change webhooks.

2023-05-23 20:54 UTC, bre-fitzgerald requested changes
Hey! Looks good, a couple of comments and suggestions for your review :)

2023-05-23 20:54 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
> +**Request Body**: Raw Text
Formatting suggestion
```suggestion
3. In your new Webhook template, fill out the following fields:
   - **Webhook URL**: <https://events.regalvoice.com/events>
   - **Request Body**: Raw Text
```

2023-05-23 20:54 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
> +| Regal API key | A Regal API key will allow sending events from Braze to Regal.<br><br>Email support@regal.io to get this key. |
```suggestion
| Regal API key | A Regal API key will allow sending events from Braze to Regal.<br><br>Email [support@regal.io](mailto:support@regal.io) to get this key. |
```

2023-05-23 20:54 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
> +Regal.io also requires an HTTP Header for authorization and an HTTP method. The following will already be included within the template as a key-value pair, but in the **Settings** tab:
Not sure if it makes sense to say "but" here 🤔 I'd suggest striking
```suggestion
Regal.io also requires an HTTP Header for authorization and an HTTP method. The following will already be included within the template as a key-value pair in the **Settings** tab:
```

2023-05-23 20:54 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
> +**Request Body**: Raw Text
Same formatting suggestion as above
```suggestion
3. In your new Webhook template, fill out the following fields:
   - **Webhook URL**: <https://events.regalvoice.com/events>
   - **Request Body**: Raw Text
```

2023-05-23 20:54 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
> +**Request Body**: Raw Text
```suggestion
3. In your new Webhook template, fill out the following fields:
   - **Webhook URL**: <https://events.regalvoice.com/events>
   - **Request Body**: Raw Text
```

2023-05-23 20:54 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
> +- Use the vertical menu icon to copy the webhook URL
```suggestion
1. Navigate to the **Transformations** page in your Braze dashboard.
2. Give your transformation a name and click **Create transformation**.
3. From the list of transformations, click <i class="fa-solid fa-ellipsis-vertical" title="View actions"></i> and select **Copy webhook URL**.
```

2023-05-23 20:54 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
> +To set up reporting Webhooks:
```suggestion
To set up reporting webhooks:
```

2023-05-23 20:54 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/additional_channels/messaging/regal.md
> +- Braze does not support phone numbers as an identifier. To use this as an identifier, the phone number can be set as a user alias. To learn more about Braze User Aliases, refer to this [documentatio
Suggestion for more meaningful link text
```suggestion
- Braze does not support phone numbers as an identifier. To use this as an identifier, the phone number can be set as a [user alias][8] in Braze.
```

2023-05-24 15:50 UTC, merged