July release
braze-inc/braze-docs pull request #5835
Opened 2023-07-21 20:34 UTC by josh-mccrowell-braze

2023-07-21 20:36 UTC, KellieHawks commented
@josh-mccrowell-braze 
Don't forget to add to this page: https://www.braze.com/docs/help/release_notes

2023-07-21 20:40 UTC, josh-mccrowell-braze commented
@KellieHawks Thanks for the reminder! Will do. This PR is just to check my math on the release notes right now - will add SDK notes, add the release notes page, etc. once those are finalized. 😸

2023-07-21 20:46 UTC, rachel-feinberg commented on _docs/_help/release_notes/2023/7_25_23.md
> +The new [Managing Segments]{{site.baseurl}}/user_guide/engagement_tools/segments/managing_segments/) article covers the actions you can take to configure your segments, such as filtering a list of se
[Managing Segments]({{site.baseurl}}/user_guide/engagement_tools/segments/managing_segments/)

2023-07-21 20:48 UTC, rachel-feinberg commented on _docs/_help/release_notes/2023/7_25_23.md
> +The new Canvas approval workflow setting adds a review process prior to launching a new Canvas. Please note that this feature is turned off by default, giving you control over its implementation. Exp
Can remove "Please" per the Style Guide ("Note that this feature...")

2023-07-21 20:56 UTC, josh-mccrowell-braze commented on _docs/_help/release_notes/2023/7_25_23.md
> +The new Canvas approval workflow setting adds a review process prior to launching a new Canvas. Please note that this feature is turned off by default, giving you control over its implementation. Exp
Great callout, thanks! Will do!

2023-07-21 20:58 UTC, lydia-xie requested changes
looks good - added some suggestions!

2023-07-21 20:58 UTC, lydia-xie commented on _docs/_help/release_notes/2023/7_25_23.md
> +page_order: 7
```suggestion
page_order: 5
```

2023-07-21 20:58 UTC, lydia-xie commented on _docs/_help/release_notes/2023/7_25_23.md
> +# July 25, 2023
```suggestion
# July 25, 2023 release
```

2023-07-21 20:58 UTC, lydia-xie commented on _docs/_help/release_notes/2023/7_25_23.md
> +## Update by phone (early access)
```suggestion
## Updating a user profile by phone number
```

2023-07-21 20:58 UTC, lydia-xie commented on _docs/_help/release_notes/2023/7_25_23.md
> +Using the [`/users/track`]({{site.baseurl}}/api/endpoints/user_data/post_user_track) endpoint, you can update a user profile using their phone number. This feature is currently in early access. Conta
```suggestion
Using the [`/users/track`]({{site.baseurl}}/api/endpoints/user_data/post_user_track) endpoint, you can update a user profile using their phone number. 

{% alert important %}
This feature is currently in early access. Contact your Braze account manager if you're interested in participating in the early access.
{% endalert %}
```

2023-07-24 15:30 UTC, bre-fitzgerald approved these changes
lgtm given Rachel and Kellie's comments 👍

2023-07-24 15:33 UTC, rachel-feinberg approved these changes
Lgtm! Left a small style comment.

2023-07-25 14:42 UTC, josh-mccrowell-braze commented
@KellieHawks : Applied changes from review, added SDK release notes and links to changelogs, built out. I _think_ this is ready to go, but need a last close review to make sure everything is ready to ship.

2023-07-25 14:43 UTC, KellieHawks commented on _docs/_help/release_notes/2023.md
> +  - name: July 25, 2022
```suggestion
  - name: July 25, 2023
```

2023-07-25 14:44 UTC, KellieHawks requested changes
Looks great! One minor fix needed.

2023-07-25 14:44 UTC, josh-mccrowell-braze commented on _docs/_help/release_notes/2023.md
> +  - name: July 25, 2022
😭 thanks

2023-07-25 14:48 UTC, KellieHawks approved these changes

2023-07-25 14:49 UTC, merged