BD-2334: Conversions dashboard v2 EA
braze-inc/braze-docs pull request #5916
Opened 2023-08-02 21:50 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-2334**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2023-08-02 22:43 UTC, bre-fitzgerald commented
FYI @rachel-feinberg, this is currently in EA, but when these changes to the Conversions dashboard go to GA, the content of this hidden doc will replace the current content of the [Conversions dashboard](https://www.braze.com/docs/user_guide/data_and_analytics/analytics/conversions_dashboard/) page. So we'll just need to redirect the URL `/docs/conversions_dashboard_v2/` to the current Conversions dashboard page and delete the hidden doc.

2023-08-03 15:00 UTC, josh-mccrowell-braze commented on assets/css/_content.scss
Hey - So I can learn, can I ask what this change does for the CSS?

2023-08-03 15:23 UTC, bre-fitzgerald commented on assets/css/_content.scss
Oh, yes, Zeyuan put together [this PR](https://github.com/braze-inc/braze-docs/pull/5451) that allows us to use the `{:start="2"}` syntax to break up a numbered list with alerts, but it only went up to 5. I updated it to go up to 9 because it was limiting this PR.

2023-08-03 15:43 UTC, josh-mccrowell-braze requested changes

2023-08-03 15:43 UTC, josh-mccrowell-braze commented on _docs/_hidden/private_betas/conversions_dashboard_v2.md
> +Coming soon
So, I know in early access we are more permissive about the "[Future Feature" guidelines](https://docs.google.com/document/d/1YWnIteF6aEvuo7eNhkOQMQOCyEhwVwQb1O4lJDEngvs/edit#heading=h.4wvw32nz50ee) from the style guide, but a section with plain text "Coming soon" strikes me as perhaps a stretch. Consider removing or expanding.

2023-08-03 15:43 UTC, josh-mccrowell-braze commented on _docs/_hidden/private_betas/conversions_dashboard_v2.md
> +4. Select a **Channel** that you would like to analyze for your messages. For now, you can select a single channel. We are working on adding multi-channel support.
I understand that we are less strict about avoiding "Future Feature" clauses for early access products, but I think this instance would be worthwhile cutting.

2023-08-03 15:43 UTC, josh-mccrowell-braze commented on _docs/_hidden/private_betas/conversions_dashboard_v2.md
> +5. (Optional) Select a **Breakdown** layer to view different dimensions of data.
What are the different dimensions of data? Without looking at the product, I can't intuit what this means. Consider adding examples.

2023-08-03 15:43 UTC, josh-mccrowell-braze commented on _docs/_hidden/private_betas/conversions_dashboard_v2.md
> +6. If you are interested in calculating conversions of an event that was not set up as a conversion event on the campaign or Canvas, turn on **Use custom events**.
Because custom events have two sub-steps and an alert, would it be worthwhile pulling these out of the numbered list and just having this as prose in an H2? This might make the numbered list read in a less fractured way.

2023-08-03 15:43 UTC, josh-mccrowell-braze commented on _docs/_hidden/private_betas/conversions_dashboard_v2.md
> +- *Conversions* are defined by the attribution method you selected when you set up the report. See the following sections for additional details on the attribution methods.
Are attribution methods all following sections, or just the section titled "Attribution methods"?

If the latter, consider providing a link.

If the former, consider using different phrasing.

2023-08-03 19:27 UTC, josh-mccrowell-braze approved these changes
Thanks so much for taking the extra time with this one to give it a little white glove treatment. It looks great!

2023-08-03 19:27 UTC, merged