OfferFit - Partner Docs
braze-inc/braze-docs pull request #5966
Opened 2023-08-11 13:27 UTC by vladzamfirescu

# Pull Request/Issue Resolution

#### Description of Change:
Add partner documentation for OfferFit integration.

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [X] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [X] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [X] Check that all links work.
- [X] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/). This was submitted on behalf of OfferFit, Inc. by Samuel Jackson, Senior Director Marketing, Business Development, and Partnerships. (GitHub username @samuelofferfit)
- [ ] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @bre-fitzgerald for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

2023-08-17 22:00 UTC, alex-braze requested changes
Hey @vladzamfirescu thanks for submitting your docs! I've added a few inline comments. Please let me know if you have any questions.

2023-08-17 22:00 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/offerfit/offerfit.md
> +## Using this integration
It may be worth calling out here whether customers can set up more than one Braze campaign or canvas to work with Offerfit.

2023-08-18 07:51 UTC, vladzamfirescu commented on _docs/_hidden/wip_partnerships/offerfit/offerfit.md
> +### Step 1: Define Braze target audience
This step refers only to defining the Braze Segment on the Braze platform. I've updated the title to "Define target audience in Braze" to make it clearer for the end user.

2023-08-18 07:59 UTC, vladzamfirescu commented on _docs/_hidden/wip_partnerships/offerfit/offerfit.md
> +| Braze REST API key  | A Braze REST API key with the following permissions: <li>`users.export.ids`</li> <li>`users.export.segment`</li> <li>`messages.send`</li> <li>`users.export.segment`</li> <li>`
Thanks for the feedback. I will add an extra table detailing our standard usage of the API endpoints.

2023-08-21 15:24 UTC, alex-braze approved these changes

2023-08-21 19:36 UTC, rachel-feinberg commented
@cla-bot check

2023-08-21 19:45 UTC, rachel-feinberg commented
Hi @vladzamfirescu, it looks like your GitHub account may not be set up properly. Can you follow the steps provided by the cla-bot above and (if you haven't already) please sign our [CLA](https://www.braze.com/docs/cla/)?

2023-08-21 19:47 UTC, rachel-feinberg commented
Hi @vladzamfirescu, can you please sign our [CLA](https://www.braze.com/docs/cla/) so we can push your changes to our site? Thank you!

2023-08-21 20:07 UTC, vladzamfirescu commented
> Hi @vladzamfirescu, can you please sign our [CLA](https://www.braze.com/docs/cla/) so we can push your changes to our site? Thank you!

Hi @rachel-feinberg as mentioned in my email to Alex Rees, I am unable to sign the CLA on behalf of OfferFit. Thus, my colleague Samuel Jackson already submitted the CLA on behalf of OfferFit. Is it possible for me to submit the documentation while Sam signs the CLA? Or will Sam have to submit the PR?

2023-08-21 20:57 UTC, rachel-feinberg commented
> Hi @rachel-feinberg as mentioned in my email to Alex Rees, I am unable to sign the CLA on behalf of OfferFit. Thus, my colleague Samuel Jackson already submitted the CLA on behalf of OfferFit. Is it possible for me to submit the documentation while Sam signs the CLA? Or will Sam have to submit the PR?

Hi @vladzamfirescu, Sam would have to submit the PR, but I can create my own branch to push the changes. Could you share Sam's GitHub username with me? After that, I'll go ahead and transfer the content from your PR to my branch.

2023-08-21 21:05 UTC, vladzamfirescu commented
> > Hi @rachel-feinberg as mentioned in my email to Alex Rees, I am unable to sign the CLA on behalf of OfferFit. Thus, my colleague Samuel Jackson already submitted the CLA on behalf of OfferFit. Is it possible for me to submit the documentation while Sam signs the CLA? Or will Sam have to submit the PR?
> 
> Hi @vladzamfirescu, Sam would have to submit the PR, but I can create my own branch to push the changes. Could you share Sam's GitHub username with me? After that, I'll go ahead and transfer the content from your PR to my branch.

Hi @rachel-feinberg Sam's GitHub username is @samuelofferfit

2023-08-21 23:08 UTC, rachel-feinberg commented
Closed because a new PR is created [here](https://github.com/braze-inc/braze-docs/pull/6013).

2023-08-21 23:08 UTC, closed without merging