BD-2357: Updates for team-level campaign and Canvas approval permissions
braze-inc/braze-docs pull request #5978
Opened 2023-08-15 22:51 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-2357**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2023-08-16 14:45 UTC, djhanggi commented on _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
>  Only admins and users with permission to manage approval settings will see this page.
Technically this no longer is true. Anyone can see the page I believe. Only admins can interact with it / change settings

2023-08-16 14:47 UTC, djhanggi commented on _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_approval.md
>  To edit a live campaign, you will need the "Approve and Deny Campaigns" permission. A user will need to approve their changes since a draft version of campaigns is not yet available. This is not the
Is it intended to have campaign language here since the page is for Canvases? Is it to highlight the difference between Campaign & Canvas behavior?

2023-08-16 18:04 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_approval.md
>  To edit a live campaign, you will need the "Approve and Deny Campaigns" permission. A user will need to approve their changes since a draft version of campaigns is not yet available. This is not the
Yes! Just to direct users to the similar feature for campaigns

2023-08-16 20:10 UTC, lydia-xie commented
@cla-bot check

2023-08-17 14:33 UTC, djhanggi commented on _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
> +The **Approve and Deny Campaigns** permission can also be applied to workspaces or [teams]({{site.baseurl}}/user_guide/administrative/app_settings/manage_your_braze_users/teams/), or added to a [perm
Should this be moved to its own section? It doesn't make sense in "Turning on campaign approval" IMO

Also should this be phrased like - "There is an Approve and Deny Campaigns permission that controls who can change the approval status of a campaign. ..."

2023-08-31 16:37 UTC, bre-fitzgerald requested changes
Some minor comments for your review :)

2023-08-31 16:37 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_approval.md
> +When you have the **Approve and Deny Canvases** permission, you'll have access to the **Summary** step of the Canvas builder. This page provides a summary of the key Canvas details with the option to
quotations for permission names per sg (when not telling them to interact w/ UI element like above)

```suggestion
When you have the "Approve and Deny Canvases" permission, you'll have access to the **Summary** step of the Canvas builder. This page provides a summary of the key Canvas details with the option to approve or deny these details, including conversion events, entry schedule, and the type and amount of components in your Canvas. Note the default state for Canvas approval is **Pending Approval**.
```

2023-08-31 16:37 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_approval.md
> +Be sure to check that you have the proper [user permissions]({{site.baseurl}}/user_guide/administrative/manage_your_braze_users/user_permissions/) to approve Canvases.
Perhaps we should link to the section below for "setting user permissions" here rather than to the main permissions article OR update the alert text to explicitly state the permission name? 🤔 

```suggestion
Be sure to check that you have the proper [user permissions]({{site.baseurl}}/user_guide/administrative/manage_your_braze_users/user_permissions/) to approve Canvases.
```

2023-08-31 16:37 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/campaigns/managing_campaigns/campaign_approval.md
> +Before using the approval workflow, you must have the **Approve and Deny Campaigns** permission. This permission controls who can update the approval status of a campaign. This permission can also be
```suggestion
Before using the approval workflow, you must have the "Approve and Deny Campaigns" permission. This permission controls who can update the approval status of a campaign. This permission can also be applied to workspaces or [teams]({{site.baseurl}}/user_guide/administrative/app_settings/manage_your_braze_users/teams/), or added to a [permission set]({{site.baseurl}}/user_guide/administrative/app_settings/manage_your_braze_users/user_permissions/#permission-sets).
```

2023-08-31 17:00 UTC, lydia-xie commented on _docs/_user_guide/engagement_tools/canvas/managing_canvases/canvas_approval.md
> +Be sure to check that you have the proper [user permissions]({{site.baseurl}}/user_guide/administrative/manage_your_braze_users/user_permissions/) to approve Canvases.
```suggestion
Be sure to check that you have the proper [user permissions]({{site.baseurl}}/user_guide/administrative/app_settings/manage_your_braze_users/user_permissions/#managing-limited-and-team-role-permissions) to approve Canvases.
```

2023-08-31 17:31 UTC, bre-fitzgerald approved these changes

2023-08-31 17:32 UTC, merged