Create partner.md
braze-inc/braze-docs pull request #5980
Opened 2023-08-16 05:31 UTC by peterwang998

Created partner.md documentation for the Braze Ketch integration

# Pull Request/Issue Resolution

added technical documentation for the Braze and Ketch Integration

2023-08-16 05:33 UTC, peterwang998 commented
@alex-braze @josh-mccrowell-braze Tagging for review. 

Let me know if anything else is needed, and thank you!

2023-08-16 16:29 UTC, alex-braze requested changes
Added some inline comments with some asks for additional details.

2023-08-16 16:29 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/Ketch/partner.md
> +| Braze API key | A Braze REST API key with `users.track, subscription.status.get, subscription.status.set, users.delete, users.alias.new, users.export.ids, email.unsubscribe,`and `email.blacklist` p
Can you provide some details on how these endpoints are used within the integration?

2023-08-16 16:29 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/Ketch/partner.md
> +3. To create a topic, you can click the create new subscription button. Each subscription will have a name and a code, the code will be how each subscription gets referred to when referenced by the A
Does the subscription code correspond to the subscription groups that the customer would be creating in Braze?

- [Braze email subscription groups](https://www.braze.com/docs/user_guide/message_building_by_channel/email/managing_user_subscriptions/#subscription-groups)
- [Braze SMS subscription groups](https://www.braze.com/docs/user_guide/message_building_by_channel/sms/sms_subscription_group/)

2023-08-16 16:29 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/Ketch/partner.md
> +
Braze now supports email address as an identifier when updating the user profile via the [Track User endpoint](https://www.braze.com/docs/api/endpoints/user_data/post_user_track/#example-request-for-updating-a-user-profile-by-email-address). However, this is in early access so any customers who are looking to use this would need to get this feature flipped by their customer success manager.

2023-08-16 18:09 UTC, alex-braze commented
Hi Peter,

Thanks for the clarification.

If you could add in some information on what the different endpoints are
used for, as well as the screenshot of the subscription groups and
re-commit I will review the changes.

Best,
Alexandra


Alex Rees | Alliances Technical Lead | Braze


On Wed, Aug 16, 2023 at 10:10 AM Peter Wang ***@***.***>
wrote:

> 1. Yup, the subscription code is the subscription group code that's found
> in braze.
> [image: Screenshot 2023-08-16 at 10.09.48 AM.png]
>
> 2. We are currently still using the subscription end-point. We were
> discussing this with Alexandra and she recommended we think about moving
> to
> Track User endpoint, so we're on a holding pattern until Braze releases
> that end-point that supports email identifiers. It's a pretty easy
> switch-over on our end, and it shouldn't take additional configurations
> for
> customers once that track.user endpoint is GA'ed on Braze's side.
>
> On Wed, Aug 16, 2023 at 9:29 AM alex-braze ***@***.***> wrote:
>
> > ***@***.**** requested changes on this pull request.
> >
> > Added some inline comments with some asks for additional details.
> > ------------------------------
> >
> > In _docs/_hidden/wip_partnerships/Ketch/partner.md
> > <
> https://github.com/braze-inc/braze-docs/pull/5980#discussion_r1296145732>
> > :
> >
> > > +page_type: reference
> > +layout: dev_guide
> > +---
> > +
> > +# Ketch
> > +
> > +> [Ketch](https://www.ketch.com) enables businesses to be responsible
> stewards of data. We provide simplified privacy operations and complete,
> dynamic data control and intelligence.
> > +
> > +The Ketch partnership with Braze allows you to control customer
> communication preferences within the Ketch preference center to be
> automatically propagated to Braze in order to manage customer communication
> and privacy preferences.
> > +
> > +## Prerequisites
> > +
> > +| Requirements | Description |
> > +|---|---|
> > +| Ketch Account | A [Ketch](https://www.ketch.com) account with admin
> privileges is required activate this integration. |
> > +| Braze API key | A Braze REST API key with `users.track,
> subscription.status.get, subscription.status.set, users.delete,
> users.alias.new, users.export.ids, email.unsubscribe,`and `email.blacklist`
> permissions.<br><br>This can be created within the **Braze Dashboard >
> Developer Console > REST API Key > Create New API Key**. |
> >
> > Can you provide some details on how these endpoints are used within the
> > integration?
> > ------------------------------
> >
> > In _docs/_hidden/wip_partnerships/Ketch/partner.md
> > <
> https://github.com/braze-inc/braze-docs/pull/5980#discussion_r1296151213>
> > :
> >
> > > +The following steps will alllow you to configure and setup your Ketch
> and Braze systems so that Ketch can orchestrate user communications and
> preference signals directly to Braze
> > +
> > +### Step 1: Setup the Braze Connection within Ketch
> > +To get start, log into your [Ketch instance](https://app.ketch.com)
> > +
> > +1. Navigate to **Data Systems**, and search for **Braze**<br><br>
> > +2. Click on the the **Braze** system, and click **New
> Connection**.<br><br>
> > +3. Give your Braze connection an identifiable name, note that a code
> will also be created for that connection, this code should be unique across
> all connections and will be used to refer to this connection in API based
> processes.<br><br>
> > +4. Confirm the identity mapping of the users, by default, we will map
> user identities based off of email addresses for the user, but we can also
> configure it based off of external_id in Braze.<br><br>
> > +5. Next, add in the braze API key you created with the proper
> permissions and then provide the rest API endpoint, note the reset API
> end-point is based on which braze instance your organization is using. You
> can use this document to find your [Braze API end-point](
> https://www.braze.com/docs/api/basics/#endpoints).<br><br>
> > +
> > +
> > +### Step 2: Configuring Subscription Preferences
> > +1. To configure Subscriptions in Ketch, go to **Policy Center >
> Subsriptions**. If you do not see the subscriptions tab under policy
> center, please make sure you have purchased the marketing preference center
> and verify that you have the correct account permissions to access this
> portion of the product.<br><br>
> > +2. The subscriptions tab displays the available subscriptions. Each
> subscription represents a specific marketing category, while the channels
> under each topic represent the medium by which your users will be contacted
> on those topics. There is also the Global Control tab which controls the
> universal opt-outs from your user.<br><br>
> > +3. To create a topic, you can click the create new subscription button.
> Each subscription will have a name and a code, the code will be how each
> subscription gets referred to when referenced by the API. You can also add
> language translations for each of your topics in case this marketing
> preference center is deployed to sites supporting multiple languages. Next,
> you will want to add the channels which you send the subscription topics
> through. For each channel that you enable, that option will show up in the
> marketing preference center for your users.<br><br>
> >
> > Does the subscription code correspond to the subscription groups that
> the
> > customer would be creating in Braze?
> >
> > - Braze email subscription groups
> > <
> https://www.braze.com/docs/user_guide/message_building_by_channel/email/managing_user_subscriptions/#subscription-groups>
>
> > - Braze SMS subscription groups
> > <
> https://www.braze.com/docs/user_guide/message_building_by_channel/sms/sms_subscription_group/>
>
> >
> > ------------------------------
> >
> > In _docs/_hidden/wip_partnerships/Ketch/partner.md
> > <
> https://github.com/braze-inc/braze-docs/pull/5980#discussion_r1296161056>
> > :
> >
> > > +4. Confirm the identity mapping of the users, by default, we will map
> user identities based off of email addresses for the user, but we can also
> configure it based off of external_id in Braze.<br><br>
> > +5. Next, add in the braze API key you created with the proper
> permissions and then provide the rest API endpoint, note the reset API
> end-point is based on which braze instance your organization is using. You
> can use this document to find your [Braze API end-point](
> https://www.braze.com/docs/api/basics/#endpoints).<br><br>
> > +
> > +
> > +### Step 2: Configuring Subscription Preferences
> > +1. To configure Subscriptions in Ketch, go to **Policy Center >
> Subsriptions**. If you do not see the subscriptions tab under policy
> center, please make sure you have purchased the marketing preference center
> and verify that you have the correct account permissions to access this
> portion of the product.<br><br>
> > +2. The subscriptions tab displays the available subscriptions. Each
> subscription represents a specific marketing category, while the channels
> under each topic represent the medium by which your users will be contacted
> on those topics. There is also the Global Control tab which controls the
> universal opt-outs from your user.<br><br>
> > +3. To create a topic, you can click the create new subscription button.
> Each subscription will have a name and a code, the code will be how each
> subscription gets referred to when referenced by the API. You can also add
> language translations for each of your topics in case this marketing
> preference center is deployed to sites supporting multiple languages. Next,
> you will want to add the channels which you send the subscription topics
> through. For each channel that you enable, that option will show up in the
> marketing preference center for your users.<br><br>
> > +4. Under each channel that you enable, you can also add the details of
> how you want the Ketch preference center to orchestrate the signals of that
> particular opt-in or opt-out.<br><br>
> > +5. For the [...]

2023-08-16 18:48 UTC, peterwang998 commented
Would it be better to not explicitly call out the subscriptions vs user
track endpoint since that change is slated to occur soon and it should not
require end-user configuration?

On Wed, Aug 16, 2023 at 11:09 AM alex-braze ***@***.***>
wrote:

> Hi Peter,
>
> Thanks for the clarification.
>
> If you could add in some information on what the different endpoints are
> used for, as well as the screenshot of the subscription groups and
> re-commit I will review the changes.
>
> Best,
> Alexandra
>
>
> Alex Rees | Alliances Technical Lead | Braze
>
>
> On Wed, Aug 16, 2023 at 10:10 AM Peter Wang ***@***.***>
> wrote:
>
> > 1. Yup, the subscription code is the subscription group code that's
> found
> > in braze.
> > [image: Screenshot 2023-08-16 at 10.09.48 AM.png]
> >
> > 2. We are currently still using the subscription end-point. We were
> > discussing this with Alexandra and she recommended we think about moving
> > to
> > Track User endpoint, so we're on a holding pattern until Braze releases
> > that end-point that supports email identifiers. It's a pretty easy
> > switch-over on our end, and it shouldn't take additional configurations
> > for
> > customers once that track.user endpoint is GA'ed on Braze's side.
> >
> > On Wed, Aug 16, 2023 at 9:29 AM alex-braze ***@***.***> wrote:
> >
> > > ***@***.**** requested changes on this pull request.
> > >
> > > Added some inline comments with some asks for additional details.
> > > ------------------------------
> > >
> > > In _docs/_hidden/wip_partnerships/Ketch/partner.md
> > > <
> > https://github.com/braze-inc/braze-docs/pull/5980#discussion_r1296145732>
>
> > > :
> > >
> > > > +page_type: reference
> > > +layout: dev_guide
> > > +---
> > > +
> > > +# Ketch
> > > +
> > > +> [Ketch](https://www.ketch.com) enables businesses to be
> responsible
> > stewards of data. We provide simplified privacy operations and complete,
> > dynamic data control and intelligence.
> > > +
> > > +The Ketch partnership with Braze allows you to control customer
> > communication preferences within the Ketch preference center to be
> > automatically propagated to Braze in order to manage customer
> communication
> > and privacy preferences.
> > > +
> > > +## Prerequisites
> > > +
> > > +| Requirements | Description |
> > > +|---|---|
> > > +| Ketch Account | A [Ketch](https://www.ketch.com) account with
> admin
> > privileges is required activate this integration. |
> > > +| Braze API key | A Braze REST API key with `users.track,
> > subscription.status.get, subscription.status.set, users.delete,
> > users.alias.new, users.export.ids, email.unsubscribe,`and
> `email.blacklist`
> > permissions.<br><br>This can be created within the **Braze Dashboard >
> > Developer Console > REST API Key > Create New API Key**. |
> > >
> > > Can you provide some details on how these endpoints are used within
> the
> > > integration?
> > > ------------------------------
> > >
> > > In _docs/_hidden/wip_partnerships/Ketch/partner.md
> > > <
> > https://github.com/braze-inc/braze-docs/pull/5980#discussion_r1296151213>
>
> > > :
> > >
> > > > +The following steps will alllow you to configure and setup your
> Ketch
> > and Braze systems so that Ketch can orchestrate user communications and
> > preference signals directly to Braze
> > > +
> > > +### Step 1: Setup the Braze Connection within Ketch
> > > +To get start, log into your [Ketch instance](https://app.ketch.com)
> > > +
> > > +1. Navigate to **Data Systems**, and search for **Braze**<br><br>
> > > +2. Click on the the **Braze** system, and click **New
> > Connection**.<br><br>
> > > +3. Give your Braze connection an identifiable name, note that a code
> > will also be created for that connection, this code should be unique
> across
> > all connections and will be used to refer to this connection in API
> based
> > processes.<br><br>
> > > +4. Confirm the identity mapping of the users, by default, we will map
> > user identities based off of email addresses for the user, but we can
> also
> > configure it based off of external_id in Braze.<br><br>
> > > +5. Next, add in the braze API key you created with the proper
> > permissions and then provide the rest API endpoint, note the reset API
> > end-point is based on which braze instance your organization is using.
> You
> > can use this document to find your [Braze API end-point](
> > https://www.braze.com/docs/api/basics/#endpoints).<br><br>
> > > +
> > > +
> > > +### Step 2: Configuring Subscription Preferences
> > > +1. To configure Subscriptions in Ketch, go to **Policy Center >
> > Subsriptions**. If you do not see the subscriptions tab under policy
> > center, please make sure you have purchased the marketing preference
> center
> > and verify that you have the correct account permissions to access this
> > portion of the product.<br><br>
> > > +2. The subscriptions tab displays the available subscriptions. Each
> > subscription represents a specific marketing category, while the
> channels
> > under each topic represent the medium by which your users will be
> contacted
> > on those topics. There is also the Global Control tab which controls the
> > universal opt-outs from your user.<br><br>
> > > +3. To create a topic, you can click the create new subscription
> button.
> > Each subscription will have a name and a code, the code will be how each
> > subscription gets referred to when referenced by the API. You can also
> add
> > language translations for each of your topics in case this marketing
> > preference center is deployed to sites supporting multiple languages.
> Next,
> > you will want to add the channels which you send the subscription topics
> > through. For each channel that you enable, that option will show up in
> the
> > marketing preference center for your users.<br><br>
> > >
> > > Does the subscription code correspond to the subscription groups that
> > the
> > > customer would be creating in Braze?
> > >
> > > - Braze email subscription groups
> > > <
> >
> https://www.braze.com/docs/user_guide/message_building_by_channel/email/managing_user_subscriptions/#subscription-groups>
>
> >
> > > - Braze SMS subscription groups
> > > <
> >
> https://www.braze.com/docs/user_guide/message_building_by_channel/sms/sms_subscription_group/>
>
> >
> > >
> > > ------------------------------
> > >
> > > In _docs/_hidden/wip_partnerships/Ketch/partner.md
> > > <
> > https://github.com/braze-inc/braze-docs/pull/5980#discussion_r1296161056>
>
> > > :
> > >
> > > > +4. Confirm the identity mapping of the users, by default, we will
> map
> > user identities based off of email addresses for the user, but we can
> also
> > configure it based off of external_id in Braze.<br><br>
> > > +5. Next, add in the braze API key you created with the proper
> > permissions and then provide the rest API endpoint, note the reset API
> > end-point is based on which braze instance your organization is using.
> You
> > can use this document to find your [Braze API end-point](
> > https://www.braze.com/docs/api/basics/#endpoints).<br><br>
> > > +
> > > +
> > > +### Step 2: Configuring Subscription Preferences
> > > +1. To configure Subscriptions in Ketch, go to **Policy Center >
> > Subsriptions**. If you do not see the subscriptions tab under policy
> > center, please make sure you have purchased the marketing preference
> center
> > and verify that you have the correct account permissions to access this
> > portion of the product.<br><br>
> > > +2. The subscriptions tab displays the available subscriptions. Each
> > subscription represents a specific marketing category, while the
> channels
> > under each topic represent the medium by which your users will be
> contacted
> > on those topics. There is also the Global Control tab which controls the
> > universal opt-outs from your user.<br><br>
> > > +3. To create a topic, you can click the create new subscription
> button.
> > Each subscription will have a name and a code, the code will be how each
> > subs [...]

2023-08-16 21:16 UTC, alex-braze commented
Assuming that /users/track is only being used for setting/updating a user's
subscription groups I think it would be ok to group those two endpoints
together in any description of how they're being used.


Alex Rees | Alliances Technical Lead | Braze


On Wed, Aug 16, 2023 at 11:48 AM Peter Wang ***@***.***>
wrote:

> Would it be better to not explicitly call out the subscriptions vs user
> track endpoint since that change is slated to occur soon and it should not
> require end-user configuration?
>
> On Wed, Aug 16, 2023 at 11:09 AM alex-braze ***@***.***>
> wrote:
>
> > Hi Peter,
> >
> > Thanks for the clarification.
> >
> > If you could add in some information on what the different endpoints are
> > used for, as well as the screenshot of the subscription groups and
> > re-commit I will review the changes.
> >
> > Best,
> > Alexandra
> >
> >
> > Alex Rees | Alliances Technical Lead | Braze
> >
> >
> > On Wed, Aug 16, 2023 at 10:10 AM Peter Wang ***@***.***>
> > wrote:
> >
> > > 1. Yup, the subscription code is the subscription group code that's
> > found
> > > in braze.
> > > [image: Screenshot 2023-08-16 at 10.09.48 AM.png]
> > >
> > > 2. We are currently still using the subscription end-point. We were
> > > discussing this with Alexandra and she recommended we think about
> moving
> > > to
> > > Track User endpoint, so we're on a holding pattern until Braze
> releases
> > > that end-point that supports email identifiers. It's a pretty easy
> > > switch-over on our end, and it shouldn't take additional
> configurations
> > > for
> > > customers once that track.user endpoint is GA'ed on Braze's side.
> > >
> > > On Wed, Aug 16, 2023 at 9:29 AM alex-braze ***@***.***> wrote:
> > >
> > > > ***@***.**** requested changes on this pull request.
> > > >
> > > > Added some inline comments with some asks for additional details.
> > > > ------------------------------
> > > >
> > > > In _docs/_hidden/wip_partnerships/Ketch/partner.md
> > > > <
> > >
> https://github.com/braze-inc/braze-docs/pull/5980#discussion_r1296145732>
> >
> > > > :
> > > >
> > > > > +page_type: reference
> > > > +layout: dev_guide
> > > > +---
> > > > +
> > > > +# Ketch
> > > > +
> > > > +> [Ketch](https://www.ketch.com) enables businesses to be
> > responsible
> > > stewards of data. We provide simplified privacy operations and
> complete,
> > > dynamic data control and intelligence.
> > > > +
> > > > +The Ketch partnership with Braze allows you to control customer
> > > communication preferences within the Ketch preference center to be
> > > automatically propagated to Braze in order to manage customer
> > communication
> > > and privacy preferences.
> > > > +
> > > > +## Prerequisites
> > > > +
> > > > +| Requirements | Description |
> > > > +|---|---|
> > > > +| Ketch Account | A [Ketch](https://www.ketch.com) account with
> > admin
> > > privileges is required activate this integration. |
> > > > +| Braze API key | A Braze REST API key with `users.track,
> > > subscription.status.get, subscription.status.set, users.delete,
> > > users.alias.new, users.export.ids, email.unsubscribe,`and
> > `email.blacklist`
> > > permissions.<br><br>This can be created within the **Braze Dashboard >
> > > Developer Console > REST API Key > Create New API Key**. |
> > > >
> > > > Can you provide some details on how these endpoints are used within
> > the
> > > > integration?
> > > > ------------------------------
> > > >
> > > > In _docs/_hidden/wip_partnerships/Ketch/partner.md
> > > > <
> > >
> https://github.com/braze-inc/braze-docs/pull/5980#discussion_r1296151213>
> >
> > > > :
> > > >
> > > > > +The following steps will alllow you to configure and setup your
> > Ketch
> > > and Braze systems so that Ketch can orchestrate user communications
> and
> > > preference signals directly to Braze
> > > > +
> > > > +### Step 1: Setup the Braze Connection within Ketch
> > > > +To get start, log into your [Ketch instance](https://app.ketch.com)
>
> > > > +
> > > > +1. Navigate to **Data Systems**, and search for **Braze**<br><br>
> > > > +2. Click on the the **Braze** system, and click **New
> > > Connection**.<br><br>
> > > > +3. Give your Braze connection an identifiable name, note that a
> code
> > > will also be created for that connection, this code should be unique
> > across
> > > all connections and will be used to refer to this connection in API
> > based
> > > processes.<br><br>
> > > > +4. Confirm the identity mapping of the users, by default, we will
> map
> > > user identities based off of email addresses for the user, but we can
> > also
> > > configure it based off of external_id in Braze.<br><br>
> > > > +5. Next, add in the braze API key you created with the proper
> > > permissions and then provide the rest API endpoint, note the reset API
> > > end-point is based on which braze instance your organization is using.
> > You
> > > can use this document to find your [Braze API end-point](
> > > https://www.braze.com/docs/api/basics/#endpoints).<br><br>
> > > > +
> > > > +
> > > > +### Step 2: Configuring Subscription Preferences
> > > > +1. To configure Subscriptions in Ketch, go to **Policy Center >
> > > Subsriptions**. If you do not see the subscriptions tab under policy
> > > center, please make sure you have purchased the marketing preference
> > center
> > > and verify that you have the correct account permissions to access
> this
> > > portion of the product.<br><br>
> > > > +2. The subscriptions tab displays the available subscriptions. Each
> > > subscription represents a specific marketing category, while the
> > channels
> > > under each topic represent the medium by which your users will be
> > contacted
> > > on those topics. There is also the Global Control tab which controls
> the
> > > universal opt-outs from your user.<br><br>
> > > > +3. To create a topic, you can click the create new subscription
> > button.
> > > Each subscription will have a name and a code, the code will be how
> each
> > > subscription gets referred to when referenced by the API. You can also
> > add
> > > language translations for each of your topics in case this marketing
> > > preference center is deployed to sites supporting multiple languages.
> > Next,
> > > you will want to add the channels which you send the subscription
> topics
> > > through. For each channel that you enable, that option will show up in
> > the
> > > marketing preference center for your users.<br><br>
> > > >
> > > > Does the subscription code correspond to the subscription groups
> that
> > > the
> > > > customer would be creating in Braze?
> > > >
> > > > - Braze email subscription groups
> > > > <
> > >
> >
> https://www.braze.com/docs/user_guide/message_building_by_channel/email/managing_user_subscriptions/#subscription-groups>
>
> >
> > >
> > > > - Braze SMS subscription groups
> > > > <
> > >
> >
> https://www.braze.com/docs/user_guide/message_building_by_channel/sms/sms_subscription_group/>
>
> >
> > >
> > > >
> > > > ------------------------------
> > > >
> > > > In _docs/_hidden/wip_partnerships/Ketch/partner.md
> > > > <
> > >
> https://github.com/braze-inc/braze-docs/pull/5980#discussion_r1296161056>
> >
> > > > :
> > > >
> > > > > +4. Confirm the identity mapping of the users, by default, we will
> > map
> > > user identities based off of email addresses for the user, but we can
> > also
> > > configure it based off of external_id in Braze.<br><br>
> > > > +5. Next, add in the braze API key you created with the proper
> > > permissions and then provide the rest API endpoint, note the reset API
> > > end-point is based on which braze instance your organization is using.
> > You
> > > can use this document to find your [Braze API end-point](
> > > https://www.braze.com/docs/api/basics/#endpoints).<br><br>
> > > > +
> > > > +
> > > > +### Step 2: Configuring Subscription Preferences
> > > > +1. To configure Subscriptions in Ketch, go to **Policy Center >
> > > Subsriptions**. If you do not see the subscriptions t [...]

2023-08-17 16:15 UTC, alex-braze approved these changes

2023-08-23 19:47 UTC, josh-mccrowell-braze approved these changes

2023-08-23 19:48 UTC, josh-mccrowell-braze commented
Updated submitted documentation to align with other Braze documentation. Your documentation will be added to the site once we get the go-ahead from our partnership team. Please feel free to reach out if you have any issues. 

Thanks, 

The Braze Documentation Team

2023-08-24 14:05 UTC, merged