OfferFit partner docs
braze-inc/braze-docs pull request #6013
Opened 2023-08-21 22:57 UTC by rachel-feinberg

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

2023-08-21 23:09 UTC, rachel-feinberg commented
Original PR and draft are located [here](https://github.com/braze-inc/braze-docs/pull/5966).

2023-08-21 23:22 UTC, bre-fitzgerald requested changes
Left some comments and suggestions for your review! Thanks for taking this on 💪

2023-08-21 23:22 UTC, bre-fitzgerald commented on _docs/_hidden/wip_partnerships/offerfit.md
> +After OfferFit is configured, the automated experimentation platform will automatically send 1:1 personalized activation events to Braze for each user in your target audience. These activation events
That's a pretty long anchor link, I'd recommend adding a custom one to shorten it.

```suggestion
After OfferFit is configured, the automated experimentation platform will automatically send 1:1 personalized activation events to Braze for each user in your target audience. These activation events will be triggered through the Braze campaigns or Canvases you configured in [step 2](#step-2).
```

2023-08-21 23:22 UTC, bre-fitzgerald commented on _docs/_hidden/wip_partnerships/offerfit.md
> +### Step 2: Configure an API-triggered Braze campaign or Canvas and create campaign assets (e.g., HTML templates, images)
Adds custom anchor link

```suggestion
### Step 2: Configure an API-triggered Braze campaign or Canvas and create campaign assets (e.g., HTML templates, images) {#step-2}
```

2023-08-21 23:22 UTC, bre-fitzgerald commented on _docs/_hidden/wip_partnerships/offerfit.md
> +[OfferFit](https://www.offerfit.ai/) is a self-learning platform that automates the experimentation process that is traditionally done through A/B testing. This allows you to automatically discover t
Formatting adjustment per partner docs template

```suggestion
> [OfferFit](https://www.offerfit.ai/) is a self-learning platform that automates the experimentation process that is traditionally done through A/B testing. 

The OfferFit and Braze integration allows you to automatically discover the right message, channel, and timing for every customer based on your customer data. You can optimize your campaigns to existing identified customers, with business goals such as cross-sell, upsell, repurchase, retention, renewal, referral, and winback.
```

2023-08-21 23:22 UTC, bre-fitzgerald commented on _docs/_hidden/wip_partnerships/offerfit.md
> +{% endalert %}
This note doesn't seem to be in the right place. I'd bump this up to directly after the prerequisites table, as it's referring to the third row item.

2023-08-21 23:22 UTC, bre-fitzgerald commented on _docs/_hidden/wip_partnerships/offerfit.md
> +Finally, depending on your dimensions, you can configure Liquid tags in your creative content to dynamically populate your campaign or Canvas with OfferFit recommendations. OfferFit will pass custome
I think we can make this little bit into an actual numbered list for it to be more digestible. Also, I'd recommend linking out to the documentation on control groups so the reader knows we mean regular control groups and aren't talking about the Global Control Group. Control groups are not selected by default (it's a checkbox in the A/B testing panel) so it doesn't quite make sense to say disable or turn off.

```suggestion
1. Create a campaign or Canvas in Braze. OfferFit will use this campaign or Canvas to send 1:1 personalized activation events to the right users from your defined audience. 
2. Do not include a Braze [control group]({{site.baseurl}}/user_guide/engagement_tools/testing/multivariant_testing/create_multivariate_campaign#including-a-control-group) in your campaign or Canvas. This allows the OfferFit control group to be the only active one.
3. Depending on your dimensions, you can configure Liquid tags in your creative content to dynamically populate your campaign or Canvas with OfferFit recommendations. OfferFit will pass customer-specific content to the Liquid tags in your templates via the Braze API.
```

2023-08-24 19:01 UTC, bre-fitzgerald approved these changes
lgtm!

2023-08-24 19:02 UTC, merged