Simon Data - Partner Docs
braze-inc/braze-docs pull request #6028
Opened 2023-08-23 20:24 UTC by cheyennaduggan

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @bre-fitzgerald for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

2023-08-23 21:06 UTC, alex-braze requested changes
@cheyennaduggan just added some inline comments but overall looks good! :)

2023-08-23 21:06 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/simon_data/simondata.md
> +Traits and Contact Properties will re-sync every time the pipe refreshes, based on your selections here. If you don't choose any traits, Simon sends all the data points by default.
The note here: https://github.com/braze-inc/braze-docs/pull/6028/commits/da939fcee3d82bb13fe9b86c6772ee2e69268542#diff-f03d22e39200f7a38bcf94833fdcd86a825c118c6af2fa733e48f57d8c6772f7R41-R43 states that only those data points that have changed will be synced but this section seems to indicate that the traits chosen will be re-synced every time the pipe refreshes. Does this means that if I have chosen "email" as a trait that it will be re-synced each time the pipe refreshes regardless whether the value has changed?

2023-08-23 21:06 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/simon_data/simondata.md
> +- **Trigger a Braze Canvas**: trigger a Braze canvas that leverages your Simon segment data.
It notes here that the integration can trigger a canvas or send a braze campaign but the only endpoint permission shown in the requirements section is for users.track. Are there other endpoints being used for triggering messages  and if so, can we add these to the requirements section?

2023-08-24 15:43 UTC, cheyennaduggan commented
@alex-braze thanks! We also use these endpoints: /canvas/trigger/schedule/create & /canvas/trigger/send
and
/campaign/trigger/schedule/create & /campaign/trigger/send

Can you tell me what permissions to include for those two?

2023-08-24 22:03 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/simon_data/simondata.md
> +- **Trigger a Braze Canvas**: trigger a Braze canvas that leverages your Simon segment data.
certainly! **campaigns.trigger.schedule.create** and **campaigns.trigger.send**

2023-08-24 23:44 UTC, cheyennaduggan commented on _docs/_hidden/wip_partnerships/simon_data/simondata.md
> +- **Trigger a Braze Canvas**: trigger a Braze canvas that leverages your Simon segment data.
Thanks! I'll add those and resubmit.

2023-08-24 23:49 UTC, cheyennaduggan commented
I revised the file for the two comments. Let me know if I should do anything else. Thanks!

2023-08-25 18:54 UTC, alex-braze approved these changes

2023-08-25 19:25 UTC, cheyennaduggan commented
I updated that note one more time.

2023-08-25 19:43 UTC, alex-braze approved these changes
Amazing, thank you!

2023-08-25 23:02 UTC, rachel-feinberg commented on _docs/_partners/data_and_infrastructure_agility/customer_data_platform/simondata.md
> +| Braze Dashboard URL | [Your REST endpoint URL][1]. Your endpoint will depend on the Braze URL for your instance.                                                                                |
```suggestion
| Braze Dashboard URL | [Your REST endpoint URL][1]. Your endpoint will depend on the Braze URL for your instance.                                                                                |
```
This links to the Simon Data homepage. 

[1]: https://www.simondata.com

2023-08-25 23:05 UTC, rachel-feinberg commented on _docs/_partners/data_and_infrastructure_agility/customer_data_platform/simondata.md
> +[1]: https://www.simondata.com
```suggestion
[1]: https://www.braze.com/docs/api/basics/#endpoints
```

2023-08-25 23:06 UTC, bre-fitzgerald commented on _docs/_partners/data_and_infrastructure_agility/customer_data_platform/simondata.md
> +| Braze Dashboard URL | [Your REST endpoint URL][1]. Your endpoint will depend on the Braze URL for your instance.                                                                                |
Ah good catch, this should be [3]. Will update.

2023-08-25 23:06 UTC, bre-fitzgerald commented on _docs/_partners/data_and_infrastructure_agility/customer_data_platform/simondata.md
> +| Braze Dashboard URL | [Your REST endpoint URL][1]. Your endpoint will depend on the Braze URL for your instance.                                                                                |
```suggestion
| Braze Dashboard URL | [Your REST endpoint URL][3]. Your endpoint will depend on the Braze URL for your instance.                                                                                |
```

2023-08-25 23:10 UTC, rachel-feinberg approved these changes
Lgtm!

2023-08-25 23:10 UTC, merged