Redpoint - Partner Docs
braze-inc/braze-docs pull request #6052
Opened 2023-08-29 14:56 UTC by mkredpoint

# Pull Request/Issue Resolution

#### Description of Change:
Redpoint Global, Inc - adding partner docs

Alex Wiseman <alex.wiseman@braze.com>

2023-08-29 16:50 UTC, alex-braze requested changes
@mkredpoint thanks for submitting! 

Two questions/requests:

- Can you add in what specific permissions the Braze API key will need? It looks like this would just be the users.track permission?
- Can you confirm, and add in any relevant information on how customers can set up their syncs to make sure only changed values are being sent to Braze in order to be data point conscious?

2023-08-29 17:32 UTC, mkredpoint commented
@alex-braze - thanks! I added the additions you suggested. Let me know if anything else is required.

2023-08-29 17:37 UTC, alex-braze approved these changes

2023-08-31 18:49 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/customer_data_platform/redpoint.md
> +Redpoint provides two modes for passing data to Braze:
```suggestion
The Braze and Redpoint integration allows you to create Braze segments based on your Redpoint CDP data. Redpoint provides two modes for passing data to Braze: 
```

2023-08-31 18:52 UTC, lydia-xie approved these changes

2023-08-31 18:52 UTC, merged