BD-2366: Data transformation GA
braze-inc/braze-docs pull request #6065
Opened 2023-08-29 23:44 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [X] Yes (**September 1, 2023**)
- [ ] No

---

2023-09-01 18:40 UTC, lydia-xie commented on _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
> +> Braze Data Transformation allows you to build and manage webhook integrations to automate data flow from external platforms into Braze user profiles. This integrated user data can then power even m
```suggestion
> Braze Data Transformation enables you to build and manage webhook integrations to automate data flow from external platforms into Braze user profiles. This integrated user data can then power even more sophisticated marketing use cases.
```

2023-09-01 19:04 UTC, lydia-xie commented on _docs/_user_guide/data_and_analytics/data_transformation/overview.md
> +Webhooks are real-time notifications sent via an HTTP POST request to a specific destination. Webhooks are often used to send data from one point to another, in which the webhook can pass through dat
```suggestion
Webhooks are real-time notifications sent via an HTTP POST request to a specific destination. Webhooks are often used to send data from one point to another, in which the webhook can pass through data about an action that has occurred and who was involved in that action.
```

2023-09-05 17:37 UTC, bre-fitzgerald requested changes
@lydia-xie looks good! Just left a few minor suggestions and comments for your review.

2023-09-05 17:37 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/data_transformation/overview.md
> +## Frequently asked questions
Can we pull these FAQs out of the details dropdowns? We typically use headers for these now afaik

2023-09-05 17:37 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
> +| 2FA or SSO | You must have 2FA or SSO enabled for your account. |
```suggestion
| Two-factor authentication or SSO | You must have [two-factor authentication]({{site.baseurl}}/user_guide/administrative/app_settings/company_settings/security_settings/#two-factor-authentication) (2FA) or [single sign-on]({{site.baseurl}}/user_guide/administrative/app_settings/company_settings/security_settings/#single-sign-on-sso-authentication) (SSO) enabled for your account. |
```

2023-09-05 17:37 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
> +    ```
Adding blank space after code block

```suggestion
    ```

```

2023-09-05 17:37 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
> +6. Click **Validate** to return a preview of your code’s output and to check if it is an acceptable `/users/track` request.
Formatting consistency

```suggestion
6. Click **Validate** to return a preview of your code’s output and to check if it is an acceptable `/users/track` request.<br><br>
```

2023-09-05 17:37 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
> +Accepting email as an identifier is possible as Braze Data Transformation early access users will also be granted early access to this new `/users/track` feature to update a user profile by email add
```suggestion
Accepting email as an identifier is possible as Braze Data Transformation early access users will also be granted early access to this new `/users/track` feature to update a user profile by email address.<br><br>Early access users of Braze Data Transformation who started before April 2023 may be familiar with a `get_user_by_email` function that helped with this use case. That function is deprecated.
```

2023-09-05 17:37 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
> +- Transformation code is accepted in the JavaScript programming language. Any standard JavaScript control flow, such as if/else logic is supported.
```suggestion
- Transformation code is accepted in the JavaScript programming language. Any standard JavaScript control flow, such as if/else logic, is supported.
```

2023-09-05 17:37 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
> +- Click **Validate** to return a preview of your code’s output and to check if it's an acceptable `/users/track` request.
This doesn't seem to apply to the same level of detail as the rest of the bullets. Suggest removing from the list and just add as a sentence after.
```suggestion

Click **Validate** to return a preview of your code’s output and to check if it's an acceptable `/users/track` request.
```

2023-09-05 17:37 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
> +**Deliveries:** After receiving incoming requests, Data Transformation applies your transformation code to create a Braze `/users/track` request.
Bullets here for readability? 🤔 

```suggestion
- **Incoming Requests:** This is the number of webhooks received at this transformation’s URL. If incoming requests are 0, your source platform hasn’t sent over any webhooks, or the connection cannot be made.
- **Deliveries:** After receiving incoming requests, Data Transformation applies your transformation code to create a Braze `/users/track` request.
```

2023-09-05 17:37 UTC, bre-fitzgerald commented on _docs/_user_guide/data_and_analytics/data_transformation/creating_a_transformation.md
> +- If deliveries are 0, check your transformation code to ensure there are no syntax errors and that it compiles. Then, check whether the output is a valid `/users/track` request.
Perhaps add a troubleshooting header before this bulleted list? Up to you

```suggestion
### Troubleshooting

- If deliveries are 0, check your transformation code to ensure there are no syntax errors and that it compiles. Then, check whether the output is a valid `/users/track` request.
```

2023-09-05 17:50 UTC, lydia-xie commented on _docs/_user_guide/data_and_analytics/data_transformation/overview.md
> +## Frequently asked questions
Done!

2023-09-05 17:59 UTC, bre-fitzgerald approved these changes

2023-09-05 17:59 UTC, merged