BD-2057 pt2: Clarify only HTML IAMs don't need special libraries
braze-inc/braze-docs pull request #6118
Opened 2023-09-11 16:55 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-2057**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2023-09-11 16:58 UTC, bre-fitzgerald commented
Related to #5266

2023-09-11 16:58 UTC, davidbielik commented on _includes/archive/android/gifs.md
> +Braze supports displaying animated GIFs and SVG images by default for HTML in-app messages. A custom image library is not required, but it is supported.
```suggestion
Braze supports displaying animated GIFs and SVG images by default for HTML in-app messages. A custom image library is not required, but it is supported.

For non custom HTML in-app messages, you must follow the guide below.
```

2023-09-11 17:14 UTC, bryanlogan commented on _includes/archive/android/gifs.md
> +Braze supports displaying animated GIFs and SVG images by default for HTML in-app messages. A custom image library is not required, but it is supported.
Instead of "For non custom HMTL", can we just say "For non-HTML in-app messages"?  It removes confusion if people are using a template, etc.

2023-09-12 14:05 UTC, bryanlogan commented on _includes/archive/android/gifs.md
> +Braze supports displaying animated GIFs and SVG images by default for HTML in-app messages. A custom image library is not required, but it is supported.
```suggestion
Braze supports displaying animated GIFs and SVG images by default for HTML in-app messages. A custom image library is required when using non-HTML in-app messages.
```

2023-09-12 14:08 UTC, bryanlogan requested changes
We can't say a custom library is not required, because in certain cases (non-HTML messages), it is required.

2023-09-12 15:57 UTC, bryanlogan approved these changes

2023-09-12 16:00 UTC, lydia-xie approved these changes

2023-09-12 16:00 UTC, merged