BD-2399 Amperity overhaul
braze-inc/braze-docs pull request #6130
Opened 2023-09-13 18:03 UTC by rachel-feinberg

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #BD-2399

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

2023-10-18 17:33 UTC, lydia-xie requested changes
looks great! flagged a few things for your review :) mostly style related

2023-10-18 17:33 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
> +| Braze REST API key | A Braze REST API key with `users.track` permissions. <br> This can be created within the Braze Dashboard by navigating to **Developer Console** > **Rest API Key** > **Create Ne
```suggestion
| Braze REST API key | A Braze REST API key with `users.track` permissions. <br> This can be created in the Braze dashboard by navigating to **Developer Console** > **Rest API Key** > **Create New API Key**. |
```

2023-10-18 17:33 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
> +| Braze instance | Your Braze instance can be obtained from your Braze onboarding manager, or be found on the [API overview page]({{site.baseurl}}/api/basics#endpoints). |
```suggestion
| Braze instance | Your Braze instance can be obtained from your Braze onboarding manager or be found on the [API overview page]({{site.baseurl}}/api/basics#endpoints). |
```

2023-10-18 17:33 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
> +Amp360 users can use SQL to write free-form queries, and then configure a schedule that sends the results to Braze.
```suggestion
Amp360 users can use SQL to write free-form queries and then configure a schedule that sends the results to Braze.
```

2023-10-18 17:33 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/customer_data_platform/amperity.md
> +Navigate to the query function in Amperity and construct a SQL query that will yield the desired set of customer data. The results should include the specific attributes you want to send to Braze. Se
```suggestion
Navigate to the query function in Amperity and construct an SQL query that will yield the desired set of customer data. The results should include the specific attributes you want to send to Braze. See this example of Amperity query for returning a list of users with their purchase histories.
```
"See this example of..." 🤔

2023-10-18 17:51 UTC, lydia-xie approved these changes
lgtm! marking as approved and gonna let @bre-fitzgerald look over the PR :)

2023-10-19 16:28 UTC, bre-fitzgerald approved these changes
lgtm!

2023-10-19 16:28 UTC, merged