BD-2428 Add Permissions Sets info to SCIM docs
braze-inc/braze-docs pull request #6152
Opened 2023-09-15 18:20 UTC by rachel-feinberg

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #BD-2428

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

2023-09-15 18:41 UTC, bre-fitzgerald requested changes
Hey @rachel-feinberg, left some comments for your review! LMK if you have any questions

2023-09-15 18:41 UTC, bre-fitzgerald commented on _docs/_hidden/misc_reference/scim_api_appendix.md
> +{: .reset-td-br-1 .reset-td-br-2 .reset-td-br-3  .reset-td-br-4}
I believe this should be updating the existing "Team permissions object" section directly below it

2023-09-15 18:41 UTC, bre-fitzgerald commented on _docs/_hidden/misc_reference/scim_api_appendix.md
I think this doc is missing a number of updates. I would comment contextually but GitHub won't let me comment where there wasn't an edit.

1. `## Permissions object` - This section is missing updates for the description column, (and the column has a typo)
2. `### App group permissions object` - It looks like they want to call this a "Workspace permissions object". Because the keys still use appGroup, it might be worthwhile to note that app groups have been renamed in Braze to workspaces, although the keys here still reference the old terminology.
3.  The addition you included for the "Workspace permissions set object" should probably also have a header for consistency

I'd also do a quick check for typos and broken links in this doc (there's an anchor link at the top that wasn't working for me), and—if you haven't already—run these edits by the PM before we merge since they're a little complex.

2023-09-15 19:17 UTC, rachel-feinberg commented on _docs/_hidden/misc_reference/scim_api_appendix.md
Do you recall how many updates in the description column you noted? I found two

2023-09-18 22:56 UTC, bre-fitzgerald approved these changes
Looks great! 🙌

2023-09-18 22:56 UTC, merged