Cohort Import restructuring
braze-inc/braze-docs pull request #6288
Opened 2023-10-06 23:01 UTC by rachel-feinberg

# Pull Request/Issue Resolution

#### Description of Change:
> I'm converting the Cohort Import redirects into actual articles

Closes #NONE

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

2023-10-11 17:11 UTC, lydia-xie requested changes
lgtm! just flagged a few style things for your review!

2023-10-11 17:11 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
> +In Mixpanel, navigate to **Data Management > Cohorts.** Select the cohort to send to Braze and then select **Export to Braze**. Lastly, select a one-time sync or dynamic sync. Selecting dynamic sync
```suggestion
In Mixpanel, navigate to **Data Management > Cohorts**. Select the cohort to send to Braze and then select **Export to Braze**. Lastly, select a one-time sync or dynamic sync. Selecting dynamic sync will sync your Braze cohort every 15 minutes to match users in Mixpanel. 
```

2023-10-11 17:11 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/cohort_import/mixpanel.md
> +Once saved, you can reference this segment during Canvas or campaign creation in the targeting users step.
```suggestion
After saving, you can reference this segment during Canvas or campaign creation in the targeting users step.
```

2023-10-11 17:11 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
> +Once saved, you can reference this segment during Canvas or campaign creation in the targeting users step.
```suggestion
After saving, you can reference this segment during Canvas or campaign creation in the targeting users step.
```

2023-10-11 17:11 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/cohort_import/amplitude.md
> +In Amplitude, navigate to **Sources & Destinations > [project name] > Destinations > Braze**. In the prompt that appears, provide the Braze data import key and REST endpoint, and click **Save**.
```suggestion
In Amplitude, navigate to **Sources & Destinations** > **[project name]** > **Destinations** > **Braze**. In the prompt that appears, provide the Braze data import key and REST endpoint, and click **Save**.
```

2023-10-11 17:21 UTC, lydia-xie approved these changes
Small note that there are some small inconsistencies when we call out "cohort import" in the article title:
- Heap
- Amplitude cohort import
- AppsFlyer Audiences
- Hightouch cohort import
- Kubit cohort import
- Mixpanel cohort import
- Tinyclues

Otherwise, lgtm 👍

2023-10-11 17:39 UTC, rachel-feinberg commented
> Small note that there are some small inconsistencies when we call out "cohort import" in the article title:
> 
> * Heap
> * Amplitude cohort import
> * AppsFlyer Audiences
> * Hightouch cohort import
> * Kubit cohort import
> * Mixpanel cohort import
> * Tinyclues
> 
> Otherwise, lgtm 👍 Approving and letting Bre + Alex take a look at the PR :)

Ah yeah, so Heap and Tinyclues only reside in Cohort Import, so I didn't use the "cohort import" naming convention. Most of those with "cohort import" in their article titles have "main" articles in other sections. (Amplitude's main article is in Analytics, Hightouch's main article is in Workflow Automation, etc.)  

AppsFlyer has a specific name for cohort import (AppsFlyer Audiences), so I used that in the navigation header and article title.

2023-10-11 18:10 UTC, bre-fitzgerald commented
@rachel-feinberg I think your approach with the naming makes sense to me. One other piece of feedback I have is how we interlink these with their "main" articles.

I think we might be able to simplify the cohort import-specific articles to make the relationship between the two clearer. What are your thoughts on cutting away some of the descriptive text at the top, and only stating that this article is for cohort import. Something like this? (excuse the squiggles, I did this with design mode)
![2023-10-11_11-07-58](https://github.com/braze-inc/braze-docs/assets/82903296/8eb2b60f-44b8-426c-b251-b3a345abd8a1)

I like the way you've phrased linking out to the cohort import articles though, that seems very clear. 👍 

cc: @lydia-xie

2023-10-11 18:50 UTC, rachel-feinberg commented
> @rachel-feinberg I think your approach with the naming makes sense to me. One other piece of feedback I have is how we interlink these with their "main" articles.
> 
> I think we might be able to simplify the cohort import-specific articles to make the relationship between the two clearer. What are your thoughts on cutting away some of the descriptive text at the top, and only stating that this article is for cohort import. Something like this? (excuse the squiggles, I did this with design mode) ![2023-10-11_11-07-58](https://user-images.githubusercontent.com/82903296/274375814-8eb2b60f-44b8-426c-b251-b3a345abd8a1.png)
> 
> I like the way you've phrased linking out to the cohort import articles though, that seems very clear. 👍
> 
> cc: @lydia-xie

Yes! This is so much cleaner. I'll implement this

2023-10-12 16:24 UTC, bre-fitzgerald approved these changes
Lgtm! Thanks for all your hard work on this 💪 🎉

2023-10-12 21:10 UTC, alex-braze approved these changes
Looks amazing!! :)

2023-10-12 21:15 UTC, merged