BD-2561: Personalized Paths beta [MERGE 11/7]
braze-inc/braze-docs pull request #6446
Opened 2023-10-31 22:55 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
Adds new doc for Personalized Paths in Experiment Steps

Closes #**BD-2561**

#### Is this change associated with a Braze feature/product release?
- [x] Yes (**November 7**)
- [ ] No

2023-11-01 17:37 UTC, borisrev requested changes
Minor tweaks otherwise lgtm

2023-11-01 17:37 UTC, borisrev commented on _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
> +Then set the **Experiment Window**. The **Experiment Window** determines how long users will be sent down all paths before choosing a single winning path for all subsequent users. The window begins w
before choosing "the best paths for each user in the delay group."

2023-11-01 17:37 UTC, borisrev commented on _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
> +When the experiment window passes and the experiment is complete, Braze will send users in the delay group to their respective paths.
optional: "to their respective paths with the highest personalized likelihood of conversion."

2023-11-01 17:38 UTC, borisrev commented on _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
> +> Personalized Paths is similar to [Personalized Variant]({{site.baseurl}}/user_guide/engagement_tools/testing/multivariant_testing/optimizations/#personalized-variant) in campaigns and lets you auto
"in campaigns and lets you personalize entire journeys for individual users based on conversion likelihood."

2023-11-01 18:36 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
> +> Personalized Paths is similar to [Personalized Variant]({{site.baseurl}}/user_guide/engagement_tools/testing/multivariant_testing/optimizations/#personalized-variant) in campaigns and lets you auto
```suggestion
> Personalized Paths is similar to [Personalized Variant]({{site.baseurl}}/user_guide/engagement_tools/testing/multivariant_testing/optimizations/#personalized-variant) in campaigns and lets you personalize entire Canvas journeys for individual users based on conversion likelihood.
```

2023-11-01 18:37 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
> +Then set the **Experiment Window**. The **Experiment Window** determines how long users will be sent down all paths before choosing a single winning path for all subsequent users. The window begins w
```suggestion
Then set the **Experiment Window**. The **Experiment Window** determines how long users will be sent down all paths before choosing the best path for each user in the delay group. The window begins when the first user enters the step.
```

2023-11-01 18:38 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
> +When the experiment window passes and the experiment is complete, Braze will send users in the delay group to their respective paths.
```suggestion
When the experiment window passes and the experiment is complete, Braze will send users in the delay group to their respective paths with the highest personalized likelihood of conversion.
```

2023-11-01 21:11 UTC, borisrev approved these changes

2023-11-03 17:33 UTC, bre-fitzgerald commented on _docs/_user_guide/engagement_tools/canvas/canvas_components/experiment_step/personalized_paths.md
> +description: "Personalized Paths is similar to Personalized Variant in campaigns and lets you automate your A/B tests."
```suggestion
description: "Personalized Paths is similar to Personalized Variant in campaigns and lets you personalize entire Canvas journeys based on each person's conversion likelihood."
```

2023-11-06 17:10 UTC, merged