BD-2557: Typeform Partner Documentation
braze-inc/braze-docs pull request #6450
Opened 2023-11-01 22:21 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
Adds Typeform partner docs 

To do:
- [ ] Update includes to add if statement for Typeform
- [ ] Add images
- [ ] Add parent page links 

Closes #**BD-2557**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2023-11-07 23:18 UTC, alex-braze reviewed
Two quick ones otherwise it looks good!

2023-11-07 23:18 UTC, alex-braze commented on _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
> +1. Send a request to your Data Transformation URL with a sample event payload of an Typeform event you intend to support. See [request body format](#request-body-format) for help formatting your requ
Since we have instructed the customer to send a test event from the Typeform webhook we can probably remove step 1.

2023-11-07 23:18 UTC, alex-braze commented on _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
> +2. Refresh your Data Transformation and make sure you can see the sample event payload in the **Webhook Details**.
We might want to set this as step 1 and change out "sample event payload" with "Typeform test payload"

2023-11-08 23:42 UTC, lydia-xie requested changes
lgtm! just some suggestions for your review!

2023-11-08 23:42 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
> +By integrating Typeform and Braze, you can:
```suggestion
By integrating Braze and Typeform, you can:
```

2023-11-08 23:42 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
> +- Trigger messaging in Braze based on a user’s engagement with a Typeform
```suggestion
- Trigger messaging in Braze based on a user’s engagement with Typeform
```
?

2023-11-08 23:42 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
> +The following are example templates built using our [example Typeform webhook payload](#example-typeform-webhook-payload). These templates can be used as a starting point. Feel free to start from scr
```suggestion
The following are example templates built using our [example Typeform webhook payload](#example-typeform-webhook-payload). These templates can be used as a starting point. You can start from scratch or delete specific components as you see fit.
```

2023-11-08 23:42 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
> +In this example template we are using an email address, captured from an email address question within the typeform, as the identifier.
```suggestion
In this example template, we are using an email address (captured from an email address question within the Typeform) as the identifier.
```
?

2023-11-08 23:42 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
> +If you intend to use email address as an identifier, please review our [frequently asked questions]({{site.baseurl}}/api/endpoints/user_data/post_user_track#frequently-asked-questions) for the `/user
```suggestion
If you intend to use an email address as an identifier, review our [frequently asked questions]({{site.baseurl}}/api/endpoints/user_data/post_user_track#frequently-asked-questions) for the `/users/track` endpoint for more information on expected behavior.
```

2023-11-08 23:47 UTC, bre-fitzgerald commented on _docs/_partners/message_orchestration/channel_extensions/surveys/typeform.md
> +- Trigger messaging in Braze based on a user’s engagement with a Typeform
uhh sorta, yes! Typeform is the name of their forms too. So I suppose here it should be "with a typeform" lowercase—good catch

2023-11-08 23:50 UTC, lydia-xie approved these changes

2023-11-09 00:30 UTC, merged