Partnership Name - Partner Docs
braze-inc/braze-docs pull request #6490
Opened 2023-11-09 21:05 UTC by Patrick-Duvall

# Pull Request/Issue Resolution

#### Description of Change:
> Add initial Recurly Partner docs

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @bre-fitzgerald for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

2023-11-09 21:08 UTC, Patrick-Duvall commented on _docs/_hidden/wip_partnerships/recurly/partner.md
> +---
Tagging @josh-mccrowell-braze @alex-braze pr documentation.

2023-11-13 20:37 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/recurly/partner.md
> +Details around using Recurly with Braze can be found [HERE](https://docs.recurly.com/docs/braze-integration)
@Patrick-Duvall - when I click into the link it takes me to an empty page. Do customers need to be signed in to see the docs?

Would it be possible to add in some basics to the Braze doc, for example:
- Supported events
- Supported identifiers
- Brief note on rate-limiting/batching

2023-11-13 20:37 UTC, alex-braze requested changes
@Patrick-Duvall added in a comment!

2023-11-14 15:23 UTC, Patrick-Duvall commented on _docs/_hidden/wip_partnerships/recurly/partner.md
> +Details around using Recurly with Braze can be found [HERE](https://docs.recurly.com/docs/braze-integration)
That document is owned/managed by product and is not done yet. We're likely adding a few more events, and are still building out the account attributes. I can document things as are currently, with the understanding as we do additional releases we'll need to make more PR's.

2023-11-15 17:48 UTC, Patrick-Duvall commented on _docs/_hidden/wip_partnerships/recurly/partner.md
> +### Supported Identifiers
@alex-braze Here are the changes/additions to the docs you suggested.

2023-11-15 18:16 UTC, alex-braze approved these changes

2023-11-15 20:59 UTC, josh-mccrowell-braze commented
Thanks for your submission, @Patrick-Duvall ! This is set to be merged during our release on 11/21.

2023-11-15 21:20 UTC, bre-fitzgerald requested changes
@josh-mccrowell-braze a couple of comments for your review! Also as a note, the partner tile also needs to be added to the partners home page (/docs/partners/home)

2023-11-15 21:20 UTC, bre-fitzgerald commented on _docs/_partners/data_and_infrastructure_agility/payments/recurly.md
> +Because Recurly uses your API key configured with Braze, the integration is subject to standard Braze rate limits of 20000 requests per minute.
Additionally the statement "Because Recurly uses your API key configured with Braze" should likely instead say something like "Because Recurly uses the Braze `/users/track` endpoint..."

2023-11-15 21:38 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/payments/recurly.md
> +Because Recurly uses your API key configured with Braze, the integration is subject to standard Braze rate limits of 20000 requests per minute.
Oops, good catch.

2023-11-15 21:47 UTC, josh-mccrowell-braze commented
@bre-fitzgerald : Good catches as always. 

* Resolved your comments and fixed the rate limit/API batching section. 
* Added Recurly to partners home page

Assuming these fixes look good, this is ready to merge on 11/21.

2023-11-21 15:13 UTC, josh-mccrowell-braze approved these changes

2023-11-21 16:16 UTC, bre-fitzgerald commented on _docs/_partners/data_and_infrastructure_agility/payments/recurly.md
> +### Batching and Rate Limiting
```suggestion
### Batching and rate limiting
```

2023-11-21 16:17 UTC, bre-fitzgerald commented on _docs/_partners/data_and_infrastructure_agility/payments/recurly.md
> +Remember to copy the URL of your Braze instance. For instance, your URL might look like:
```suggestion
Remember to copy the URL of your Braze instance. For example, your URL might look like: 
```

2023-11-21 16:17 UTC, bre-fitzgerald approved these changes

2023-11-21 16:17 UTC, merged