Meta Lead Ads via Zapier documentation
braze-inc/braze-docs pull request #6525
Opened 2023-11-16 00:14 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-2582**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2023-11-17 00:27 UTC, dkim32 requested changes
overall lgtm. minor updates and wondering if we should include a code snippet for customers to copy/paste for the webhook payload.

2023-11-17 00:27 UTC, dkim32 commented on _docs/_partners/data_and_infrastructure_agility/analytics/meta.md
> +| Zapier account | A Zapier account is required to take advantage of this partnership. This integration requires isomg [premium Zapier apps](https://zapier.com/app/pricing), so check that your Zapier
Type: "isomg"

2023-11-17 00:27 UTC, dkim32 commented on _docs/_partners/data_and_infrastructure_agility/analytics/meta.md
> +| Facebook Business Manager | A centralized tool to manage your brand’s Facebook assets (for example, ad accounts, pages, apps). |
I don't know if we wanted to include, but there are hyperlinks to each Facebook requirement that leads to a Facebook help article: https://docs.google.com/document/d/1DWPhOGbwfzFy60ax5Rgp51v3WoKBSW9_6mKj45u96b4/edit#bookmark=id.y0hl0sh4gvts

2023-11-17 00:27 UTC, dkim32 commented on _docs/_partners/data_and_infrastructure_agility/analytics/meta.md
> +| URL | Your Braze REST endpoint to `/users/track`. An example is `https://rest.iad-06.braze.com/users/track`. |
Although not grammatically correct, I would recommend removing the "." after the users/track URL. 

I could foresee customers copying/pasting that.

2023-11-17 00:27 UTC, dkim32 commented on _docs/_partners/data_and_infrastructure_agility/analytics/meta.md
> +{: .reset-td-br-1 .reset-td-br-2}
Should we provide a code snippet here so it's easier for customers to copy/paste?

2023-11-17 00:27 UTC, dkim32 commented on _docs/_partners/data_and_infrastructure_agility/analytics/meta.md
> +## Troubleshooting
not that urgent but i wonder if we can make these sections collapsable similar to the troubleshooting in audience sync: https://braze-docs-7hhkv2une-braze.vercel.app/docs/partners/canvas_steps/tiktok_audience_sync/#troubleshooting

if it's too much effort don't worry about it.

2023-11-17 18:56 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/analytics/meta.md
> +{: .reset-td-br-1 .reset-td-br-2}
I added a code snippet and cleaned up some of the preceding text to match other Partner docs 👍  Also removed the code example image, but lmk if you want to include it as another example

2023-11-20 21:33 UTC, josh-mccrowell-braze requested changes
Thanks for tackling this task, Lydia!

I left some suggestions for flow and style, as well as some open-ended considerations. Let me know if you have any questions. 

Once these are resolved, I think we're ready to merge. I'll follow up about timing.

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +> With the Facebook Lead Ads integration via [Zapier][1], you can import your leads from Facebook into Braze along with tracking a custom event when leads are captured. Facebook Lead Ads is a type of
Suggestion for flow: 

```suggestion
> With the Facebook Lead Ads integration via [Zapier][1], you can import your leads from Facebook into Braze and track a custom event when leads are captured. Facebook Lead Ads is an ad format that allows businesses to collect lead information directly in Facebook. These ads are designed to make the lead generation process easy and seamless.
```

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +| [Facebook Business Manager](https://www.facebook.com/business/help/1710077379203657?id=180505742745347) | A centralized tool to manage your brand’s Facebook assets (for example, ad accounts, pages,
```suggestion
| [Facebook Business Manager](https://www.facebook.com/business/help/1710077379203657?id=180505742745347) | You will use Facebook Business Manager, a centralized tool to manage your brand’s Facebook assets (for example, ad accounts, pages, and apps), as part of this integration. |
```

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +| [Facebook ad account](https://www.facebook.com/business/help/195296697183682?id=829106167281625) | An active Facebook ad account tied to your brand’s business manager. <br><br>Ensure that you have
```suggestion
| [Facebook ad account](https://www.facebook.com/business/help/195296697183682?id=829106167281625) | You will need an active Facebook ad account tied to your brand’s business manager. <br><br>Ensure that you have the "Manage ad accounts" permission for each ad account you plan to use with Braze, and that you have accepted your ad account terms and conditions. |
```

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +| [Facebook Page](https://www.facebook.com/business/help/183277585892925?id=420299598837059) | An active Facebook Page tied to your brand’s business manager and with "Manage Pages" permissions for ea
```suggestion
| [Facebook Page](https://www.facebook.com/business/help/183277585892925?id=420299598837059) | You will need an active Facebook Page tied to your brand’s business manager. <br><br>Ensure that you have the "Manage Pages" permissions for each Facebook Page you plan to use with Braze. |
```

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +| [Facebook Leads access](https://www.facebook.com/business/help/540596413257598?id=735435806665862) | Facebook Leads access for each ad account you plan to use with Braze. |
```suggestion
| [Facebook Leads access](https://www.facebook.com/business/help/540596413257598?id=735435806665862) | Facebook Leads access for each ad account you plan to use with Braze is required to use this integration. |
```

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +| [Facebook Business Manager](https://www.facebook.com/business/help/1710077379203657?id=180505742745347) | A centralized tool to manage your brand’s Facebook assets (for example, ad accounts, pages,
Some of the descriptions were full sentences and some were fragments. I tried to standardize. Please finesse for flow if you have insights on how to improve this.

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +From Facebook Ads Manager, create a [Facebook Leads campaign and Facebook Lead Ads form](https://www.facebook.com/business/help/397336587121938?id=735435806665862&helpref=uf_permalink).
General comment: Can we please make links to non-Braze pages open in new windows as a best practice?

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +Include email or phone as a field in your form. You can use an email address or phone number when making a request to the `/users/track` endpoint to update or create the user profile. If you're colle
```suggestion
You can use either an email address or phone number when making a request to the [`/users/track` endpoint]({{site.baseurl}}/api/endpoints/user_data/post_user_track/) to update or create the user profile. For this reason, include a **Contact field** of **email** or **phone** in your lead ad form. If you're collecting first names or last names, collect those separately in your form instead of using full names.
```

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +In Zapier, go to **Apps** to search for available Facebook apps select either **Facebook Lead Ads** or **Facebook Lead Ads (for Business admins).
```suggestion
In Zapier, go to **Apps** to search for available Facebook apps. Select either **Facebook Lead Ads** or **Facebook Lead Ads (for Business admins).
```

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +In Zapier, go to **Apps** to search for available Facebook apps select either **Facebook Lead Ads** or **Facebook Lead Ads (for Business admins).
```suggestion
In Zapier, go to **Apps** to search for available Facebook apps select either **Facebook Lead Ads** or **Facebook Lead Ads (for Business admins)**.
```

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +Next, assign Zapier to Leads Access within your Business Manager. In your Business Manager, go to **Integrations** > **Leads Access** on the left-hand menu. Select your Facebook Page, then click **CR
Should this be a separate step (Step 3) instead of a subtask of Step 2?

2023-11-20 21:33 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +3. Check that you have assigned Zapier to Leads Access* by going to **Facebook Business Manager** > **Integrations** > **Lead Access**.
```suggestion
3. Check that you have assigned Zapier to Leads Access by going to **Facebook Business Manager** > **Integrations** > **Lead Access**.
```

2023-11-20 21:59 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +From Facebook Ads Manager, create a [Facebook Leads campaign and Facebook Lead Ads form](https://www.facebook.com/business/help/397336587121938?id=735435806665862&helpref=uf_permalink).
For clarity: I'm not asking that we go wide with this right now, just for this article, can we use target="_blank" or something?

2023-11-20 22:09 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/leads_capture.md
> +nav_title: Leads Capture
Noted! This was just part of the initial work to track that this section would need to be created

2023-11-28 16:32 UTC, dkim32 approved these changes
lgtm!

2023-11-28 16:55 UTC, josh-mccrowell-braze approved these changes
Lydia, please give this one final final review to make sure my edits look good on your end!

2023-11-28 16:58 UTC, lydia-xie commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/facebook_via_zapier.md
> +### Step 2: Connect your Facebook Account to Zapier
```suggestion
### Step 2: Connect your Facebook account to Zapier 
```

2023-11-28 17:20 UTC, merged