added Friendbuy partner integration documentation
braze-inc/braze-docs pull request #6594
Opened 2023-12-06 00:07 UTC by vladFriendbuy1

# Pull Request/Issue Resolution

#### Description of Change:
Added Friendbuy partner integration documentation.

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ X] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [X ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ X] Check that all links work.
- [X ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @bre-fitzgerald for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

2023-12-06 18:51 UTC, vladFriendbuy1 commented
@cla-bot check

2023-12-06 18:54 UTC, josh-mccrowell-braze commented
Hi @vladFriendbuy1 : 

Thanks for submitting your documentation! 

Our Alliances Technology Lead will be in contact next week to help move your article along and get it published on the Braze documentation portal. (Glad the CLA bot finally cooperated!)

If you have any questions in the meantime, please let me know. Thanks again!
The Braze Tech Writing team

2023-12-14 17:36 UTC, alex-braze requested changes
@vladFriendbuy1 just added in a few comments on a few areas we often hear customers ask about when reviewing the docs.

2023-12-14 17:36 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/Friendbuy/partner.md
> +2. Confirm your API-Key. In your Braze account, go to **Settings > API Keys**. A REST API key is required with every request to the Braze API. The API Key gives you access to your data for a workspac
Let's reference here what permissions this API key would need. I believe this would just be users.track, is that correct?

2023-12-14 17:36 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/Friendbuy/partner.md
> +
Can we add some information in here noting which identifiers are used to create/update users in Braze?

2023-12-14 17:36 UTC, alex-braze commented on _docs/_hidden/wip_partnerships/Friendbuy/partner.md
> +<td><h5><strong>Friendbuy Custom Attributes</strong></h5></td>
Can we show or mention somewhere in this section how these are formatted when sent to Braze. For example, is this sent as a nested custom attribute or an array. I think it would be helpful if we could show an example of what the format looks like when it is sent to Braze. I think it would also be helpful to add some information in this section about how diffs are sent to Braze.

2023-12-20 01:39 UTC, vladFriendbuy1 commented on _docs/_hidden/wip_partnerships/Friendbuy/partner.md
> +2. Confirm your API-Key. In your Braze account, go to **Settings > API Keys**. A REST API key is required with every request to the Braze API. The API Key gives you access to your data for a workspac
Hi Alex. Yes, definitely, the documentation should have had this (I based the PR off our help doc someone else wrote; we are going to update our documentation too). Right now the integration only needs users.track; we are going to use email.unsubscribe in an upcoming feature. I recommended having merchants check the top level "User Data" and "Email" checkboxes to: 1) make it easy for merchants 2) ensure the API keys have permissions merchants will need for future planned functionality. We have had problems getting merchants to make/update API keys with extra permissions for new releases in the past.

Thank you for the thorough review.

Changed in https://github.com/braze-inc/braze-docs/pull/6594/commits/ea58b4f30e4eba3c8e36e0c945d8785c63b3ded1

2023-12-20 01:39 UTC, vladFriendbuy1 commented on _docs/_hidden/wip_partnerships/Friendbuy/partner.md
> +<td><h5><strong>Friendbuy Custom Attributes</strong></h5></td>
I added a column for the Braze data type to the table in https://github.com/braze-inc/braze-docs/pull/6594/commits/e691745404f600c9cfb2cfb34ccccfb1ac7ce55c

2023-12-20 01:40 UTC, vladFriendbuy1 commented on _docs/_hidden/wip_partnerships/Friendbuy/partner.md
> +
Yes, definitely a good idea. Done in https://github.com/braze-inc/braze-docs/pull/6594/commits/5e43abda767f3fd866ef92688b9b13d1810f7c1d

2024-01-09 17:27 UTC, vladFriendbuy1 commented
Hello. Let me know if there any other changes that need to be made/what the status of this branch is. Thank you.

2024-01-09 18:26 UTC, alex-braze commented
@vladFriendbuy1 thanks for adding in the updates! The doc is approved from the Alliances side. We're working with the Friendbuy team to finalize launch plans before we can release this.

2024-03-08 00:16 UTC, internetisaiah commented
Hey @vladFriendbuy1 ,

Thanks for your work so far! I'm here to help you get your docs published. It looks like I don't have edit access for these commits. When you have a couple minutes, do you mind updating my permissions by following the instructions on GitHub's docs:

- [Enabling repository maintainer permissions on existing pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)

Thanks in advance!

2024-03-08 02:06 UTC, vladFriendbuy1 commented
@internetisaiah I was confused for a bit because the "Allow edits by maintainers" option does not show up on this pull request. Turns out this is because I forked braze-docs into the Friendbuy GitHub organization, and "Allow edits by maintainers" is not supported on repositories owned by organizations: https://github.com/orgs/community/discussions/5634

I opened a new PR from a fork in my individual account that allows edits by maintainers, and supersedes this PR: https://github.com/braze-inc/braze-docs/pull/7017

2024-03-08 02:10 UTC, closed without merging

2024-03-08 18:18 UTC, internetisaiah commented
Thanks @vladFriendbuy1 ! Checking out the new PR now. As a note, I'll be adding this step to our [new contributing docs](https://www.braze.com/docs/contributing/home/) so that we can reduce the likelihood of contributors needing to move their work to new PRs. Thanks for being flexible 👍🏽