BD-2606: Movable Ink Customer Data API docs
braze-inc/braze-docs pull request #6653
Opened 2023-12-14 23:37 UTC by bre-fitzgerald

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-2606**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

2023-12-18 20:34 UTC, bre-fitzgerald commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +{% endraw %}
Document was missing an example webhook for the "Card Add" event

2023-12-18 20:35 UTC, bre-fitzgerald commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +{% endraw %}
Document was missing an example webhook for the "Product Search" event

2024-01-12 21:12 UTC, alex-braze reviewed
@bre-fitzgerald added some comments in with some payloads!

2024-01-12 21:12 UTC, alex-braze commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
>  ### Cart Add Event
I think we can remove the tabs for events that don't have an example webhook: Cart Add Event, Product Search Event and Conversion Event (this one doesn't have a webhook campaign example only a /users/track payload example so we can remove it)

2024-01-12 21:12 UTC, alex-braze commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
>  ### Identify Event
Similar to the above can we change the tab to be "Expected MovableInk Request Payload" and can we add a tab to the left that is for the "Example Braze Trigger Event" with an example of what the Braze event payload would look like for an Identify Event that is triggering the webhook campaign to MI:

`{
  "events": [
    {
      "external_id": "123456789",
      "name": "Account Created",
      "time": "2023-12-06T19:20:45+01:00"
    }  
  ]
}`

2024-01-17 16:55 UTC, bre-fitzgerald commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
>  ### Cart Add Event
Updated!

2024-01-17 16:57 UTC, bre-fitzgerald commented
@alex-braze I believe I resolved all of your comments; let me know if this looks okay to merge or if any additional changes or review is needed. Thanks!

2024-01-19 22:49 UTC, alex-braze commented
@bre-fitzgerald apologies, one last comment: I think we can remove the "Cart Add Event", "Product Search Event" and "Conversion Event" example payloads completely!

2024-01-22 23:21 UTC, lydia-xie requested changes
made some suggestions for your review! looks great overall

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +Braze tracks user behavior across multiple platforms (web, mobile app, etc.), so a single user may have several distinct anonymous IDs. These IDs can be merged into the single known Stories user prof
```suggestion
Braze tracks user behavior across multiple platforms (such as web and mobile app), so a single user may have several distinct anonymous IDs. These IDs can be merged into the single known Stories user profile when an `identify` event is sent to Movable Ink, as long as the `identify` event includes both an anonymous identifier and the single known identifier.
```

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +However, given that the webhook is intended just to stream data, attribution at this level is likely less useful than looking at attribution at the campaign level after the behavioral data from Braze
```suggestion
However, given that the webhook is intended to stream data, attribution at this level is likely less useful than looking at attribution at the campaign level after the behavioral data from Braze is used to personalize content.
```

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +Braze supports scheduled, action-based, and API-triggered deliveries. [Action-based delivery][3] is usually the best fit for most behavioral event use cases. However, if there are any questions about
```suggestion
Braze supports scheduled, action-based, and API-triggered deliveries. [Action-based delivery][3] is usually the best fit for most behavioral event use cases. For questions about what makes sense for your use case, connect with your Braze and Movable Ink customer success managers.
```

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +{% tab Expected MovableInk Request Payload %}
```suggestion
{% tab Expected Movable Ink Request Payload %}
```
Not sure if this is supposed to be two words

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +{% tab Expected MovableInk Request Payload %}
```suggestion
{% tab Expected Movable Ink Request Payload %}
```
Same comment

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +{% tab Expected MovableInk Request Payload %}
```suggestion
{% tab Expected Movable Ink Request Payload %}
```
Same comment

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +### Product View Event
```suggestion
### Product view event
```
?

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +### Category View Event
```suggestion
### Category view event
```
Feel free to disregard if inaccurate

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +### Identify Event
```suggestion
### Identify event
```

2024-01-22 23:21 UTC, lydia-xie commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +2. For your **Request Body**, either create your own request body with JSON key-value pairs, or enter your event payload as raw text. Refer to the [sample payloads](#sample-payloads) for examples of
```suggestion
2. For your **Request Body**, either create your own request body with JSON key-value pairs or enter your event payload as raw text. Refer to the [sample payloads](#sample-payloads) for examples of standard ecommerce events.
```

2024-01-22 23:23 UTC, bre-fitzgerald commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +However, given that the webhook is intended just to stream data, attribution at this level is likely less useful than looking at attribution at the campaign level after the behavioral data from Braze
revised your suggestion slightly

2024-01-22 23:23 UTC, bre-fitzgerald commented on _docs/_partners/message_personalization/dynamic_content/movable_ink/customer_data_api.md
> +{% tab Expected MovableInk Request Payload %}
oop good catch, copied and pasted from another source and missed this 👍

2024-01-22 23:30 UTC, lydia-xie approved these changes

2024-01-22 23:30 UTC, merged