BD-2713: Criteo audience sync GA
braze-inc/braze-docs pull request #6709
Opened 2024-01-08 19:07 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-2713**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2024-01-11 23:14 UTC, dkim32 requested changes
Left some comments!

2024-01-11 23:14 UTC, dkim32 commented on _docs/_partners/canvas_steps/overview.md
> +This documentation is not intended to provide, nor may it be relied upon as providing legal advice. The use of Audience Sync is subject to specific legal requirements. To ensure that you are using it
Could we move this to the Data Privacy considerations section within the overview?

2024-01-11 23:14 UTC, dkim32 commented on _docs/_partners/canvas_steps/overview.md
> +Keep in mind that Braze will sync users as soon as they enter the Audience Sync step within your Canvas.
Before this sentence, let's add: https://docs.google.com/document/d/1-ojMXl3tXRev17QMWoPpB42g9ORb6fD3p5JksQgeqRU/edit?disco=AAABD7I8MRM

2024-01-11 23:14 UTC, dkim32 commented on _docs/_partners/canvas_steps/overview.md
> +![][9]{: style="max-width:85%;"}
we should have images 7 and 9 back to back and have the sentence starting with "next, you can create..."

2024-01-11 23:14 UTC, dkim32 commented on _docs/_partners/canvas_steps/overview.md
Add the legal disclaimer after the header

2024-01-12 17:20 UTC, lydia-xie commented
@cla-bot check

2024-01-12 18:21 UTC, dkim32 approved these changes
lgtm. thanks for the quick fixes!

2024-01-12 18:50 UTC, bre-fitzgerald approved these changes
lgtm!

2024-01-12 18:51 UTC, merged