BD-2695 Add image specs to an includes file
braze-inc/braze-docs pull request #6733
Opened 2024-01-12 22:10 UTC by rachel-feinberg

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #BD-2695

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

2024-01-12 22:29 UTC, bre-fitzgerald requested changes
Hey @rachel-feinberg! Thanks for tackling this! The includes usage looks great and is rendering correctly for me, however, I don't think this is the right place to put this content. This would mean we have all the channels image specs hosted under IAM modals. 😅  

I took a look at the ticket request and if I had to guess, it looks like they put a random URL that currently has image specs as the request URL, since that field is required. 

I'd suggest we do this instead:

1. Create a new file under [Templates and Media](https://braze-docs-ghmxy6lo3-braze.vercel.app/docs/user_guide/engagement_tools/templates_and_media)
2. Add all the content you just added (still use the includes!)
3. As a next step, find areas in the docs where we list image specs and replace them with the respective includes content.

Let me know what you think! Happy to chat it through in Slack too.

2024-02-20 17:14 UTC, internetisaiah reviewed
Just tiny suggestions. Docs look great!

2024-02-20 17:14 UTC, internetisaiah commented on _docs/_user_guide/engagement_tools/templates_and_media/image_specs.md
> +{% alert tip %} Create assets with confidence! Our in-app message image templates and safe zone overlays are designed to play nicely with devices of all sizes. [Download Design Templates ZIP]({% imag
```suggestion
{% alert tip %} Create assets with confidence! Our in-app message image templates and safe-zone overlays are designed to play nicely with devices of all sizes. [Download Design Templates ZIP]({% image_buster /assets/download_file/Braze-In-App-Message-Design-Templates.zip %}). {% endalert %}
```

2024-02-20 17:14 UTC, internetisaiah commented on _includes/image_specs.md
> +    <td>Used in <a href="{{site.baseurl}}/user_guide/message_building_by_channel/push/android/rich_notifications/">Android rich notifications</a></td>
```suggestion
    <td>Used in <a href="{{site.baseurl}}/user_guide/message_building_by_channel/push/android/rich_notifications/">Android rich notifications</a>.</td>
```

2024-02-20 17:22 UTC, internetisaiah approved these changes
LGTM

2024-02-20 18:21 UTC, merged