Updated Extole integration guide to reflect changes on the Extole side
braze-inc/braze-docs pull request #6953
Opened 2024-02-23 19:31 UTC by ekthayer

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @internetisaiah as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @internetisaiah for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@internetisaiah</td>
    <td>Developer Guide<br>Technology partners<br>Channels</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>Frontend Infrastructure & Experience (FIX)</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

2024-02-23 20:39 UTC, josh-mccrowell-braze commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +### Extole Program Events
```suggestion
### Extole program events
```

2024-02-23 20:39 UTC, josh-mccrowell-braze commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +### Extole Rewards
```suggestion
### Extole rewards
```

2024-02-23 20:39 UTC, josh-mccrowell-braze commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +### Lookup and Create Users in Braze
```suggestion
### Lookup and create users in Braze
```

2024-02-23 20:42 UTC, josh-mccrowell-braze commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +### Lookup and create users in Braze
```suggestion
### Find and create users in Braze
```

2024-02-26 17:44 UTC, ekthayer commented
@josh-mccrowell-braze do you need any further action from me to proceed?

2024-02-26 17:46 UTC, josh-mccrowell-braze commented
Hi @ekthayer  - Thanks so much for this update! I'm coordinating with our partnership team for final approval. Appreciate you keeping the Braze Docs up to date!

2024-02-26 19:49 UTC, alex-braze requested changes
Added in two questions for clarification!

2024-02-26 19:49 UTC, alex-braze commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +| Event | Description | Default Properties & User Attributes |
Within the "Default Properties & User Attributes" which ones are sent as event properties vs. user attributes? Event properties do not consume data points OOTB but user attributes will incur data points so customers will want to be aware of how many they are sending. 

In addition, for those that are user attributes, is this configurable per event? The customer would likely not want to sent "First name" as an attribute with each event since this would incur a data point every time even though the value likely is not changing.

2024-02-26 19:49 UTC, alex-braze commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +7. Select your Braze External ID key mapping, which is how Extole updates user profiles in Braze. You can map the Braze External ID key to Extole's `email_address` or `partner_user_id` for the user.
We might want to add a note here that we recommend against customers using 'email_address' as the 'external_id' as it is not secure. Braze can accept 'email_address' as an identifier but it would be sent within the 'email' field rather than the 'external_id' field.

2024-02-29 17:25 UTC, josh-mccrowell-braze commented
Hi @ekthayer : Just flagging that Alex from the Partner team has a few questions here. Let me know if you need support in resolving these!

2024-02-29 18:44 UTC, ekthayer commented
@josh-mccrowell-braze I apologize for the delay! I had to check with our engineers on few points. I will be updating the doc to address Alex's comments this afternoon and hopefully everything will be good to go!

2024-02-29 18:47 UTC, josh-mccrowell-braze commented
@ekthayer No apologies necessary whatsoever, just didn't want it to slip through the cracks. Thanks so much!

2024-03-08 15:15 UTC, ekthayer commented
Okay! After much back and forth with our engineers, I've updated the doc to (hopefully) address all the questions posted here. I think we are ready for another review! @josh-mccrowell-braze

2024-03-08 18:28 UTC, lydia-xie approved these changes

2024-03-08 18:28 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +8. Complete the connection by saving your settings. Once this is done, Extole events will be able to flow into your Braze account.
```suggestion
1. Select the Braze integration on the [Partners](https://my.extole.com/partners) page of your My Extole account.
2. In the Braze integration, select **Install** to initiate the connection between Extole and Braze.
3. Fill out the required fields, starting with your Braze REST API key. 
4. Enter your Braze API URL. This URL depends on which instance your Braze account is provisioned to.
5. Add any Extole events you'd like to send to Braze. The default events, event properties, and user attributes are described in the [Extole Events table](https://dev.extole.com/docs/braze#extole-program-events).
6. Add any reward states you'd like to send to Braze other than the `FULFILLED` state. Refer to the [Extole Rewards table](https://dev.extole.com/docs/braze#extole-rewards) for descriptions of the available reward states.
7. Select your Braze external ID key mapping. This is how Extole updates user profiles in Braze. You can map the Braze external ID key to Extole's `email_address` or `partner_user_id` for the user. We recommend using `external_id` instead of `email_address` as it is more secure.
8. Save your settings to complete the connection. Now, Extole events can flow to your Braze account.
```

2024-03-08 18:28 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +Below are the default events, event properties, and user attributes Extole will send into Braze. In addition to the default events listed here, you can add any other Extole events to your integration
```suggestion
Below are the default events, event properties, and user attributes Extole will send to Braze. Reach out to your Extole implementation or customer success managers to identify and add additional Extole events to your integration.
```

2024-03-08 18:28 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +| `outcome` - The outcome is dynamic based on the configuration of your program (e.g., `extole_shipped`, `extole_converted`, etc.)| A participant has converted or completed the desired outcome event
```suggestion
| `outcome` - The outcome is dynamic based on the configuration of your program (such as `extole_shipped`, `extole_converted`)| A participant has converted or completed the desired outcome event configured for the program. | Dynamic per program | Email <br>First name <br>Last Name |
```

2024-03-08 18:28 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +| `subscribed` | A participant has opted-in to receive marketing messages. | NA | Email  <br>List type  <br>External ID  <br>Email subscribe (opted in) |
```suggestion
| `subscribed` | A participant has opted-in to receive marketing messages. | N/A | Email  <br>List type  <br>External ID  <br>Email subscribe (opted in) |
```

2024-03-08 18:28 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +By default, Extole will send reward events in the `FULFILLED` state to Braze so that you can trigger reward notifications via a Braze campaign or canvas. See the table below for additional reward sta
```suggestion
By default, Extole will send reward events in the `FULFILLED` state to Braze so you can trigger reward notifications via a Braze campaign or Canvas. Refer to the following table for additional reward states.
```

2024-03-08 18:28 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +| `FULFILLED` - Default | The reward has been assigned a value (e.g., coupon, gift card, etc.) by an Extole reward supplier. | Email <br>Face value  <br>Coupon code  <br>Face value type  | Email <br>
```suggestion
| `FULFILLED` | The default state. The reward has been assigned a value (such as coupon or gift card) by an Extole reward supplier. | Email <br>Face value  <br>Coupon code  <br>Face value type  | Email <br>First name  <br>Last name |
```

2024-03-08 18:28 UTC, lydia-xie commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/extole.md
> +For certain use cases, such as a new email or SMS subscription where Extole does not have an external id (user id) for the user, Extole can check for the user's identifier using Braze's Export User b
```suggestion
For certain use cases, such as a new email or SMS subscription where Extole does not have an external ID (user ID), Extole can check for the user's identifier using the Braze [Export user profile by identifier endpoint]({{site.baseurl}}/api/endpoints/export/user_data/post_users_identifier/). Extole will add and update any profile attributes if the user exists in Braze. If the request does not return a user profile, Extole will use the `/users/track` endpoint to create a user alias with the user's email address as the alias name.
```

2024-03-08 18:40 UTC, merged