Create celebrus.md
braze-inc/braze-docs pull request #7030
Opened 2024-03-12 14:53 UTC by brian-holyer-d4t4solutions-com

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @internetisaiah as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Ana Teresa Serafino on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @internetisaiah for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@internetisaiah</td>
    <td>Developer Guide<br>Technology partners<br>Channels</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>Frontend Infrastructure & Experience (FIX)</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

2024-03-12 15:22 UTC, josh-mccrowell-braze commented
Hi @brian-holyer-d4t4solutions-com  - Let me know if you want a quick chat about contributing. My email is joshua.mccrowell@braze.com. I left some resources for you on one of your previous pull requests, [here](https://github.com/braze-inc/braze-docs/pull/7029).

2024-03-18 14:45 UTC, josh-mccrowell-braze commented
Hi @brian-holyer-d4t4solutions-com 
I merged in a change you made from a [previous PR](https://github.com/braze-inc/braze-docs/pull/7029) into this branch since you had more work on it and closed the other PR. Let me know if you'd like to chat!
Thanks,
The Braze Docs Team

2024-03-20 17:29 UTC, alex-braze requested changes
Hey @brian-holyer-d4t4solutions-com thanks for submitting these! I have added in some comments with some suggested changes for adding in some information we often see customers struggle with if it is not included in the docs. Please let me know if you have any questions.

2024-03-20 17:29 UTC, alex-braze commented on _docs/_partners/isv_partners/celebrus.md
> +> Celebrus seamlessly integrates with Braze SDK across web and mobile app channels, facilitating the population of Braze with channel activity data. This includes comprehensive insights into visitor
The verbiage "this enables the delivery of precise Braze analytics..." is a bit confusing. Can we remove that first piece and start with "This empowers you to devise highly effective..."

2024-03-20 17:29 UTC, alex-braze commented on _docs/_partners/isv_partners/celebrus.md
>  <!-- The prerequisites for this task. If no prerequisites are required, you can remove this section. -->
Based on our last discussion of the integration my understanding was that the integration is happening in two ways:

Braze Cloud Data Ingestion
- The customer must have one of the data warehouses we support in CDI. The Celebrus Data Loader will then sync the data out to that customer data warehouse 
- The Celebrus Data Loader is going to sync the data in the form that we would expect through CDI
- This will support attributes, events, and purchases

SDK: The Celebrus snippet (web SDK) can also be used to insert the Braze SDK to initiate the SDK and identify the user.
- Right now what is built is just the init not the syncing of data but in theory, Celebrus could call Braze SDK methods. Such as client-side custom events to be used for triggering IAMs (this would be an important call out since IAMs can only be triggered via client-side events)

If the above is accurate then there are a few pre-requisites for the customer to use this integration, including:

- A data warehouse supported by CDI
- Setting up CDI in Braze

2024-03-20 17:29 UTC, alex-braze commented on _docs/_partners/isv_partners/celebrus.md
There are a few items I think we need to address in the doc to ensure customers reviewing these docs understand how the integration works:

1. Can you confirm the diffing has been added to the integration to ensure there will be no data point overages?
2. How identity will work. For example, what identifiers are supported? This is particularly important when we're talking about using both the SDK and CDI. The Braze SDK will automatically create an anonymous user through a device_id when a user first starts a session. Until an identifier is assigned to that user, such as email, phone, external_id or user alias there is no identifier for CDI to sync on.
3. We had talked about support for attributes, events and purchases but only attributes are called out on the docs. Can you confirm if events and purchases will be supported?
4. With the support of attributes, customers will want to ensure that standard attributes (email, etc) are using the assigned naming convention. Can you confirm this is the case and ensure this is called out in the docs?
5. Will custom attributes (and, if events and purchases are support, event properties) support nested data structures at all? If so, will these be sent in a data point efficient manner?

2024-04-01 15:13 UTC, josh-mccrowell-braze commented
Hi @brian-holyer-d4t4solutions-com - Just following up about Alex's comments above. Let us know if there's anything the Braze Docs team can do to support you finalizing your documentation.

2024-05-09 12:59 UTC, nadeem-celebrus commented on _docs/_partners/isv_partners/celebrus.md
> +> Celebrus seamlessly integrates with Braze SDK across web and mobile app channels, facilitating the population of Braze with channel activity data. This includes comprehensive insights into visitor
Celebrus captures an individual's unique identifiers such as email, phone, external id or user alias and sends to Braze via CDI. This allows for Braze to sync identities for the same individual.

2024-05-21 15:34 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +If you do not already have the Braze SDK implemented in your web channel, you can use Celebrus to deploy the Braze SDK. Celebrus will add the Braxe SDK to web pages, and set up the Braze identity for
```suggestion
If you do not already have the Braze SDK implemented in your web channel, you can use Celebrus to deploy the Braze SDK. Celebrus will add the Braze SDK to web pages, and set up the Braze identity for the web visitor using the Celebrus identity graph. Customer attributes can be synced with Braze via a Cloud Data Ingestion (CDI). This requires a data warehouse supported by Braze CDI, and the configuration of the CDI in Braze.
```

2024-05-21 15:37 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +>
```suggestion
```

2024-05-21 15:37 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +>
```suggestion

```

2024-05-21 15:38 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +## Prerequisites
```suggestion

## Prerequisites
```

2024-05-21 15:38 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +| Data Warehouse (Optional) | When using the Celebrus connector for Braze Custom Attributes, you must have a data warehouse that is supported by Braze's Cloud Data Ingestion (CDI) integration, and co
```suggestion
| Data Warehouse (Optional) | When using the Celebrus connector for Braze custom attributes, you must have a data warehouse that is supported by Braze's Cloud Data Ingestion (CDI) integration, and configure CDI in the Braze dashboard. |
```

2024-05-21 15:39 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +This integration uses Braze's Cloud Data Ingestion product. Follow Braze's documentation to set up the Cloud Data Ingestion settings according to the type of warehouse you are using. In Braze, you wi
```suggestion
This integration uses Braze's Cloud Data Ingestion product. Follow Braze's documentation to set up the Cloud Data Ingestion settings according to the type of warehouse you are using. In Braze, you will need to [configure the Cloud Data Ingestion settings]({{site.baseurl}}/user_guide/data_and_analytics/cloud_ingestion/overview/) to accept data from the warehouse Celebrus is connected to.
```

2024-05-21 15:40 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +Celebrus will use the defined identifiers to send the customer attributes that are defined in the Celebrus Profile Builder, but only when attribute values change. The integration currently supports a
```suggestion
Celebrus will use the defined identifiers to send the customer attributes that are defined in the Celebrus Profile Builder, but only when attribute values change. The integration currently supports attributes; events and purchases are planned for a future release. Note that the attribute names will be as defined in the Celebrus profile builder, so the attributes in Braze will mirror those in the Celebrus profile. These may need to be adjusted to conform to Braze naming conventions. For example, conforming to Braze's [standard attribute naming conventions] ({{site.baseurl}}/api/objects_filters/user_attributes_object#:~:text=custom%20attributes.-,Braze%20user%20profile%20fields,-Important%3A%0AThe).  
```

2024-05-21 15:40 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +The Celebrus connector for Braze Custom Attributes sends custom attributes to an intermediate database, pre-formatted in the way Braze expects to receive it. In Celebrus you configure the connection
```suggestion
The Celebrus connector for Braze Custom Attributes sends custom attributes to an intermediate database, pre-formatted in the way Braze expects to receive it. In Celebrus you configure the connection details for the database—these will depend on what type of database you are using (such as Snowflake or Redshift). 
```

2024-05-21 15:44 UTC, rachel-feinberg commented on _docs/_partners/home.md
> +  url: /docs/partners/data_and_infrastructure_agility/analytics/celebrus/
```suggestion
  url: /docs/partners/isv_partners/celebrus/
```

2024-05-21 16:19 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +The Celebrus connector for Braze SDK will insert and initialize the Braze SDK to identify the user and add the identifier to Celebrus' Identity Graph. This connector will not log data to the user pro
```suggestion
The Celebrus connector for Braze SDK will insert and initialize the Braze SDK to identify the user and add the identifier to Celebrus' Identity Graph. This connector will not log data to the user profile or trigger other Braze SDK methods. You can call any desired methods directly within your code base to log data via the [Braze SDK] ({{site.baseurl}}/developer_guide/platform_integration_guides/web/initial_sdk_setup/) or take advantage of other Braze SDK-supported features. 
```

2024-05-21 16:20 UTC, rachel-feinberg commented on _docs/_partners/isv_partners/celebrus.md
> +Celebrus will use the defined identifiers to send the customer attributes that are defined in the Celebrus Profile Builder, but only when attribute values change. The integration currently supports a
```suggestion
Celebrus will use the defined identifiers to send the customer attributes that are defined in the Celebrus Profile Builder, but only when attribute values change. The integration currently supports attributes; events and purchases are planned for a future release. Note that the attribute names will be as defined in the Celebrus profile builder, so the attributes in Braze will mirror those in the Celebrus profile. These may need to be adjusted to conform to Braze naming conventions. For example, conforming to Braze's [standard attribute naming conventions] ({{site.baseurl}}/api/objects_filters/user_attributes_object/).  
```

2024-05-22 16:51 UTC, rachel-feinberg approved these changes
Lgtm! @alex-braze does this look ready to merge?

2024-05-22 19:49 UTC, alex-braze approved these changes

2024-05-22 19:52 UTC, merged