BD-2343 Rules-based recommendations article
braze-inc/braze-docs pull request #7094
Opened 2024-03-22 20:09 UTC by rachel-feinberg

# Pull Request/Issue Resolution

#### Description of Change:
> Created a new rules-based recommendations article

Closes #**BD-2343**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

2024-03-22 21:24 UTC, lydia-xie requested changes
looks good, left some suggestions for your review!

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +Let’s say you have a health food app and want to create a content card campaign that sends different recipes based on how long a user has been signed up for your app.
```suggestion
Let’s say you have a health food app and want to create a Content Card campaign that sends different recipes based on how long a user has been signed up for your app. 
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +1. Create and upload a catalog via CSV that includes the following information:<br>- **id:** A unique number that correlates to the number of days since the user signed up with your app. For example,
```suggestion
1. Create and upload a catalog via CSV that includes the following information:<br>- **id:** A unique number that correlates to the number of days since the user signed up with your app. For example, `3` correlates to three days.<br>- **type:** The recipe category, such as `comfort`, `fresh`, and others.<br>- **title:** The title of the Content Card that will be sent for each ID, such as “Make ahead for lunch this week” or “Let’s taco about it”.<br>- **link:** The link to the recipe article.<br>- **image_url:** The image that corresponds to the recipe.
```
Thoughts on turning this bulleted list into a table? 🤔  Or rephrasing this use case so that this info isn't part of a step?

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +3. Create a content card campaign. In the composer, enter Liquid logic to determine which users should receive the campaign, and which recipe and image should display. In this use case, Braze will pu
```suggestion
3. Create a Content Card campaign. In the composer, enter Liquid logic to determine which users should receive the campaign, and which recipe and image should display. In this use case, Braze will pull the user’s `start_date` (or sign-up date) and compare it to the current date. The difference in days will determine which Content Card is sent. 
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +4. In the **On click behavior** section, enter Liquid logic for where users should be redirected when they click the content card on iOS, Android, and Web devices.
```suggestion
4. In the **On click behavior** section, enter Liquid logic for where users should be redirected when they click the Content Card on iOS, Android, and Web devices. 
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +5. Go to the **Test** tab and select “Custom user” under **Preview message as user**. Enter a date in the **Custom attribute** field to preview the content card that would be sent to a user who signe
```suggestion
5. Go to the **Test** tab and select **Custom user** under **Preview message as user**. Enter a date in the **Custom attribute** field to preview the Content Card that would be sent to a user who signed up on that date. <br><br>
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +2. Write Connected Content Liquid into the message body or Content Block HTML editor that will call your endpoint to search your database.
```suggestion
2. Write Connected Content Liquid in the message body or Content Block HTML editor that will call your endpoint to search your database.
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +Next, let’s say you want to pull restaurant recommendations based on a user’s city and food type. You can do so by dynamically inserting the custom attributes for the user’s city and food type to the
```suggestion
Next, let’s say you want to pull restaurant recommendations based on a user’s city and food type. You can do so by dynamically inserting the custom attributes for the user’s city and food type at the beginning of the call and then assigning the value of `restaurants` to the variable `city_food.restaurants`.
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +- If a rating is “Good”, append the restaurant name to the `good_restaurants` string, then add a * character at the end.
```suggestion
1. Use `assign` to create blank arrays for rating categories of “excellent”, “very good”, and “good”.
2. Add a `for` loop that examines the rating of each restaurant in the list. 
- If a rating is “Excellent”, append the restaurant name to the `excellent_restaurants` string, then add an asterisk (*) at the end to separate each restaurant name. 
- If a rating is “Very Good”, append the restaurant name to the `very_good_restaurants` string, then add an asterisk (*) at the end.
- If a rating is “Good”, append the restaurant name to the `good_restaurants` string, then add an asterisk (*) at the end.
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +See the below screenshot for an example of how the response displays on a user’s device.
```suggestion
See the below image for an example of how the response displays on a user’s device.
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +![][5]{: style="max-width:30%;"}
```suggestion
![][5]{: style="max-width:30%;"}
```
Minor suggestion to have some alt text here

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +![][3]{: style="max-width:40%;"}<br><br>
```suggestion
![][3]{: style="max-width:60%;"}<br><br>
```
Suggesting to resize this image because the other images in the article are larger, or adjust the sizing for step 2 and 3 of Catalogs use case

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +2. After the catalog is uploaded to Braze, check the preview of a select number of catalog items to confirm the information imported accurately. The items may be randomized in the preview, but this w
```suggestion
2. After the catalog is uploaded to Braze, check the preview of a select number of catalog items to confirm the information imported accurately. The items may be randomized in the preview, but this won’t affect the output of the recommendation engine.
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +5. Pass one or more of those IDs back to the catalog to collect the other details for those products.
```suggestion
1. [Create a catalog]({{site.baseurl}}/user_guide/personalization_and_dynamic_content/catalogs/catalog/) of products.
2. For each product, add a list of recommended products as a string separated by a delimiter (like a pipe `|`) in a column named “product_recommendations”.
3. Pass the product ID that you want to find recommendations for to the catalog.
4. Get the `product_recommendations` value for that catalog item and split it by the delimiter with a Liquid split filter.
5. Pass one or more of those IDs back to the catalog to collect the other product details.
```

2024-03-22 21:24 UTC, lydia-xie commented on _docs/_user_guide/sage_ai/rules_based_recommendations.md
> +Rules-based recommendations are based on fixed logic that you must manually set. This means your recommendations won’t adjust to a user's individual purchase history and tastes unless you update the
```suggestion
Rules-based recommendations are based on fixed logic that you must manually set. This means your recommendations won’t adjust to a user's purchase history and tastes unless you update the logic.<br><br>To create personalized AI recommendations that automatically adjust to a user’s history, check out [AI item recommendations]({{site.baseurl}}/user_guide/sage_ai/recommendations/).
```

2024-03-25 15:39 UTC, lydia-xie approved these changes
lgtm! marking as approved from my end!

2024-03-25 15:41 UTC, rachel-feinberg commented
@lydia-xie, awesome! Thank you!
@bre-fitzgerald Let me know if you need anything on my end before merging this into your PR

2024-03-25 17:21 UTC, merged