Adding MetaRouter docs
braze-inc/braze-docs pull request #7172
Opened 2024-04-04 18:46 UTC by alex-braze

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @internetisaiah as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Ana Teresa Serafino on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @internetisaiah for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@internetisaiah</td>
    <td>Developer Guide<br>Technology partners<br>Channels</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>Frontend Infrastructure & Experience (FIX)</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

2024-04-04 19:08 UTC, alex-braze reviewed
Finalizing metarouter docs

2024-04-05 14:39 UTC, internetisaiah requested changes

2024-04-05 14:39 UTC, internetisaiah commented on _docs/_partners/data_and_infrastructure_agility/workflow_automation/metarouter.md
> + - Retries can be built in.
Hey @alex-braze , can we follow up with the client and get steps on how to use this with Braze? i.e. something [like this](https://www.braze.com/docs/partners/data_and_infrastructure_agility/analytics/scuba/#creating-segments-using-scubas-behavioral-data), where it shows step-by-step how to use the integration:

- Whether it's done through an API
- Whether it's done through their platform
- Etc.

Thanks! Let me know if you have any questions

2024-04-05 14:39 UTC, internetisaiah commented on _docs/_partners/data_and_infrastructure_agility/workflow_automation/metarouter.md
> +1. Establish your MetaRouter Cluster.
Are these steps they user needs to do _before_ step 1 and 2 below? Or is this list referring to something else?

2024-04-08 22:33 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/workflow_automation/metarouter.md
> +1. Establish your MetaRouter Cluster.
These steps are (from my understanding) the overarching steps of getting Metarouter set up to send events to Braze. 

Step 1 and 2 below are moreso setting up the Braze integration so that Braze can receive events from Metarouter. Please feel free to rename stuff and move it around to make sense!

2024-04-08 22:36 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/workflow_automation/metarouter.md
> + - Retries can be built in.
All of the work is done in their platform so I can push them to be more prescriptive but I think for this initial launch unfortunately we will need to launch with the bare minimum on docs. 

Maybe the title for this is something closer to "Integration Call Outs" or something of that sort.

2024-04-08 22:37 UTC, alex-braze reviewed
@internetisaiah - added in some answers to your questions!

2024-04-10 00:47 UTC, internetisaiah approved these changes
LGTM

2024-04-10 00:47 UTC, merged