BD-3060: Sanitization article
braze-inc/braze-docs pull request #7306
Opened 2024-05-03 22:25 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-3060**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2024-05-06 23:38 UTC, Singwai commented on _docs/_user_guide/message_building_by_channel/email/best_practices/sanitization.md
> +The main purpose of sanitization is to prevent bad actors from accessing other Braze dashboard users’ session data. Without sanitization, a bad actor with basic read only access can create an email u
Should we tell the public that the purposes of the sanitization is to prevent XSS on dashboard? Sanitization is probably not the best way to handle XSS and we are stuck with it because of the our current architecture.

2024-05-06 23:38 UTC, Singwai commented on _docs/_user_guide/message_building_by_channel/email/best_practices/sanitization.md
> +    * Preview and Test
Let me review all the preview and test iframes and give an update, but I am almost certain that the preview and test iframes are secure (or can be secured) without any payload sanitization logic.

2024-05-07 16:16 UTC, thomas-devoss reviewed
I like the idea of adding this to the docs, and maybe linking to them when the sanitization kicks in when they are in the dashboard. im not sure as far as the wording, but the over all information is good and accurate. May want to get legal weigh in on how much we can/want to say in this manner tho

2024-05-08 01:36 UTC, Singwai commented on _docs/_user_guide/message_building_by_channel/email/best_practices/sanitization.md
> +    * Preview and Test
I check and confirmed that we don't run sanitization for all preview and test iframe.

2024-05-08 20:51 UTC, thomas-devoss approved these changes
lgtm

2024-05-09 16:16 UTC, colleenwoodford commented
> I like the idea of adding this to the docs, and maybe linking to them when the sanitization kicks in when they are in the dashboard. im not sure as far as the wording, but the over all information is good and accurate. May want to get legal weigh in on how much we can/want to say in this manner tho

@thomas-devoss I ran this same doc by legal a week ago and they were 👍 on it since we're modifying their content and we need to note it in the documentation. The plan is to link from the dashboard when sanitization happens - we already have designs done and just need to do the work.

2024-05-09 16:19 UTC, colleenwoodford requested changes
one comment to add classic editor

2024-05-09 16:19 UTC, colleenwoodford commented on _docs/_user_guide/message_building_by_channel/email/best_practices/sanitization.md
> +If Braze detects JavaScript that is a security risk, before you go to the **Preview and Test** tab to view the email message Braze will ask you to confirm that Braze can remove the JavaScript from yo
"...before you go to the **Preview and Test** tab or the **Classic Editor** to view the email message..."

2024-05-09 16:32 UTC, rachel-feinberg commented on _docs/_user_guide/message_building_by_channel/email/best_practices/sanitization.md
> +The main purpose of sanitization is to prevent bad actors from accessing other Braze dashboard users’ session data. Without sanitization, a bad actor with basic read only access can create an email u
```suggestion
The main purpose of sanitization is to prevent bad actors from accessing other Braze dashboard users’ session data. Without sanitization, a bad actor with basic read-only access can create an email using the CKEditor with JavaScript that "sends current browser session" to anywhere the bad actor wants using a network request.
```

2024-05-09 16:35 UTC, rachel-feinberg approved these changes
Made small suggestions, but overall lgtm!

2024-05-09 16:42 UTC, merged