BD-3101: Liquid color-coding scheme
braze-inc/braze-docs pull request #7401
Opened 2024-05-23 21:45 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-3101**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

2024-06-06 21:18 UTC, colleenwoodford requested changes

2024-06-06 21:18 UTC, colleenwoodford commented on _docs/_user_guide/personalization_and_dynamic_content/liquid.md
> +## Liquid highlights
I'd be interested to see what Alison would recommend, but I'd like to call this - Liquid Highlighting - instead, unless that violates some standards on the docs slide. I'd be interested to see how Allison Everett would call it in the learning videos.

2024-06-06 21:18 UTC, colleenwoodford commented on _docs/_user_guide/personalization_and_dynamic_content/liquid.md
> +| Liquid element   | Color  |
Do you think it would be worthwhile outlining the color coding schema for each element (like abort messages, etc), or do you think that it would be too granular? I think it's confusing to see just the two items called out with the more complete screenshot linked below.

2024-06-12 18:19 UTC, rachel-feinberg approved these changes
Lgtm!

2024-06-12 18:19 UTC, merged