BD-3167 Track user sync beta
braze-inc/braze-docs pull request #7515
Opened 2024-06-13 15:19 UTC by lydia-xie

# Pull Request/Issue Resolution

#### Description of Change:
> I'm changing..... (could be a link, a new image, a new section, etc.)... because...

Closes #**BD-3167**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**June 18. 2024**)
- [ ] No

---

2024-06-13 23:55 UTC, bartlam18 commented on _docs/_hidden/private_betas/post_user_track_synchronous.md
> +Reach out to your customer success manager if you need your limit increased.
We should just take this line out, while I definitely want to hear feedback on whether this rate limit is too small, we can't guarantee increasing it.

2024-06-13 23:56 UTC, bartlam18 commented on _docs/_hidden/private_betas/post_user_track_synchronous.md
> +We apply a base speed limit of 500 requests per minute to this endpoint for all customers. Each `/users/sync/track/` request can contain up to one event object, one attribute object, or one purchase
Should be /users/track/sync

2024-06-18 17:21 UTC, internetisaiah requested changes
Feel free to implement all or some of these changes. The only ones I think that need to be changed are the FAQ ones to:

- reduce heading length
- ensure all questions are using 1st person

2024-06-18 17:21 UTC, internetisaiah commented on _docs/_hidden/private_betas/post_user_track_synchronous.md
> +When using any of the aforementioned API requests, you should receive one of the following two general responses: a successful message or a message with fatal errors.
```suggestion
When using this endpoint's [request parameters](#request-parameters), you should receive one of the following responses: a successful message or a message with fatal errors.
```

2024-06-18 17:21 UTC, internetisaiah commented on _docs/_hidden/private_betas/post_user_track_synchronous.md
> +When using any of the aforementioned API requests, you should receive one of the following two general responses: a successful message or a message with fatal errors.
^ the goal being to replace the word `aforementioned`.

2024-06-18 17:21 UTC, internetisaiah commented on _docs/_hidden/private_betas/post_user_track_synchronous.md
> +Successful messages will be met with the following response, which includes information about the user profile data that was updated.
```suggestion
Successful messages will return the following response, which includes information about the user profile data that was updated.
```

2024-06-18 17:21 UTC, internetisaiah commented on _docs/_hidden/private_betas/post_user_track_synchronous.md
> +### In what instances should I use the asynchronous or synchronous endpoint?
```suggestion
### Should I use the asynchronous or synchronous endpoint?
```

2024-06-18 17:21 UTC, internetisaiah commented on _docs/_hidden/private_betas/post_user_track_synchronous.md
> +### Does response time differ compared to the `/users/track` endpoint?
```suggestion
### Does response time differ from the `/users/track` endpoint?
```

2024-06-18 17:21 UTC, internetisaiah commented on _docs/_hidden/private_betas/post_user_track_synchronous.md
> +### Can you send multiple requests to this endpoint at the same time?
```suggestion
### Can I send multiple requests to this endpoint at the same time?
```

2024-06-18 18:03 UTC, internetisaiah approved these changes
LGTM

2024-06-18 18:04 UTC, merged