Partners: LiveRamp + Snowflake + Braze
braze-inc/braze-docs pull request #7563
Opened 2024-06-24 15:39 UTC by internetisaiah

# Pull Request/Issue Resolution

#### Description of Change:
Partners: LiveRamp + Snowflake + Braze. Original doc from partner [here](https://docs.google.com/document/d/1BqjLwdEWiK7o3FYdt2P1vxVc4Ik6yP-gZ_MZxFsCA0I/edit?usp=sharing). First-round Braze edits [here](https://docs.google.com/document/d/1Mx7wGDPUEVk6LvN3c9ksZik5AylhB3MhyWwaPhbwkGg/edit).

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [x] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @internetisaiah as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Ana Teresa Serafino on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @internetisaiah for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@internetisaiah</td>
    <td>Developer Guide<br>Technology partners<br>Channels</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>Frontend Infrastructure & Experience (FIX)</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

2024-07-18 01:49 UTC, internetisaiah commented
Hey @mpmpmpmp1 , this one's ready for review! Let me know if you have any questions!

2024-07-24 17:27 UTC, alex-braze reviewed
Added in just a couple of thoughts/comments. Outside of those this looks good to me!

2024-07-30 19:18 UTC, internetisaiah commented
hey @alex-braze , took me a bit to figure out, but you may have reviewed an older version of the page that is not a reflection of the current page. that being said, i'm still going to try to apply your suggestions--but you may want to check out the [latest deployment](https://braze-docs-p43esrm9q-braze.vercel.app/docs/partners/data_and_infrastructure_agility/advertising/liveramp) to double-check if there's anything else you want to change/add.

2024-07-30 19:21 UTC, internetisaiah commented on _docs/_partners/liveramp.md
> +  - Custom Identifiers from a platform partner, or one with which you have directly established an identity sync with LiveRamp, such as your internal Customer ID.
Which one is this referring to in [the latest deployment](https://braze-docs-p43esrm9q-braze.vercel.app/docs/partners/data_and_infrastructure_agility/advertising/liveramp/#use-cases)? I'm having a little trouble figuring it out 😅 @alex-braze

2024-07-31 20:59 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
>  | A Snowflake Braze integration | To integrate Snowflake with Braze, see [Snowflake integration guide]({{site.baseurl}}/partners/data_and_infrastructure_agility/data_warehouses/snowflake/).
Update: Step 1 + 2 is referenced as a single pre-req of setting up Braze's Snow Data Share.

2024-07-31 20:59 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +### Step 3: Install the LiveRamp Identity Resolution and Transcoding Native App
Step 3, 4 & 5: update to be a single step "Install the LiveRamp ID Res & Transcoding Native App and run initial setup" and link out to: https://docs.liveramp.com/identity/en/set-up-the-liveramp-native-app-in-snowflake.html

2024-07-31 20:59 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +### Step 6: Create the Input Table for Identity Resolution
Stays the same since it is nuanced and specific to Braze

2024-07-31 20:59 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +### Step 6: Create the Metadata Table
combine steps 6 + 7 into a single step " Create the Metadata Table and Perform the Identity Resolution operation and verify the output" and within the copy link out to the relevant pieces in LR's docs:
 - metadata table: https://docs.liveramp.com/identity/en/perform-identity-resolution-in-snowflake.html#create-the-metadata-table-for-pii-resolution--without-deconfliction--43
 - perform operations + view output: https://docs.liveramp.com/identity/en/perform-identity-resolution-in-snowflake.html#perform-the-identity-resolution-operation

2024-07-31 20:59 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +- **Data Minimization:** LiveRamp’s Activation app uses Snowflake’s Secure Data Share feature to effectively read the tables directly from your instance. No data is moved from Snowflake until the poi
remove line 123 - 126

2024-07-31 20:59 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +With your data now pseudonymized to your dedicated encoding of RampID, you have the ability to share the RampID-based tables to LiveRamp’s Managed Activation Application for streamlined fulfillment t
update: "With your data now pseudonymized to your dedicated encoding of RampID, you have the ability to share the RampID-based tables to LiveRamp’s Managed Activation Application for streamlined fulfillment to your key advertising platform partners."

2024-07-31 20:59 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +- **Actionable Person & Household Based Insights:** Consolidation of consumer touchpoints to a person-based view enables a more accurate understanding of consumer preferences for better audience segm
replace 16 - 19 with:

**Data Minimization:** LiveRamp’s Activation app uses Snowflake’s Secure Data Share feature to effectively read the tables directly from your instance. No data is moved from Snowflake until the point of delivery to the downstream partner.
- **Secure 1st Party Activation:** By using the above Identity Resolution application, LiveRamp’s Activation application will only utilize the RampID-based tables in your Snowflake instance, and thus PII will never have to leave your walls.
- **Expedite Time to Live:** By resolving data to RampID directly in your environment, delivery to an end destination can occur within a matter of hours, as compared to several days when using LiveRamp’s more traditional file-based approach. This greatly increases the ability to optimize campaign performance in a timely manner.
- **Operational Savings:** Similar to the above, through the use of Snowflake’s Secure Data Share feature customers save time and money when compared to coordinating egress of files to LiveRamp or directly to any end destination.

2024-08-02 02:00 UTC, internetisaiah commented
Hey @alex-braze , here's the new deployment with the changes we discussed:
https://braze-docs-akqmy2qmk-braze.vercel.app/docs/partners/data_and_infrastructure_agility/advertising/liveramp

If you could re-review when you have a second, that would be great! Thanks!

2024-08-05 15:59 UTC, alex-braze requested changes
two very very minor notes but approved otherwise!

2024-08-05 15:59 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
>  Now that your variables are set, create the metadata table for PII resolution. This will give details on the specific job type to be executed based on the category of identifiers involved. For a full
There's an extra ", which" at the end of the sentence

2024-08-05 15:59 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
>  Finally, preform the identity resolution operation in LiveRamp. For a full walkthrough, see [LiveRamp: Perform the Identity Resolution Operation](https://docs.liveramp.com/identity/en/perform-identit
Two small updates to the first sentence:
 - Correct "preform" and removing "in LiveRamp" since it won't be done inside the LR platform it will be done in the SF Native App.

Finally, perform the identity resolution operation.

2024-08-05 17:52 UTC, internetisaiah commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +Finally, preform the identity resolution operation in LiveRamp. For a full walkthrough, see [LiveRamp: Perform the Identity Resolution Operation](https://docs.liveramp.com/identity/en/perform-identit
```suggestion
Finally, preform the identity resolution operation. For a full walkthrough, see [LiveRamp: Preform the Identity Resolution Operation](https://docs.liveramp.com/identity/en/perform-identity-resolution-in-snowflake.html#perform-the-identity-resolution-operation).
```

2024-08-05 18:22 UTC, alex-braze commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +Finally, preform the identity resolution operation. For a full walkthrough, see [LiveRamp: Preform the Identity Resolution Operation](https://docs.liveramp.com/identity/en/perform-identity-resolution
Hey @internetisaiah this is still showing as "preform" instead of "perform"

2024-08-05 18:23 UTC, internetisaiah commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +Finally, preform the identity resolution operation. For a full walkthrough, see [LiveRamp: Preform the Identity Resolution Operation](https://docs.liveramp.com/identity/en/perform-identity-resolution
```suggestion
Finally, perform the identity resolution operation. For a full walkthrough, see [LiveRamp: Perform the Identity Resolution Operation](https://docs.liveramp.com/identity/en/perform-identity-resolution-in-snowflake.html#perform-the-identity-resolution-operation).
```

2024-08-05 18:24 UTC, internetisaiah commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +Finally, preform the identity resolution operation. For a full walkthrough, see [LiveRamp: Preform the Identity Resolution Operation](https://docs.liveramp.com/identity/en/perform-identity-resolution
Ah, should be fixed now 👍🏽

2024-08-05 18:25 UTC, internetisaiah commented on _docs/_partners/data_and_infrastructure_agility/advertising/liveramp.md
> +Finally, preform the identity resolution operation. For a full walkthrough, see [LiveRamp: Preform the Identity Resolution Operation](https://docs.liveramp.com/identity/en/perform-identity-resolution
```suggestion
Finally, perform the identity resolution operation. For a full walkthrough, see [LiveRamp: Perform the Identity Resolution Operation](https://docs.liveramp.com/identity/en/perform-identity-resolution-in-snowflake.html#perform-the-identity-resolution-operation).
```

2024-08-05 18:26 UTC, alex-braze approved these changes
Looks great!

2024-08-05 18:32 UTC, internetisaiah commented
@cla-bot check

2024-08-05 18:33 UTC, merged