[SDK-4819] Add log level descriptions for Android SDK
braze-inc/braze-docs pull request #7624
Opened 2024-07-02 21:49 UTC by vanessaland

### Summary

My PR adds additional information about each of the log levels that can be used in the Android SDK configurations.

### Related PRs, issues, or features (optional)

- [SDK-4819](https://jira.braze.com/browse/SDK-4819)

### Feature release date (optional)

- N/A

### Contributor checklist

- [x] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-07-02 22:46 UTC, radixdev approved these changes

2024-07-03 14:12 UTC, vanessaland commented
Hi @internetisaiah , this PR is ready on our end and open for review from the Docs Team. 

Thank you and have a great weekend ahead! 🙏🏼

2024-07-03 16:59 UTC, internetisaiah requested changes
Hey @vanessaland , I made some changes to the overall structure of the logging section to make it easier to understand/read. That being said:

1. Can you look over my changes to make sure I didn't misrepresent any of the original content.
2. Can you help me answer the 2 comments I left in the review?

Thanks! Let me know if you have any questions 👍🏽

2024-07-03 16:59 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
> +To enable logs in the Braze Android SDK, add the following to your `TODO` file:
@vanessaland , could you let me know where in the Braze SDK this should be set? Thanks!

2024-07-03 16:59 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
> +The default log level for the Braze Android SDK is `INFO`. To suppress all logs for the Braze Android SDK, call `BrazeLogger.SUPPRESS` in your `TODO` file.
@vanessaland , could you let me know where in the Braze SDK this should be set? Thanks!

2024-07-03 17:00 UTC, internetisaiah commented
> **NOTE:** Other files have been touched in due to my last commit because changed a heading from `Enabling verbose logging` to `Enabling logs`, so I needed to update any references to that specific heading.

2024-07-08 19:25 UTC, vanessaland reviewed
Hi @internetisaiah , thank you for reviewing and adding your edits! It's a lot more reader-friendly and descriptive!

I added my response to your questions and edits for some of the technicalities. Let me know what you think and feel free to edit it to your preference. Thanks! 🙏🏼

2024-07-08 19:25 UTC, vanessaland commented on _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
> +If you set `LOG_LEVEL_VALUE` to a number `>=` these values, the logs will be forwarded to Android's default [`Log`](https://developer.android.com/reference/android/util/Log) method. If the number is
This message was intended to tell the user that their log levels are inclusive to the logs with values equal to or above the set log level. Every log has a value and the set log level is to set what severity of logs I want to see.

For example, if I set my application's log level to `WARN`/`5`, I will be able to see logs of status `5`, `6`, `7`, and any logs of `4`, `3`, `2` will be dropped.

As another example, if I set my application's log level to `VERBOSE`/`2` (the most detailed level), I will be able to see all the logs of all values, `2`, `3`, `4`, `5`, `6`, and `7`.

```suggestion
Logs at levels `>=` to your set `LOG_LEVEL_VALUE` will be forwarded to Android's default [`Log`](https://developer.android.com/reference/android/util/Log) method. Any logs `<` your set `LOG_LEVEL_VALUE` will be discarded.
```

2024-07-08 19:25 UTC, vanessaland commented on _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
> +If you set `LOG_LEVEL_VALUE` to a number `>=` these values, the logs will be forwarded to Android's default [`Log`](https://developer.android.com/reference/android/util/Log) method. If the number is
We might also want to refactor this note and put it outside of the tabbing, since it's relevant to either way setting the log level. Let me know what you think!

2024-07-09 18:49 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
> +{% tab Braze SDK %}
```suggestion
{% tab Application %}
```

2024-07-09 18:51 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
> +To enable logs in the Braze Android SDK, add the following to your `TODO` file:
```suggestion
To enable logs in the Braze Android SDK, add the following to your applications `onCreate()` method _before_ any other methods.
```

2024-07-09 18:52 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
> +The default log level for the Braze Android SDK is `INFO`. To suppress all logs for the Braze Android SDK, call `BrazeLogger.SUPPRESS` in your `TODO` file.
```suggestion
The default log level for the Braze Android SDK is `INFO`. To suppress all logs for the Braze Android SDK, call `BrazeLogger.SUPPRESS` in your application's `onCreate()` method _before_ any other methods.
```

2024-07-09 19:04 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration.md
> +If you set `LOG_LEVEL_VALUE` to a number `>=` these values, the logs will be forwarded to Android's default [`Log`](https://developer.android.com/reference/android/util/Log) method. If the number is
```suggestion
Any logs at a level `>=` to your set `LOG_LEVEL_VALUE` will be forwarded to Android's default [`Log`](https://developer.android.com/reference/android/util/Log) method. Any logs `<` your set `LOG_LEVEL_VALUE` will be discarded.
<br><br>
For example, if `LOG_LEVEL_VALUE` is set to `2`,  logs at levels `2`, `3`, `4`, `5`, `6`, and `7` will be forwarded to the 'Log' method.
```

2024-07-09 21:14 UTC, internetisaiah commented
Hey @vanessaland , I incorporated your suggestions! (They were great btw). I'm going to merge this PR now, but let me know if this needs any tweaks in the future 👍🏽

2024-07-09 21:14 UTC, internetisaiah approved these changes
LGTM

2024-07-09 21:14 UTC, merged