Update Punchh Dynamic Code Generation liquid
braze-inc/braze-docs pull request #7828
Opened 2024-08-06 21:07 UTC by alex-braze

replacing liquid as previous liquid was not generating correctly

### Summary

My PR...

### Related PRs, issues, or features (optional)

- N/A

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-08-06 22:13 UTC, internetisaiah requested changes
Hey @alex-braze , most everything here looks good, but I noticed that most of the `{% raw %}{% endraw %}` tags were moved, which were breaking your [test deployment](https://braze-docs-igf8uqdqq-braze.vercel.app/). Just for a little background:

If you have any Liquid on a docs page, the docs site will try to execute that code as if its real Liquid. To avoid this, you need to wrap it in raw tags, like this:

``````
{% raw %}
```liquid
https://SERVER_NAME.punchh.com/request_coupons/DYNAMIC_COUPON_GENERATION_TOKEN?sign={{jwt}}
```
{% endraw %}
``````

Or like this:

``````
To link to a Puncch-hosted web page, add the Dynamic Generation URL provided in Punchh Campaign creation UI and replace `GENERATED_SIGNATURE` with `{% raw %}{{jwt}}{% endraw %}`:
``````

Hope this helps! Please let me know if you have questions. You can select **Add Suggestion to Batch** for each suggestion I left (you have to do this from the **Files** tab), then commit them all at once to update the page 👍🏽

2024-08-06 22:13 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
> +
```suggestion
{% raw %}
```

2024-08-06 22:13 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
> +
```suggestion
{% endraw %}

```

2024-08-06 22:13 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
> +To link to a Puncch-hosted web page, add the Dynamic Generation URL provided in Punchh Campaign creation UI and replace `GENERATED_SIGNATURE` with `{{jwt}}`:
```suggestion
To link to a Puncch-hosted web page, add the Dynamic Generation URL provided in Punchh Campaign creation UI and replace `GENERATED_SIGNATURE` with `{% raw %}{{jwt}}{% endraw %}`:
```

2024-08-06 22:13 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
>  ```liquid
```suggestion
{% raw %}
```liquid
```

2024-08-06 22:13 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
>  ```
``````suggestion
```
{% endraw %}

``````

2024-08-06 22:13 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
>  ```liquid
```suggestion
{% raw %}
```liquid
```

2024-08-06 22:13 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
> +````
``````suggestion
````
{% endraw %}
``````

2024-08-07 00:09 UTC, internetisaiah requested changes
Left a couple of comments and one suggestion, but after that, we should be good to go 👍🏽  @alex-braze

2024-08-07 00:09 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
> +{% connected_content https://example.punchh.com/request_coupons/XXXXXXXXXXXXX.json?sign={{jwt}} :save punchh_coupon %}
Its ok if we change the variable names from the original, but lets make sure that these are descriptive variables instead of `example` or `XXXXXXXXXXXXX`. Additionally, the variable should be all caps (as that is apart of our style guide).

2024-08-07 00:09 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
> +<img src="https://example.punchh.com/request_coupons/XXXXXXXXXXXXX.png?sign={{jwt}}">
Its ok if we change the variable names from the original, but lets make sure that these are descriptive variables instead of `example` or `XXXXXXXXXXXXX`. Additionally, the variable should be all caps (as that is apart of our style guide).

2024-08-07 00:09 UTC, internetisaiah commented on _docs/_partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation.md
> +To link the coupon code inside an image, add `.png` before the sign query parameter of the Dynamic Generation URL as shown in the following snippet example:
```suggestion
To link the coupon code inside an image, add `.png` after the Dynamic Generation URL, as shown in the following snippet:
```

2024-08-07 17:28 UTC, internetisaiah approved these changes
LGTM! Reverted the `11111` variable back to `DYNAMIC_COUPON_GENERATION_TOKEN` to keep it uniform with the earlier content + ensure that the variable is a descriptive name. Gonna merge and should be good for next deploy tomorrow 👍🏽 Thanks for working quick with me on this 🙌🏽

2024-08-07 17:33 UTC, alex-braze commented
@internetisaiah quick heads up! We had to change the original URL because it is no longer the DYNAMIC_COUPON_GENERATION_TOKEN that is included in the URL! This URL has to be pulled from the Punchh dashboard and does not include the token in it.

2024-08-07 17:46 UTC, internetisaiah commented
> @internetisaiah quick heads up! We had to change the original URL because it is no longer the DYNAMIC_COUPON_GENERATION_TOKEN that is included in the URL! This URL has to be pulled from the Punchh dashboard and does not include the token in it.

Ah, what about `URL_TOKEN` then a link to the Punchh docs on where they can find this? Would you happen to have a link?

2024-08-07 18:19 UTC, alex-braze commented
I'm hesitant to add any variable in that spot specifically because technically the entire dynamic generation URL would be a variable being replaced, but it's kind of confusing to just show this:

DYNAMIC-GENERATION-URL{{jwt}}

Here's where it is referenced in their docs:

https://developers.partech.com/docs/dev-portal-platform-functions/be3c7bd2c3908-punchh-dynamic-coupon-code-generation#:~:text=Dynamic%20Generation%20URL%3A%20This%20URL%20will%20be%20embedded%20in%20the%20email%20as%20a%20link%20or%20an%20image%2C%20as%20required%20by%20the%20business.

2024-08-07 20:40 UTC, internetisaiah commented
@alex-braze , ahh i think i'm understanding your concern now. how's this instead? placeholder values have been replaced with an actual example instead.

https://braze-docs-5jkuv01ju-braze.vercel.app/docs/partners/message_orchestration/channel_extensions/loyalty/punchh/code_generation/#step-3-append-coupon-code-to-message-body

2024-08-07 21:13 UTC, alex-braze commented
@internetisaiah LOVE IT!!!

2024-08-07 23:54 UTC, merged