[BD-2890] Sending empty PN messages
braze-inc/braze-docs pull request #7833
Opened 2024-08-07 17:40 UTC by internetisaiah

### Summary

We don't have expected behaviour documented if users send a Push without a title. Having raised with Support who conducted tests and checked with Product:

- you cannot send a blank title Android Push
- you CAN send a blank title with a space - this will deliver silently.
- you can send a blank title iOS - this will deliver silently.
- you can send a blank title with a space - this will deliver silently.

#### Pages to update

- [ ] [Creating a push message](https://www.braze.com/docs/user_guide/message_building_by_channel/push/creating_a_push_message/)
- [ ] [Android: Silent push notifications](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/silent_push_notifications/)
- [ ] [iOS: Silent push notifications](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications/)
- [ ] [Android: Notification options](https://www.braze.com/docs/user_guide/message_building_by_channel/push/android/notification_options/)
- [ ] [iOS: Notification options](https://www.braze.com/docs/user_guide/message_building_by_channel/push/ios/notification_options/)
- [ ] [Quick push campaigns](https://www.braze.com/docs/user_guide/message_building_by_channel/push/creating_a_push_message/quick_push/) - _maybe_ add an alert here?
- [ ] [Android: Rich Push Notifications](https://www.braze.com/docs/user_guide/message_building_by_channel/push/android/rich_notifications/#requirements) - maybe?
- [ ] [iOS: Rich Push Notifications](https://www.braze.com/docs/user_guide/message_building_by_channel/push/ios/rich_notifications/#requirements) - maybe?
- [ ] []()

### Related PRs, issues, or features (optional)

- [BD-2890](https://jira.braze.com/browse/BD-2890)

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-08-08 13:54 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
> +{% endalert %}
So... this is wrong haha. Not sure what was the testing methodology here.

The only way to send a silent push notification on Apple platform is this combination:
- `content-available` flag set to `1` + no title and no body

You can also send a combo silent + user visible notification with the following combination:
- `content-available` flag set to `1` + title and body
  - In that case, the notification is displayed to the user, and the app may be launched in the background like a silent notification do

The Braze platform:
- Allows an empty title, but requires a body
  - Empty title + body -> Push notification displayed with the name of the application as title
  - Empty title + single space body -> Push notification is not received by the device

Official doc: https://developer.apple.com/documentation/usernotifications/pushing-background-updates-to-your-app#Create-a-background-notification

2024-08-08 14:09 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
> +{% endalert %}
hmm, let me get back with the person who filed the ticket and see if i can get more information on how (and where) the testing was conducted. i assume this applies to both iOS and Android but you are the iOS SME, so you are only highlighting the process for iOS?

2024-08-08 15:27 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
> +{% endalert %}
Yep, I can only speak on the iOS side

2024-08-08 16:07 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
> +{% endalert %}
@lowip As I do more digging, quick follow up on this bit:

> The Braze platform: Allows an empty title, but requires a body:
> - Empty title + non-empty body -> Push notification displayed with the name of the application as title
> - Empty title + single space body -> Push notification is not received by the device

^ Just want to confirm, that _regardless_ of the title/body content, you **must** integrate silent push for iOS no matter what? If that's the case: If silent push for iOS is _not_ set up, will Braze notify you in the UI? or will it let you "send" even though it doesn't actually send?

2024-08-09 09:00 UTC, lowip commented on _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
> +{% endalert %}
The silent push integration is part of our standard push notification integration. It's very unlikely (though technically possible) that the client disable silent push notification handling. Braze is unable to detect this case and so it will let you "send" the push even though it cannot be processed by the device.

IMO, we shouldn't have to handle / document that integration scenario.

2024-08-09 18:35 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
> +{% endalert %}
Makes total sense. Thanks for the clarification. It helps me understand the problem you raised much better 👍🏽

2024-08-09 21:07 UTC, hokstuff requested changes
We should double check that the docs update is accurate with what we are seeing in practice. On iOS, I believe the instructions to add a single space for title / body is misleading

2024-08-09 21:07 UTC, hokstuff commented on _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
> +You can send an iOS push message without a title or a title with a single space. In either case, your message will be sent as a silent push notification. For more information, see [Silent push notifi
I'm also curious what testing was done for this. When I tried to send a push notification with KVPs but no body and no title (or a single space for both fields), no push notification was received by the app. This might be since the server doesn't send it, or the Apple SDK doesn't recognize it as a valid payload

I think we can reach out to the person who filed this since the docs update sounds misleading

2024-08-20 20:53 UTC, radixdev commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/silent_push_notifications.md
> +When you [compose your push notification message]({{site.baseurl}}/user_guide/message_building_by_channel/push/creating_a_push_message//?tab=android#step-4-compose-your-push-message), you can send a
@christorbraze @chrishaines does this have push composer implications? @internetisaiah these docs are really just posting about Composer behavior and not really the SDK behavior.

2024-08-20 20:55 UTC, radixdev commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/silent_push_notifications.md
> +When you [compose your push notification message]({{site.baseurl}}/user_guide/message_building_by_channel/push/creating_a_push_message//?tab=android#step-4-compose-your-push-message), you can send a
But yes, this new section is correct (as of Sweeney) and the `Silent notifications are also available within the dashboard. To send a silent notification, ensure the title and body fields of the notification are blank as pictured:
` section right below this seems wrong for Android

2024-08-23 01:11 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/android/push_notifications/android/silent_push_notifications.md
> +When you [compose your push notification message]({{site.baseurl}}/user_guide/message_building_by_channel/push/creating_a_push_message//?tab=android#step-4-compose-your-push-message), you can send a
Thanks for the info @radixdev . I applied your suggestion in commit [`2f3bc15`](https://github.com/braze-inc/braze-docs/pull/7833/commits/2f3bc15c97b8d1ef68ced13741815ae9383a3084).

2024-08-23 01:15 UTC, internetisaiah commented
The latest commit has the correct information for Android, but the iOS information seems to be incorrect with no good way to verify the testing (due to the ticket submitter being on parental leave--congrats btw 🎉 ).

That being said, I'm going to revert all the iOS changes, then merge the Android ones only. I'll update the Jira ticket with the information surfaced in this PR, including a link to the iOS commits should someone want to `git cherry-pick` them in the future.

2024-08-23 01:21 UTC, internetisaiah commented on _docs/_user_guide/message_building_by_channel/push/creating_a_push_message.md
> +#### On-select behavior
```suggestion
#### On-click behavior
```

2024-08-23 01:27 UTC, internetisaiah commented on _docs/_developer_guide/platform_integration_guides/swift/push_notifications/silent_push_notifications.md
> +{% endalert %}
Resolving conversation. If you'd like more info, see [my comment](https://github.com/braze-inc/braze-docs/pull/7833#issuecomment-2305998740).

2024-08-23 15:00 UTC, internetisaiah commented
@hokstuff , do you mind re-reviewing the PR so I can merge? I believe all iOS content should be removed now if you'd like to double check.

2024-08-23 15:41 UTC, hokstuff approved these changes

2024-08-23 15:51 UTC, merged