Add details for floats and strings for user attributes object
braze-inc/braze-docs pull request #7965
Opened 2024-08-27 18:38 UTC by lydia-xie

### Summary

My PR...

### Related PRs, issues, or features (optional)

- N/A

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-08-27 21:02 UTC, shihanxiong approved these changes

2024-08-27 21:11 UTC, lydia-xie commented on _docs/_api/objects_filters/user_attributes_object.md
> +| Strings | String custom attributes are sequences of characters used to store text data. For example, you can use strings to store user names, email addresses, or preferences. |
```suggestion
| Strings | String custom attributes are sequences of characters used to store text data. For example, you can use strings to store first and last names, email addresses, or preferences. |
```

2024-08-27 21:52 UTC, internetisaiah requested changes
Quick follow up question/statements here before merging.

2024-08-27 21:52 UTC, internetisaiah commented on _docs/_api/objects_filters/user_attributes_object.md
> +| Floats | Float custom attributes are numbers with a decimal point. For example, you can use floats to store user ratings for products or services. |
Couple things to specific here:

1. Can you assign a negative number? Or must it always be positive?
2. I think its good to add some info on the general "precise-ness" of the float. For context, in many program languages there are floats and doubles. For example in C++ a float holds up to 4 bytes while a double holds up to 8 bytes of memory (i.e. approximately 7 decimal digits of precision for floats vs 15 for doubles). That means if you want to reference an integer like `1.29837918769`, you will want to use a float over a double. We don't need to be _overly_ precise here, but maybe giving a general "up to 5 decimal digits" or something is fine (once we verify with prod/eng).

2024-08-27 22:00 UTC, lydia-xie commented on _docs/_api/objects_filters/user_attributes_object.md
> +| Floats | Float custom attributes are numbers with a decimal point. For example, you can use floats to store user ratings for products or services. |
1. I believe you can assign negative and positive numbers for floats. So for cases where a custom attribute is like a bank account balance, the float could be negative.
2. I don't think we have a specific limit for the number of digits in a float. I'm not entirely sure about the guidance here for how many decimal digits are recommended.

@shihanxiong - do you have any additional context here for @internetisaiah 's questions?

2024-08-29 16:16 UTC, shihanxiong commented on _docs/_api/objects_filters/user_attributes_object.md
> +| Floats | Float custom attributes are numbers with a decimal point. For example, you can use floats to store user ratings for products or services. |
1. float can be a negative number
2. Afaik ruby has a limit of 15 digits to float type

2024-08-29 16:30 UTC, lydia-xie commented on _docs/_api/objects_filters/user_attributes_object.md
> +| Floats | Float custom attributes are numbers with a decimal point. For example, you can use floats to store user ratings for products or services. |
```suggestion
| Floats | Float custom attributes are positive or negative numbers with a decimal point. For example, you can use floats to store account balances or user ratings for products or services. |
```

2024-08-29 17:17 UTC, internetisaiah commented on _docs/_api/objects_filters/user_attributes_object.md
> +| Floats | Float custom attributes are numbers with a decimal point. For example, you can use floats to store user ratings for products or services. |
cool. given that the max value is so high, i doubt customers will ever exceed it, so i don't think we need to specify that personally. but i trust your judgement @lydia-xie 👍🏽

2024-08-29 17:18 UTC, internetisaiah approved these changes
LGTM

2024-08-29 17:25 UTC, merged