BD-3442 Rename Sage AI to BrazeAI
braze-inc/braze-docs pull request #8040
Opened 2024-09-06 22:50 UTC by rachel-feinberg

### Summary

My PR changes mentions of Sage AI to BrazeAI.

### Related PRs, issues, or features (optional)

[BD-3442](https://jira.braze.com/browse/BD-3442)

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-09-09 22:26 UTC, rachel-feinberg commented on _lang/ja/_user_guide/sage_ai/generative_ai/ai_liquid.md
> +> BrazeAI Liquid Assistant は、BrazeAI を搭載したチャットアシスタントで、メッセージコンテンツをパーソナライズするために必要なLiquid を生成するのに役立ちます。
```suggestion
> AI Liquid Assistant は、BrazeAI を搭載したチャットアシスタントで、メッセージコンテンツをパーソナライズするために必要なLiquid を生成するのに役立ちます。 
```

2024-09-09 22:29 UTC, rachel-feinberg commented on _lang/ja/_user_guide/sage_ai/generative_ai/ai_liquid.md
> +AI Liquid Assistant を使用すると、テンプレート s からLiquid を生成したり、パーソナライズされた Liquid の提案を受信したり、BrazeAI を使用して既存のLiquid を最適化したりできます。AI Liquid Assistant には、使用されているLiquid を説明するアノテーションも用意されているため、Liquid について理解を深め、自分で書くこと
```suggestion
AI Liquid Assistant を使用すると、テンプレート s からLiquid を生成したり、パーソナライズされた Liquid の提案を受信したり、BrazeAI<sup>TM</sup> を使用して既存のLiquid を最適化したりできます。AI Liquid Assistant には、使用されているLiquid を説明するアノテーションも用意されているため、Liquid について理解を深め、自分で書くことを学ぶことができます。
```

2024-09-09 22:29 UTC, rachel-feinberg commented on _lang/ja/_user_guide/sage_ai/generative_ai/ai_liquid.md
> +description: "本稿では、BrazeAI Liquid Assistant の仕組みと、メッセージング用のLiquid スニペットの生成方法について説明します。"
```suggestion
description: "本稿では、AI Liquid Assistant の仕組みと、メッセージング用のLiquid スニペットの生成方法について説明します。"
```

2024-09-09 22:30 UTC, rachel-feinberg commented on _lang/ja/_user_guide/sage_ai/generative_ai.md
> +description: "BrazeAI by Brazeは、効率性と創造性を高める様々な自動生成AI機能を提供する。"
```suggestion
guide_top_text: "BrazeAI<sup>TM</sup> by Brazeは、効率性と創造性を高める様々な自動生成AI機能を提供する。定型的なコピーライティング作業、コンテンツの洗練、画像作成に費やす時間を減らしながら、魅力的なクロスチャネル顧客体験を創造する。<br><br>詳しくは以下の記事をご覧いただきたい。"
description: "BrazeAI<sup>TM</sup> by Brazeは、効率性と創造性を高める様々な自動生成AI機能を提供する。"
```

2024-09-09 22:30 UTC, rachel-feinberg commented on _lang/ja/_user_guide/sage_ai.md
> +description: "BrazeAI by Brazeは、クリエイティビティ、パーソナライゼーション、エンゲージメント戦略の最適化のための参入障壁を下げる、アクセスしやすく使いやすいツールのコレクションを提供する。"
```suggestion
guide_top_text: "BrazeAI<sup>TM</sup> by Brazeは、クリエイティビティ、パーソナライゼーション、エンゲージメント戦略の最適化のための参入障壁を下げる、アクセスしやすく使いやすいツールのコレクションを提供する。BrazeAI<sup>TM</sup> by Brazeの機能を使えば、創造性を導き、より良い決断を下し、顧客のユーザー体験を最適化するための信頼できるアドバイザーを持つことができる。"
description: "BrazeAI<sup>TM</sup> by Brazeは、クリエイティビティ、パーソナライゼーション、エンゲージメント戦略の最適化のための参入障壁を下げる、アクセスしやすく使いやすいツールのコレクションを提供する。"
```

2024-09-09 22:30 UTC, rachel-feinberg commented on _lang/ja/_user_guide/message_building_by_channel/sms/campaign/link_shortening.md
> +BrazeAIの[インテリジェントチャネルフィルター]({{site.baseurl}}/user_guide/sage_ai/intelligence/intelligent_channel/)を使用する予定があり、SMSチャネルを選択可能にしたい場合は、高度なトラッキングおよび[クリックトラッキング]({{site.baseurl}}/user_guide/message_building_
```suggestion
BrazeAI<sup>TM</sup>の[インテリジェントチャネルフィルター]({{site.baseurl}}/user_guide/sage_ai/intelligence/intelligent_channel/)を使用する予定があり、SMSチャネルを選択可能にしたい場合は、高度なトラッキングおよび[クリックトラッキング]({{site.baseurl}}/user_guide/message_building_by_channel/sms/campaign/link_shortening/#click-tracking)を使用してSMSリンクの短縮をオンにしてください。
```

2024-09-09 22:31 UTC, rachel-feinberg commented on _lang/ja/_help/release_notes/2024/7_23_24.md
> +BrazeAI Liquid AssistantはBrazeAIを搭載したチャットアシスタントで、メッセージ内容をパーソナライズするために必要なLiquidの生成をサポートする。テンプレートからリキッドを生成し、パーソナライズされたリキッドの提案を受け、セージAIのサポートで既存のリキッドを最適化することができる。AIリキッド・アシスタントは、使用されているリキッドを説明する注釈も提供するので、
```suggestion
AI Liquid AssistantはBrazeAIを搭載したチャットアシスタントで、メッセージ内容をパーソナライズするために必要なLiquidの生成をサポートする。テンプレートからリキッドを生成し、パーソナライズされたリキッドの提案を受け、セージAIのサポートで既存のリキッドを最適化することができる。AIリキッド・アシスタントは、使用されているリキッドを説明する注釈も提供するので、リキッドへの理解を深め、自分で書けるようになる。
```

2024-09-09 22:31 UTC, rachel-feinberg commented on _lang/ja/_help/release_notes/2024/4_2_24.md
> +以前は、Braze ダッシュボードでBrazeAIを使用して、SMSとプッシュ通知内容の品質保証を実行することができました。これで、[QA アプリ内メッセージ content]({{site.baseurl}}/user_guide/sage_ai/generative_ai/ai_content_qa/) もできます。
```suggestion
以前は、Braze ダッシュボードでBrazeAI<sup>TM</sup>を使用して、SMSとプッシュ通知内容の品質保証を実行することができました。これで、[QA アプリ内メッセージ content]({{site.baseurl}}/user_guide/sage_ai/generative_ai/ai_content_qa/) もできます。
```

2024-09-09 22:31 UTC, rachel-feinberg commented on _lang/ja/_help/release_notes/2024/4_2_24.md
> +BrazeAI by Brazeを使用すると、最も人気のあるプロダクトを計算したり、特定のカタログのパーソナライズされた AI 推奨を作成したりできます。詳細については、[項目の推奨事項について]({{site.baseurl}}/user_guide/sage_ai/recommendations/about_item_recommendations/)を参照してください。
```suggestion
BrazeAI<sup>TM</sup> by Brazeを使用すると、最も人気のあるプロダクトを計算したり、特定のカタログのパーソナライズされた AI 推奨を作成したりできます。詳細については、[項目の推奨事項について]({{site.baseurl}}/user_guide/sage_ai/recommendations/about_item_recommendations/)を参照してください。
```

2024-09-09 22:32 UTC, rachel-feinberg commented on _lang/ja/_help/release_notes.md
> +BrazeAI by Brazeを使えば、最も人気のある商品を計算したり、特定のカタログに対してパーソナライズされたAIレコメンデーションを作成したりすることができる。詳しくは、[アイテムの推奨についてを]({{site.baseurl}}/user_guide/sage_ai/recommendations/about_item_recommendations/)参照のこと。
```suggestion
BrazeAI<sup>TM</sup> by Brazeを使えば、最も人気のある商品を計算したり、特定のカタログに対してパーソナライズされたAIレコメンデーションを作成したりすることができる。詳しくは、[アイテムの推奨についてを]({{site.baseurl}}/user_guide/sage_ai/recommendations/about_item_recommendations/)参照のこと。
```

2024-09-09 22:32 UTC, rachel-feinberg commented on _lang/ja/_help/release_notes.md
> +以前は、BrazeのダッシュボードでBrazeAIを使ってSMSやプッシュ通知のコンテンツの品質保証を行うことができた。[アプリ内メッセージの内容もQA]({{site.baseurl}}/user_guide/sage_ai/generative_ai/ai_content_qa/)できるようになった。
```suggestion
以前は、BrazeのダッシュボードでBrazeAI<sup>TM</sup>を使ってSMSやプッシュ通知のコンテンツの品質保証を行うことができた。[アプリ内メッセージの内容もQA]({{site.baseurl}}/user_guide/sage_ai/generative_ai/ai_content_qa/)できるようになった。
```

2024-09-09 22:32 UTC, rachel-feinberg commented on _lang/ja/_help/release_notes/2023/7_25_23.md
> +BrazeAI by Brazeは、クリエイティビティ、パーソナライゼーション、エンゲージメント戦略の最適化のための参入障壁を下げる、アクセスしやすく使いやすいツールのコレクションを提供する。BrazeAIの特徴や機能の詳細については、[ドキュメントを]({{site.baseurl}}/user_guide/sage_ai)参照されたい。
```suggestion
BrazeAI<sup>TM</sup> by Brazeは、クリエイティビティ、パーソナライゼーション、エンゲージメント戦略の最適化のための参入障壁を下げる、アクセスしやすく使いやすいツールのコレクションを提供する。BrazeAIの特徴や機能の詳細については、[ドキュメントを]({{site.baseurl}}/user_guide/sage_ai)参照されたい。
```

2024-09-09 23:38 UTC, rachel-feinberg commented on _lang/ja/_help/release_notes.md
> +以前は、BrazeのダッシュボードでBrazeAIを使ってSMSやプッシュ通知のコンテンツの品質保証を行うことができた。[アプリ内メッセージの内容もQA]({{site.baseurl}}/user_guide/sage_ai/generative_ai/ai_content_qa/)できるようになった。
```suggestion
以前は、BrazeのダッシュボードでSage AIを使ってSMSやプッシュ通知のコンテンツの品質保証を行うことができた。[アプリ内メッセージの内容もQA]({{site.baseurl}}/user_guide/sage_ai/generative_ai/ai_content_qa/)できるようになった。
```

2024-09-09 23:38 UTC, rachel-feinberg commented on _lang/ja/_help/release_notes.md
> +BrazeAI by Brazeを使えば、最も人気のある商品を計算したり、特定のカタログに対してパーソナライズされたAIレコメンデーションを作成したりすることができる。詳しくは、[アイテムの推奨についてを]({{site.baseurl}}/user_guide/sage_ai/recommendations/about_item_recommendations/)参照のこと。
```suggestion
Sage AI by Brazeを使えば、最も人気のある商品を計算したり、特定のカタログに対してパーソナライズされたAIレコメンデーションを作成したりすることができる。詳しくは、[アイテムの推奨についてを]({{site.baseurl}}/user_guide/sage_ai/recommendations/about_item_recommendations/)参照のこと。
```

2024-09-09 23:39 UTC, rachel-feinberg commented on _lang/ja/_user_guide/sage_ai/generative_ai/ai_liquid.md
> +> BrazeAI Liquid Assistant は、BrazeAI を搭載したチャットアシスタントで、メッセージコンテンツをパーソナライズするために必要なLiquid を生成するのに役立ちます。
```suggestion
> Sage AI Liquid Assistant は、Sage AI を搭載したチャットアシスタントで、メッセージコンテンツをパーソナライズするために必要なLiquid を生成するのに役立ちます。 
```

2024-09-09 23:39 UTC, rachel-feinberg commented on _lang/ja/_user_guide/sage_ai/generative_ai/ai_liquid.md
> +AI Liquid Assistant を使用すると、テンプレート s からLiquid を生成したり、パーソナライズされた Liquid の提案を受信したり、BrazeAI を使用して既存のLiquid を最適化したりできます。AI Liquid Assistant には、使用されているLiquid を説明するアノテーションも用意されているため、Liquid について理解を深め、自分で書くこと
```suggestion
AI Liquid Assistant を使用すると、テンプレート s からLiquid を生成したり、パーソナライズされた Liquid の提案を受信したり、Sage AI を使用して既存のLiquid を最適化したりできます。AI Liquid Assistant には、使用されているLiquid を説明するアノテーションも用意されているため、Liquid について理解を深め、自分で書くことを学ぶことができます。
```

2024-09-16 18:09 UTC, internetisaiah commented
Old URLS to test for redirect:

https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/creating_a_churn_prediction/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/prediction_quality/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/messaging_users/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/prediction_faq/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_events/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_events/creating_an_event_prediction/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_events/prediction_analytics/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_events/messaging_users/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/intelligence/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/intelligence/intelligent_channel/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/intelligence/intelligent_selection/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/intelligence/intelligent_timing/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/intelligence/faqs
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/recommendations/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/recommendations/about_item_recommendations/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/recommendations/ai_item_recommendations/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/recommendations/rules_based_recommendations/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/generative_ai
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/generative_ai/ai_copywriting/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/generative_ai/ai_copywriting/brand_guidelines/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/generative_ai/ai_liquid/
https://braze-docs-gtcavota9-braze.vercel.app/docs/user_guide/sage_ai/generative_ai/ai_content_qa/

2024-09-16 18:22 UTC, internetisaiah requested changes
I reviewed most files, but to avoid leaving too many comments: some of the URLs that were changed were simply changing `sage_ai` to `brazeai` in the URL. These all seem to work 👍🏽 

However, the URLs where `brazeai` was _added_ don't seem to have redirects set up yet, so the are 404ing. For example:

**Old**
```
[Prediction Quality]({{site.baseurl}}/user_guide/predictive_suite/predictive_churn/prediction_analytics/prediction_quality/)
```

**New**
```
[Prediction Quality]({{site.baseurl}}/user_guide/brazeai/predictive_suite/predictive_churn/prediction_analytics/prediction_quality/)
```

2024-09-16 18:22 UTC, internetisaiah commented on _docs/_user_guide/brazeai/predictive_suite/predictive_churn.md
> -Once the prediction model is built, users in the prediction audience will be assigned a [churn risk score]({{site.baseurl}}/user_guide/predictive_suite/predictive_churn/prediction_analytics/#churn_sc
This URL needs a redirect set up still.

2024-09-16 18:22 UTC, internetisaiah commented on _docs/_user_guide/brazeai/intelligence/intelligent_timing.md
> -Learn more about [when Braze checks the eligibility criteria for segments and filters]({{site.baseurl}}/user_guide/intelligence/faqs/#when-does-braze-check-the-eligibility-criteria-for-segment-and-au
This one needs a URL redirect set up still.

2024-09-16 18:22 UTC, internetisaiah commented on _docs/_user_guide/brazeai/intelligence/intelligent_selection.md
> -We do not allow the use of Intelligent Selection with campaigns with re-eligibility enabled in under 24 hours because it would affect the integrity of the control variant. Check out [Intelligence FAQ
This one needs a URL redirect set up still.

2024-09-16 18:22 UTC, internetisaiah commented on _docs/_user_guide/brazeai/predictive_suite/predictive_churn/prediction_analytics.md
> -As soon as the prediction is done training and this page is populated, you can jump to simply using [filters]({{site.baseurl}}/user_guide/predictive_suite/predictive_churn/messaging_users/#filters) i
This one needs a URL redirect set up still.

2024-09-16 18:22 UTC, internetisaiah commented on _docs/_user_guide/brazeai/predictive_suite/predictive_churn/prediction_analytics.md
> -To measure the accuracy of your model, the _Prediction Quality_ metric will show you how effective this particular machine learning model appears to be when tested on historical data. Refer to [Predi
This one needs a URL redirect set up still.

2024-09-16 18:22 UTC, internetisaiah commented on _docs/_user_guide/brazeai/predictive_suite/predictive_churn/prediction_faq.md
> -If your model has a [prediction quality]({{site.baseurl}}/user_guide/predictive_suite/predictive_churn/prediction_analytics/prediction_quality/) of 40% or greater, you are in a great place! But if yo
This one needs a URL redirect set up still.

2024-09-17 16:42 UTC, internetisaiah commented
Old URLs to test for redirects:

```

https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/creating_a_churn_prediction/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/prediction_analytics/prediction_quality/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/messaging_users/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_churn/prediction_faq/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_events/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_events/creating_an_event_prediction/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_events/prediction_analytics/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/predictive_suite/predictive_events/messaging_users/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/intelligence/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/intelligence/intelligent_channel/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/intelligence/intelligent_selection/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/intelligence/intelligent_timing/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/intelligence/faqs
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/recommendations/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/recommendations/about_item_recommendations/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/recommendations/ai_item_recommendations/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/recommendations/rules_based_recommendations/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/generative_ai
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/generative_ai/ai_copywriting/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/generative_ai/ai_copywriting/brand_guidelines/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/generative_ai/ai_liquid/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/sage_ai/generative_ai/ai_content_qa/
https://braze-docs-kvrjikgcn-braze.vercel.app/docs/user_guide/predictive_suite/predictive_churn/prediction_analytics/#churn_score
https://braze-docs-kvrjikgcn-braze.vercel.app/user_guide/intelligence/faqs/#when-does-braze-check-the-eligibility-criteria-for-segment-and-audience-filters
https://braze-docs-kvrjikgcn-braze.vercel.app/user_guide/intelligence/faqs/#why-is-re-eligibility-not-available-when-combined-with-intelligent-selection
https://braze-docs-kvrjikgcn-braze.vercel.app/user_guide/predictive_suite/predictive_churn/messaging_users/#filters
https://braze-docs-kvrjikgcn-braze.vercel.app/user_guide/predictive_suite/predictive_churn/prediction_analytics/prediction_quality/
```

2024-09-17 16:53 UTC, internetisaiah requested changes
Looks like only one last link/page to fix!

2024-09-17 16:53 UTC, internetisaiah commented on _docs/_user_guide/brazeai/recommendations/about_item_recommendations.md
> -[selections]({{site.baseurl}}/user_guide/personalization_and_dynamic_content/catalogs/selections/). However, selections with Liquid cannot be used in AI recommendations, so keep that in mind when bui
For this one looks like the old link still works and the new link 404s. Maybe this file hasn't been moved renamed yet?

2024-09-17 16:59 UTC, rachel-feinberg commented on _docs/_user_guide/brazeai/recommendations/about_item_recommendations.md
> -[selections]({{site.baseurl}}/user_guide/personalization_and_dynamic_content/catalogs/selections/). However, selections with Liquid cannot be used in AI recommendations, so keep that in mind when bui
@internetisaiah That one shouldn't be redirecting. It's going to /docs/user_guide/brazeai/personalization_and_dynamic_content/catalogs/selections, which is incorrect. It should be going to /docs/user_guide/personalization_and_dynamic_content/catalogs/selections.

I can't locate the redirect link though 🤔

2024-09-17 17:02 UTC, internetisaiah commented on _docs/_user_guide/brazeai/recommendations/about_item_recommendations.md
> -[selections]({{site.baseurl}}/user_guide/personalization_and_dynamic_content/catalogs/selections/). However, selections with Liquid cannot be used in AI recommendations, so keep that in mind when bui
Oh sorry, it is _not_ redirecting. but the change below says that the new URL/path is:

```
/user_guide/brazeai/personalization_and_dynamic_content/catalogs/selections/
```

but that's not a real page in the PR that i can see?

2024-09-17 17:15 UTC, internetisaiah commented on _docs/_user_guide/brazeai/recommendations/about_item_recommendations.md
> +[Selections]({{site.baseurl}}/user_guide/brazeai/personalization_and_dynamic_content/catalogs/selections/) are specific groups of catalog data. When you use a selection, you're essentially setting up
@rachel-feinberg , looks like it might be the same thing with this one? may want to do a CMD+F for the selections url to ensure it hasn't changed elsewhere 👍🏽

2024-09-17 17:18 UTC, rachel-feinberg commented on _docs/_user_guide/brazeai/recommendations/about_item_recommendations.md
> +[Selections]({{site.baseurl}}/user_guide/brazeai/personalization_and_dynamic_content/catalogs/selections/) are specific groups of catalog data. When you use a selection, you're essentially setting up
Oomph. Yeah, this one had quite a few to fix. I just pushed a commit for them 🙇‍♀️

2024-09-17 18:07 UTC, internetisaiah approved these changes
LGTM

2024-09-17 18:24 UTC, merged