BD-3089 Create `includes` file for metrics
braze-inc/braze-docs pull request #8055
Opened 2024-09-11 18:03 UTC by rachel-feinberg

### Summary

My PR creates an includes file that contains metrics definitions, and inserts the include tag throughout the Docs site.

### Related PRs, issues, or features (optional)

[BD-3089](https://jira.braze.com/browse/BD-3089)

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-10-14 16:52 UTC, bre-fitzgerald approved these changes
Did a spot check of most of the pages and looks like everything is rendering as expected. Lgtm!

2024-10-15 16:27 UTC, lydia-xie requested changes
Left 2 comments for your review!

2024-10-15 16:27 UTC, lydia-xie commented on _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
> +=======
```suggestion
---

<style>
  .calculation-line {
    color: #76848C;
    font-size: 14px;
  }
</style>
=======
```
@rachel-feinberg I think this area might've broken [the page](https://braze-docs-gikztwry4-braze.vercel.app/docs/user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary)
![Screenshot 2024-10-15 at 9 22 18 AM](https://github.com/user-attachments/assets/06b53e96-8ea1-4f76-a72f-61ee22466efb)

2024-10-15 16:27 UTC, lydia-xie commented on _includes/campaign_analytics.md
> +=======
```suggestion
```
Suggestion to remove this, see https://braze-docs-gikztwry4-braze.vercel.app/docs/user_guide/message_building_by_channel/email/reporting_and_analytics/email_reporting/#email-performance:~:text=%3D%3D%3D%3D%3D%3D%3D%20Here%20are%20some,Analytics%20Glossary.

2024-10-15 16:51 UTC, rachel-feinberg commented on _docs/_user_guide/message_building_by_channel/email/reporting_and_analytics/analytics_glossary.md
> +=======
```suggestion
```

2024-10-15 17:32 UTC, merged