BD-3509 Add LINE message types
braze-inc/braze-docs pull request #8143
Opened 2024-09-23 21:55 UTC by rachel-feinberg

### Why are you making this change? (required)

Add LINE message types article

### Related PRs, issues, or features (optional)

[BD-3509](https://jira.braze.com/browse/BD-3509)

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-09-25 22:06 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/line/create/message_types.md
> +> This article covers the LINE message types you can compose, including aspects and li,itations, and is part of the LINE beta collection. [Return to the main page](https://www.braze.com/docs/line/).
```suggestion
> This article covers the LINE message types you can compose, including aspects and limitations, and is part of the LINE beta collection. [Return to the main page]({{site.baseurl}}/line/).
```

2024-09-25 22:08 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/line/create/message_types.md
> +A LINE image message can be added through the [Media Library]({{site.baseurl}}/user_guide/engagement_tools/templates_and_media/media_library/) or a URL.
We are no longer capitalizing media library! 

```suggestion
A LINE image message can be added through the [media library]({{site.baseurl}}/user_guide/engagement_tools/templates_and_media/media_library/) or a URL.
```

2024-09-25 22:11 UTC, bre-fitzgerald commented on _docs/_user_guide/message_building_by_channel/line/create/message_types.md
> +A LINE rich message is an image that contains one or more links that are opened by selecting specific areas on the image. Select a rich message templates to choose how the links are mapped onto the i
@rachel-feinberg can we add descriptions like this one to each of the message types? We need to make sure that the differences are clear even without the context of the pictures.

2024-09-26 17:51 UTC, internetisaiah requested changes
Left a few comments. Also agree with Bre's open comment as well. Great work overall!

2024-09-26 17:51 UTC, internetisaiah commented on _docs/_user_guide/message_building_by_channel/line/create/message_types.md
> +![][5]{: style="max-width:40%;"}
Be sure to add alt text to all images before you merge 👍🏽

2024-09-26 17:51 UTC, internetisaiah commented on _docs/_user_guide/message_building_by_channel/line/create/message_types.md
> +    - Include the Liquid in your image source attribute. For example, you can insert {% raw %} `https://example.com/images/?imageBanner={{first_name}}` {% endraw %} as the image URL to include a user
```suggestion
```

2024-09-26 17:51 UTC, internetisaiah commented on _docs/_user_guide/message_building_by_channel/line/create/message_types.md
> +- Liquid dynamic images
```suggestion
- Liquid dynamic images by including the Liquid in your image source attribute. For example, you can insert {% raw %} `https://example.com/images/?imageBanner={{first_name}}` {% endraw %} as the image URL to include a user's first name in the image.
```

2024-09-26 17:51 UTC, internetisaiah commented on _docs/_user_guide/message_building_by_channel/line/create/message_types.md
> +- Liquid dynamic images
(Note: typically i try to avoid the multi-nested bullets if possible because i feel it can be a bit busy).

2024-09-30 17:49 UTC, bre-fitzgerald approved these changes
lgtm!

2024-10-01 19:12 UTC, internetisaiah approved these changes
LGTM

2024-10-01 19:13 UTC, merged