BD-3664 Outgrow partner docs
braze-inc/braze-docs pull request #8423
Opened 2024-11-14 22:01 UTC by rachel-feinberg

### Why are you making this change? (required)

Add Outgrow docs

### Related PRs, issues, or features (optional)

[BD-3664](https://jira.braze.com/browse/BD-3664)

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-12-02 17:43 UTC, internetisaiah requested changes
@rachel-feinberg , heads up: you'll need to add the link for `outgrow.md` to all the landing pages of the parent directories, up till `_partners`. so there should be about 3 landing pages modified in total (and you already did 1). 👍🏽

2024-12-02 22:40 UTC, internetisaiah approved these changes
LGTM, feel free to merge whenever the partner is ready to go live 👍🏽

2024-12-03 15:41 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/outgrow.md
> +{: .reset-td-br-1 .reset-td-br-2 role="presentation" }git
```suggestion
{: .reset-td-br-1 .reset-td-br-2 role="presentation" }
```
I think this is breaking your table

2024-12-03 15:42 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/outgrow.md
> +| **API key** | An API Key from Braze with appropriate permissions (such as `users.track`) to enable user data transfer. |
I wonder if we should be crisper about what the "appropriate permissions" are? If we don't know, how would the user?

2024-12-03 15:43 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/outgrow.md
> +| **API key** | An API Key from Braze with appropriate permissions (such as `users.track`) to enable user data transfer. |
```suggestion
| **API key** | An API Key from Braze with appropriate permissions (such as `users.track`) to enable user data transfer |
```

If the other table entries don't have a period, let's remove it here, too.

2024-12-03 15:44 UTC, josh-mccrowell-braze commented on _docs/_partners/data_and_infrastructure_agility/leads_capture/outgrow.md
> +2. Select **Create Campaign** and choose your campaign type (email, push, in-app message, or others.).
```suggestion
2. Select **Create Campaign** and choose your campaign type (email, push, in-app message, or others).
```

2024-12-03 15:45 UTC, josh-mccrowell-braze approved these changes
A few nitpicks, but otherwise looking good to go!

2024-12-03 17:23 UTC, merged