BD-3727 B2B Salesforce Sales Cloud use case
braze-inc/braze-docs pull request #8663
Opened 2024-12-19 23:51 UTC by rachel-feinberg

### Why are you making this change? (required)
Adding a B2B use case for Salesforce Sales Cloud

### Related PRs, issues, or features (optional)
[BD-3727](https://jira.braze.com/browse/BD-3727)

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-12-20 20:37 UTC, rachel-feinberg commented on _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
> +This example specifically demonstrates how to update a lead’s lead stage to “MQL” (Marketing Qualified Lead) after a lead crosss a certain lead threshold. This is a core part of our [B2B lead scoring
```suggestion
This example specifically demonstrates how to update a lead’s lead stage to “MQL” (Marketing Qualified Lead) after a lead crosses a certain lead threshold. This is a core part of our [B2B lead scoring workflow]({{site.baseurl}}/user_guide/getting_started/b2b_use_cases/lead_scoring/) use case.
```

2024-12-20 20:39 UTC, rachel-feinberg commented on _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
> +1. Go to **Platform Tools** > **Apps** > **App Manager**.
```suggestion
1. In Salesforce, go to **Platform Tools** > **Apps** > **App Manager**.
```

2024-12-20 20:39 UTC, rachel-feinberg commented on _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
> +1. Go to **Platform Tools** > **Apps** > **App Manager**.
```suggestion
1. In Salesforce, go to **Platform Tools** > **Apps** > **App Manager**.
```

2025-01-07 18:06 UTC, internetisaiah requested changes
Left some feedback for a couple changes, but overall great job!

2025-01-07 18:06 UTC, internetisaiah commented on _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
> +## Troubleshooting
Can we move this to the end of the file instead of in the middle? I'm assuming its here because as of now the troubleshooting only applies to the first 2 sections, but incase this is expanded in the future, I think its still best to keep this at the end for page organization purposes.

2025-01-07 18:06 UTC, internetisaiah commented on _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
> +2. In the “MQL Threshold” group, look for any users who currently don’t have a status of “MQL” (for example, `lead_stage` equals “Lead”), but have a lead score that is over your defined threshold (fo
```suggestion
2. In the “MQL Threshold” group, look for any users who currently don’t have a status of “MQL” (for example, `lead_stage` equals “Lead”), but have a lead score that is over your defined threshold (for example, `lead_score` greater than 50). If so, they move forward to the next step, if not, they exit.
```

2025-01-07 18:06 UTC, internetisaiah commented on _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
> +2. In the “MQL Threshold” group, look for any users who currently don’t have a status of “MQL” (for example, `lead_stage` equals “Lead”), but have a lead score that is over your defined threshold (fo
Since you use "equals" instead of "=" in the previous sentence, i changed this one to match.

2025-01-07 18:06 UTC, internetisaiah commented on _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
> +4. Add a webhook step that updates Salesforce with the new MQL stage
```suggestion
4. Add a webhook step that updates Salesforce with the new MQL stage.
```

2025-01-07 18:13 UTC, rachel-feinberg commented on _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
> +
```suggestion
```

2025-01-07 18:14 UTC, rachel-feinberg commented on _docs/_user_guide/getting_started/b2b_use_cases/b2b_salesforce_sales_cloud.md
> +
```suggestion

## Troubleshooting

These workflows have limited debugging capability within Salesforce, so we recommend referring to the Braze [Message Activity Log]({{site.baseurl}}/user_guide/administrative/app_settings/message_activity_log_tab#message-activity-log) to find out why a Webhook failed and if any errors occurred.

For example, an error caused by an invalid URL used for oAuth token retrieval would display as `https://[insert_instance_name].my.salesforce.com/services/oauth2/token is not a valid URL`.

![An error response body stating that the URL isn't a valid URL.][8]

```

2025-01-07 19:02 UTC, internetisaiah approved these changes
LGTM

2025-01-07 19:15 UTC, merged