BD-3790 Apply template standards to Custom Data
braze-inc/braze-docs pull request #8667
Opened 2024-12-20 23:52 UTC by rachel-feinberg

### Why are you making this change? (required)
Apply Diataxis standards to Custom Data.

### Related PRs, issues, or features (optional)
[BD-3790](https://jira.braze.com/browse/BD-3790)

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

2024-12-27 19:53 UTC, internetisaiah requested changes
Great job overall! Left a few suggestions 🫡

2024-12-27 19:53 UTC, internetisaiah commented on _docs/_user_guide/data_and_analytics/custom_data/custom_attributes.md
> +> This page covers, custom attributes, which are a collection of your users' unique traits. Custom attributes are best for storing attributes about your users, or information about low-value actions
```suggestion
> This page covers custom attributes, which are a collection of your users' unique traits. Custom attributes are best for storing attributes about your users, or information about low-value actions within your application. 
```

2024-12-27 19:53 UTC, internetisaiah commented on _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
```suggestion

{% alert note %}
```

2024-12-27 19:53 UTC, internetisaiah commented on _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
> +Note that for nested custom attributes, if the year is less than 0 or greater than 3000, Braze doesn't store these values on the user.
```suggestion
For nested custom attributes, if the year is less than 0 or greater than 3000, Braze doesn't store these values on the user.
```

2024-12-27 19:53 UTC, internetisaiah commented on _docs/_user_guide/data_and_analytics/custom_data/custom_attributes/nested_custom_attribute_support.md
```suggestion
{% endalert %}

```

2024-12-27 19:53 UTC, internetisaiah commented on _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
> +To access the nested data in your custom event, generate a schema for each event with nested event properties. Generate a schema by following these steps:
```suggestion
You can access the nested data in your custom event by generating a schema for each event with nested event properties. To generate a schema:
```

2024-12-27 19:53 UTC, internetisaiah commented on _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
> +The following Liquid templating examples demonstrate how to reference the nested properties saved from the preceding API request and use them in your Liquid messaging. Using Liquid and dot notation,
```suggestion
The following shows how to create a Liquid template that references the nested properties requested from the [previous API request](#api-request-body).
```

2024-12-27 19:53 UTC, internetisaiah commented on _docs/_user_guide/data_and_analytics/custom_data/custom_events/nested_objects.md
> +The following Liquid templating examples demonstrate how to reference the nested properties saved from the preceding API request and use them in your Liquid messaging. Using Liquid and dot notation,
**Note:** the current change (not my suggestion above) seems to have a type/missing word after "the template will...".

My suggestion helps trim down the content, but _may_ not accurately describe the original intent, so please re-read before committing.

2024-12-27 19:53 UTC, internetisaiah commented on _docs/_user_guide/data_and_analytics/custom_data/event_naming_conventions.md
> +> Maintaining consistency in your event and attribute taxonomy during your Braze integration will keep your data clean and usable for new and existing users of the Braze platform. This helps to avoid
```suggestion
> This page covers proper event naming conventions and best practices. By maintaining consistency in your event and attribute taxonomy, you'll keep your data clean and usable for new and existing users of the Braze platform. This helps avoid issues later, such as triggering a campaign to the wrong audience or generating wrong results after using the wrong event.
```

2024-12-27 19:53 UTC, internetisaiah commented on _docs/_user_guide/data_and_analytics/custom_data/events.md
> -By tracking these different types of events, you can gain a deeper understanding of your users, which can inform your marketing strategies, help you optimize your app, and enable you to provide a mor
the original (with a `.`) is hilarious to me 😂

2025-01-06 18:51 UTC, lydia-xie approved these changes
looks great! :)

2025-01-06 19:04 UTC, merged